package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class axl {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final cfp D;
    public static final cfr E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final cfp I;
    public static final cfr J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final cfp N;
    public static final cfr O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final cfp S;
    public static final cfr T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final cfp X;
    public static final cfr Y;
    public static final long Z;
    public static final cfr a;
    public static final long aA;
    public static final cfp aB;
    public static final cfr aC;
    public static final long aD;
    public static final long aE;
    public static final long aF;
    public static final cfp aG;
    public static final cfr aH;
    public static final long aI;
    public static final long aJ;
    public static final long aK;
    public static final cfp aL;
    public static final cfr aM;
    public static final long aN;
    public static final long aO;
    public static final long aP;
    public static final cfp aQ;
    public static final cfr aR;
    public static final long aS;
    public static final long aT;
    public static final long aU;
    public static final cfp aV;
    public static final cfr aW;
    public static final long aX;
    public static final long aY;
    public static final long aZ;
    public static final long aa;
    public static final long ab;
    public static final cfp ac;
    public static final cfr ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final cfp ah;
    public static final cfr ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final cfp am;
    public static final cfr an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final cfp ar;
    public static final cfr as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final cfp aw;
    public static final cfr ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final cfr bA;
    public static final long bB;
    public static final long bC;
    public static final long bD;
    public static final cfp bE;
    public static final cfr bF;
    public static final long bG;
    public static final long bH;
    public static final long bI;
    public static final cfp bJ;
    public static final cfr bK;
    public static final long bL;
    public static final long bM;
    public static final long bN;
    public static final cfp bO;
    public static final cfr bP;
    public static final long bQ;
    public static final long bR;
    public static final long bS;
    public static final cfp bT;
    public static final cfp ba;
    public static final cfr bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final cfp bf;
    public static final cfr bg;
    public static final long bh;
    public static final long bi;
    public static final long bj;
    public static final cfp bk;
    public static final cfr bl;
    public static final long bm;
    public static final long bn;
    public static final long bo;
    public static final cfp bp;
    public static final cfr bq;
    public static final long br;
    public static final long bs;
    public static final long bt;
    public static final cfp bu;
    public static final cfr bv;
    public static final long bw;
    public static final long bx;
    public static final long by;
    public static final cfp bz;
    public static final long c;
    public static final long d;
    public static final cfp e;
    public static final cfr f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final cfp j;
    public static final cfr k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final cfp o;
    public static final cfr p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final cfp t;
    public static final cfr u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final cfp y;
    public static final cfr z;

    static {
        cfr cfrVar = axm.a;
        a = axm.b;
        b = chp.A(24.0d);
        c = chp.C(16);
        d = chp.A(0.5d);
        e = axm.e;
        f = axm.b;
        g = chp.A(20.0d);
        h = chp.C(14);
        i = chp.A(0.2d);
        j = axm.e;
        k = axm.b;
        l = chp.A(16.0d);
        m = chp.C(12);
        n = chp.A(0.4d);
        o = axm.e;
        p = axm.a;
        q = chp.A(64.0d);
        r = chp.C(57);
        long jA = chp.A(0.2d);
        if (cid.a(jA) == 0) {
            chx.a("Cannot perform operation for Unspecified type.");
        }
        s = chp.D(cid.a(jA), -Float.intBitsToFloat((int) (jA & 4294967295L)));
        t = axm.e;
        u = axm.a;
        v = chp.A(52.0d);
        w = chp.C(45);
        x = chp.A(0.0d);
        y = axm.e;
        z = axm.a;
        A = chp.A(44.0d);
        B = chp.C(36);
        C = chp.A(0.0d);
        D = axm.e;
        E = axm.a;
        F = chp.A(40.0d);
        G = chp.C(32);
        H = chp.A(0.0d);
        I = axm.e;
        J = axm.a;
        K = chp.A(36.0d);
        L = chp.C(28);
        M = chp.A(0.0d);
        N = axm.e;
        O = axm.a;
        P = chp.A(32.0d);
        Q = chp.C(24);
        R = chp.A(0.0d);
        S = axm.e;
        T = axm.b;
        U = chp.A(20.0d);
        V = chp.C(14);
        W = chp.A(0.1d);
        X = axm.d;
        Y = axm.b;
        Z = chp.A(16.0d);
        aa = chp.C(12);
        ab = chp.A(0.5d);
        ac = axm.d;
        ad = axm.b;
        ae = chp.A(16.0d);
        af = chp.C(11);
        ag = chp.A(0.5d);
        ah = axm.d;
        ai = axm.a;
        aj = chp.A(28.0d);
        ak = chp.C(22);
        al = chp.A(0.0d);
        am = axm.e;
        an = axm.b;
        ao = chp.A(24.0d);
        ap = chp.C(16);
        aq = chp.A(0.2d);
        ar = axm.d;
        as = axm.b;
        at = chp.A(20.0d);
        au = chp.C(14);
        av = chp.A(0.1d);
        aw = axm.d;
        ax = axm.b;
        ay = chp.A(24.0d);
        az = chp.C(16);
        aA = chp.A(0.15d);
        aB = axm.d;
        aC = axm.b;
        aD = chp.A(20.0d);
        aE = chp.C(14);
        aF = chp.A(0.25d);
        aG = axm.d;
        aH = axm.b;
        aI = chp.A(16.0d);
        aJ = chp.C(12);
        aK = chp.A(0.4d);
        aL = axm.d;
        aM = axm.a;
        aN = chp.A(64.0d);
        aO = chp.C(57);
        aP = chp.C(0);
        aQ = axm.d;
        aR = axm.a;
        aS = chp.A(52.0d);
        aT = chp.C(45);
        aU = chp.C(0);
        aV = axm.d;
        aW = axm.a;
        aX = chp.A(44.0d);
        aY = chp.C(36);
        aZ = chp.C(0);
        ba = axm.d;
        bb = axm.a;
        bc = chp.A(40.0d);
        bd = chp.C(32);
        be = chp.C(0);
        bf = axm.d;
        bg = axm.a;
        bh = chp.A(36.0d);
        bi = chp.C(28);
        bj = chp.C(0);
        bk = axm.d;
        bl = axm.a;
        bm = chp.A(32.0d);
        bn = chp.C(24);
        bo = chp.C(0);
        bp = axm.d;
        bq = axm.b;
        br = chp.A(20.0d);
        bs = chp.C(14);
        bt = chp.A(0.1d);
        bu = axm.c;
        bv = axm.b;
        bw = chp.A(16.0d);
        bx = chp.C(12);
        by = chp.A(0.5d);
        bz = axm.c;
        bA = axm.b;
        bB = chp.A(16.0d);
        bC = chp.C(11);
        bD = chp.A(0.5d);
        bE = axm.c;
        bF = axm.a;
        bG = chp.A(28.0d);
        bH = chp.C(22);
        bI = chp.C(0);
        bJ = axm.d;
        bK = axm.b;
        bL = chp.A(24.0d);
        bM = chp.C(16);
        bN = chp.A(0.15d);
        bO = axm.c;
        bP = axm.b;
        bQ = chp.A(20.0d);
        bR = chp.C(14);
        bS = chp.A(0.1d);
        bT = axm.c;
    }
}
