package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class ckp {
    int a;
    public final cks b = new cks();
    public final ckr c = new ckr();
    public final ckq d = new ckq();
    public final ckt e = new ckt();
    public HashMap f = new HashMap();
    cko g;

    public final void a(ckl cklVar) {
        ckq ckqVar = this.d;
        cklVar.e = ckqVar.j;
        cklVar.f = ckqVar.k;
        cklVar.g = ckqVar.l;
        cklVar.h = ckqVar.m;
        cklVar.i = ckqVar.n;
        cklVar.j = ckqVar.o;
        cklVar.k = ckqVar.p;
        cklVar.l = ckqVar.q;
        cklVar.m = ckqVar.r;
        cklVar.n = ckqVar.s;
        cklVar.o = ckqVar.t;
        cklVar.s = ckqVar.u;
        cklVar.t = ckqVar.v;
        cklVar.u = ckqVar.w;
        cklVar.v = ckqVar.x;
        cklVar.leftMargin = ckqVar.H;
        cklVar.rightMargin = ckqVar.I;
        cklVar.topMargin = ckqVar.J;
        cklVar.bottomMargin = ckqVar.K;
        cklVar.A = ckqVar.T;
        cklVar.B = ckqVar.S;
        cklVar.x = ckqVar.P;
        cklVar.z = ckqVar.R;
        cklVar.G = ckqVar.y;
        cklVar.H = ckqVar.z;
        cklVar.p = ckqVar.B;
        cklVar.q = ckqVar.C;
        cklVar.r = ckqVar.D;
        cklVar.I = ckqVar.A;
        cklVar.X = ckqVar.E;
        cklVar.Y = ckqVar.F;
        cklVar.M = ckqVar.V;
        cklVar.L = ckqVar.W;
        cklVar.O = ckqVar.Y;
        cklVar.N = ckqVar.X;
        cklVar.aa = ckqVar.an;
        cklVar.ab = ckqVar.ao;
        cklVar.P = ckqVar.Z;
        cklVar.Q = ckqVar.aa;
        cklVar.T = ckqVar.ab;
        cklVar.U = ckqVar.ac;
        cklVar.R = ckqVar.ad;
        cklVar.S = ckqVar.ae;
        cklVar.V = ckqVar.af;
        cklVar.W = ckqVar.ag;
        cklVar.Z = ckqVar.G;
        cklVar.c = ckqVar.h;
        cklVar.a = ckqVar.f;
        cklVar.b = ckqVar.g;
        cklVar.width = ckqVar.d;
        cklVar.height = ckqVar.e;
        String str = ckqVar.am;
        if (str != null) {
            cklVar.ac = str;
        }
        cklVar.ad = ckqVar.aq;
        cklVar.setMarginStart(ckqVar.M);
        cklVar.setMarginEnd(ckqVar.L);
        cklVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ckp ckpVar = new ckp();
        ckq ckqVar = ckpVar.d;
        ckq ckqVar2 = this.d;
        ckqVar.b = ckqVar2.b;
        ckqVar.d = ckqVar2.d;
        ckqVar.c = ckqVar2.c;
        ckqVar.e = ckqVar2.e;
        ckqVar.f = ckqVar2.f;
        ckqVar.g = ckqVar2.g;
        ckqVar.h = ckqVar2.h;
        ckqVar.i = ckqVar2.i;
        ckqVar.j = ckqVar2.j;
        ckqVar.k = ckqVar2.k;
        ckqVar.l = ckqVar2.l;
        ckqVar.m = ckqVar2.m;
        ckqVar.n = ckqVar2.n;
        ckqVar.o = ckqVar2.o;
        ckqVar.p = ckqVar2.p;
        ckqVar.q = ckqVar2.q;
        ckqVar.r = ckqVar2.r;
        ckqVar.s = ckqVar2.s;
        ckqVar.t = ckqVar2.t;
        ckqVar.u = ckqVar2.u;
        ckqVar.v = ckqVar2.v;
        ckqVar.w = ckqVar2.w;
        ckqVar.x = ckqVar2.x;
        ckqVar.y = ckqVar2.y;
        ckqVar.z = ckqVar2.z;
        ckqVar.A = ckqVar2.A;
        ckqVar.B = ckqVar2.B;
        ckqVar.C = ckqVar2.C;
        ckqVar.D = ckqVar2.D;
        ckqVar.E = ckqVar2.E;
        ckqVar.F = ckqVar2.F;
        ckqVar.G = ckqVar2.G;
        ckqVar.H = ckqVar2.H;
        ckqVar.I = ckqVar2.I;
        ckqVar.J = ckqVar2.J;
        ckqVar.K = ckqVar2.K;
        ckqVar.L = ckqVar2.L;
        ckqVar.M = ckqVar2.M;
        ckqVar.N = ckqVar2.N;
        ckqVar.O = ckqVar2.O;
        ckqVar.P = ckqVar2.P;
        ckqVar.Q = ckqVar2.Q;
        ckqVar.R = ckqVar2.R;
        ckqVar.S = ckqVar2.S;
        ckqVar.T = ckqVar2.T;
        ckqVar.U = ckqVar2.U;
        ckqVar.V = ckqVar2.V;
        ckqVar.W = ckqVar2.W;
        ckqVar.X = ckqVar2.X;
        ckqVar.Y = ckqVar2.Y;
        ckqVar.Z = ckqVar2.Z;
        ckqVar.aa = ckqVar2.aa;
        ckqVar.ab = ckqVar2.ab;
        ckqVar.ac = ckqVar2.ac;
        ckqVar.ad = ckqVar2.ad;
        ckqVar.ae = ckqVar2.ae;
        ckqVar.af = ckqVar2.af;
        ckqVar.ag = ckqVar2.ag;
        ckqVar.ah = ckqVar2.ah;
        ckqVar.ai = ckqVar2.ai;
        ckqVar.aj = ckqVar2.aj;
        ckqVar.am = ckqVar2.am;
        int[] iArr = ckqVar2.ak;
        if (iArr == null || ckqVar2.al != null) {
            ckqVar.ak = null;
        } else {
            ckqVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        ckqVar.al = ckqVar2.al;
        ckqVar.an = ckqVar2.an;
        ckqVar.ao = ckqVar2.ao;
        ckqVar.ap = ckqVar2.ap;
        ckqVar.aq = ckqVar2.aq;
        ckr ckrVar = ckpVar.c;
        ckr ckrVar2 = this.c;
        ckrVar.b = ckrVar2.b;
        ckrVar.c = ckrVar2.c;
        ckrVar.e = ckrVar2.e;
        ckrVar.f = ckrVar2.f;
        ckrVar.g = ckrVar2.g;
        ckrVar.j = ckrVar2.j;
        ckrVar.h = ckrVar2.h;
        ckrVar.i = ckrVar2.i;
        cks cksVar = ckpVar.b;
        cks cksVar2 = this.b;
        cksVar.a = cksVar2.a;
        cksVar.b = cksVar2.b;
        cksVar.d = cksVar2.d;
        cksVar.e = cksVar2.e;
        cksVar.c = cksVar2.c;
        ckt cktVar = ckpVar.e;
        ckt cktVar2 = this.e;
        cktVar.b = cktVar2.b;
        cktVar.c = cktVar2.c;
        cktVar.d = cktVar2.d;
        cktVar.e = cktVar2.e;
        cktVar.f = cktVar2.f;
        cktVar.g = cktVar2.g;
        cktVar.h = cktVar2.h;
        cktVar.i = cktVar2.i;
        cktVar.j = cktVar2.j;
        cktVar.k = cktVar2.k;
        cktVar.l = cktVar2.l;
        cktVar.m = cktVar2.m;
        cktVar.n = cktVar2.n;
        cktVar.o = cktVar2.o;
        ckpVar.a = this.a;
        ckpVar.g = this.g;
        return ckpVar;
    }
}
