package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class dsl {
    public static final float A;
    public static final String B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final float F;
    public static final float G;
    public static final String H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final float L;
    public static final float M;
    public static final String N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final float R;
    public static final float S;
    public static final String T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final float X;
    public static final float Y;
    public static final String Z;
    public static final String a;
    public static final long aA;
    public static final float aB;
    public static final float aC;
    public static final String aD;
    public static final long aE;
    public static final long aF;
    public static final long aG;
    public static final float aH;
    public static final float aI;
    public static final String aJ;
    public static final long aK;
    public static final long aL;
    public static final long aM;
    public static final float aN;
    public static final float aO;
    public static final String aP;
    public static final long aQ;
    public static final long aR;
    public static final long aS;
    public static final float aT;
    public static final float aU;
    public static final String aV;
    public static final long aW;
    public static final long aX;
    public static final long aY;
    public static final float aZ;
    public static final long aa;
    public static final long ab;
    public static final long ac;
    public static final float ad;
    public static final float ae;
    public static final String af;
    public static final long ag;
    public static final long ah;
    public static final long ai;
    public static final float aj;
    public static final float ak;
    public static final String al;
    public static final long am;
    public static final long an;
    public static final long ao;
    public static final float ap;
    public static final float aq;
    public static final String ar;
    public static final long as;
    public static final long at;
    public static final long au;
    public static final float av;
    public static final float aw;
    public static final String ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final float ba;
    public static final String bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final float bf;
    public static final float bg;
    public static final String bh;
    public static final long bi;
    public static final long bj;
    public static final long bk;
    public static final float bl;
    public static final float bm;
    public static final String bn;
    public static final long bo;
    public static final long bp;
    public static final long bq;
    public static final float br;
    public static final float bs;
    public static final String bt;
    public static final long bu;
    public static final long bv;
    public static final long bw;
    public static final float bx;
    public static final float by;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final float f;
    public static final float g;
    public static final String h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final float m;
    public static final float n;
    public static final String o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final float t;
    public static final float u;
    public static final String v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final float z;

    static {
        String str = dsm.a;
        a = dsm.a;
        b = chp.A(22.0d);
        c = chp.C(18);
        d = chp.A(1.6d);
        e = chp.A(0.4d);
        f = 599.0f;
        g = 100.0f;
        h = dsm.a;
        i = chp.A(18.0d);
        j = chp.C(15);
        k = chp.A(1.4d);
        l = chp.A(0.6d);
        m = 599.0f;
        n = 100.0f;
        o = dsm.a;
        p = chp.A(16.0d);
        q = chp.C(14);
        r = chp.A(1.4d);
        s = chp.A(0.6d);
        t = 560.0f;
        u = 100.0f;
        v = dsm.a;
        w = chp.A(12.0d);
        x = chp.C(10);
        y = chp.A(0.2d);
        z = 500.0f;
        A = 104.0f;
        B = dsm.a;
        C = chp.A(18.0d);
        D = chp.C(16);
        E = chp.A(0.4d);
        F = 450.0f;
        G = 110.0f;
        H = dsm.a;
        I = chp.A(16.0d);
        J = chp.C(14);
        K = chp.A(0.4d);
        L = 450.0f;
        M = 110.0f;
        N = dsm.a;
        O = chp.A(14.0d);
        P = chp.C(12);
        Q = chp.A(0.4d);
        R = 500.0f;
        S = 110.0f;
        T = dsm.a;
        U = chp.A(44.0d);
        V = chp.C(40);
        W = chp.A(0.2d);
        X = 500.0f;
        Y = 110.0f;
        Z = dsm.a;
        aa = chp.A(34.0d);
        ab = chp.C(30);
        ac = chp.A(0.2d);
        ad = 520.0f;
        ae = 110.0f;
        af = dsm.a;
        ag = chp.A(26.0d);
        ah = chp.C(24);
        ai = chp.A(0.2d);
        aj = 550.0f;
        ak = 110.0f;
        al = dsm.a;
        am = chp.A(22.0d);
        an = chp.C(20);
        ao = chp.A(0.4d);
        ap = 500.0f;
        aq = 110.0f;
        ar = dsm.a;
        as = chp.A(18.0d);
        at = chp.C(15);
        au = chp.A(0.4d);
        av = 500.0f;
        aw = 110.0f;
        ax = dsm.a;
        ay = chp.A(16.0d);
        az = chp.C(13);
        aA = chp.A(0.4d);
        aB = 500.0f;
        aC = 110.0f;
        aD = dsm.a;
        aE = chp.A(60.0d);
        aF = chp.C(60);
        aG = chp.A(0.0d);
        aH = 560.0f;
        aI = 110.0f;
        aJ = dsm.a;
        aK = chp.A(24.0d);
        aL = chp.C(24);
        aM = chp.A(0.0d);
        aN = 550.0f;
        aO = 100.0f;
        aP = dsm.a;
        aQ = chp.A(50.0d);
        aR = chp.C(50);
        aS = chp.A(0.0d);
        aT = 580.0f;
        aU = 110.0f;
        aV = dsm.a;
        aW = chp.A(40.0d);
        aX = chp.C(40);
        aY = chp.A(0.0d);
        aZ = 580.0f;
        ba = 100.0f;
        bb = dsm.a;
        bc = chp.A(30.0d);
        bd = chp.C(30);
        be = chp.A(0.0d);
        bf = 550.0f;
        bg = 100.0f;
        bh = dsm.a;
        bi = chp.A(20.0d);
        bj = chp.C(18);
        bk = chp.A(0.2d);
        bl = 500.0f;
        bm = 110.0f;
        bn = dsm.a;
        bo = chp.A(18.0d);
        bp = chp.C(16);
        bq = chp.A(0.4d);
        br = 550.0f;
        bs = 110.0f;
        bt = dsm.a;
        bu = chp.A(16.0d);
        bv = chp.C(14);
        bw = chp.A(0.4d);
        bx = 550.0f;
        by = 110.0f;
    }
}
