package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class dsn {
    public static final djw a;
    public static final djw b;
    public static final djw c;
    public static final cdo d;
    public static final cdo e;
    public static final cdo f;
    public static final cdo g;
    public static final cdo h;
    public static final cdo i;
    public static final cdo j;
    public static final cdo k;
    public static final cdo l;
    public static final cdo m;
    public static final cdo n;
    public static final cdo o;
    public static final cdo p;
    public static final cdo q;
    public static final cdo r;
    public static final cdo s;
    public static final cdo t;
    public static final cdo u;
    private static final djw v;

    static {
        djw djwVar = new djw(drw.a);
        v = djwVar;
        String str = dsl.a;
        String str2 = dsl.a;
        cfa.a(str2);
        cfp cfpVar = new cfp((int) dsl.f);
        cfo cfoVar = dso.a;
        cfd cfdVarN = bqs.n(byx.g(str2, cfpVar, dso.a, 4));
        cfp cfpVar2 = new cfp((int) dsl.f);
        a = djw.b(djwVar, dsl.c, cfdVarN, cfpVar2, dsl.e, dsl.d, dsl.b, 99);
        String str3 = dsl.h;
        cfa.a(str3);
        cfd cfdVarN2 = bqs.n(byx.g(str3, new cfp((int) dsl.m), dso.b, 4));
        cfp cfpVar3 = new cfp((int) dsl.m);
        b = djw.b(djwVar, dsl.j, cfdVarN2, cfpVar3, dsl.l, dsl.k, dsl.i, 99);
        String str4 = dsl.o;
        cfa.a(str4);
        cfd cfdVarN3 = bqs.n(byx.g(str4, new cfp((int) dsl.t), dso.c, 4));
        cfp cfpVar4 = new cfp((int) dsl.t);
        c = djw.b(djwVar, dsl.q, cfdVarN3, cfpVar4, dsl.s, dsl.r, dsl.p, 99);
        cdo cdoVar = drw.a;
        String str5 = dsl.v;
        cfa.a(str5);
        cfd cfdVarN4 = bqs.n(byx.g(str5, new cfp((int) dsl.z), dso.d, 4));
        cfp cfpVar5 = new cfp((int) dsl.z);
        d = cdo.w(cdoVar, dsl.x, cfpVar5, cfdVarN4, null, dsl.y, dsl.w, null, null, null, 16645977);
        cdo cdoVar2 = drw.a;
        String str6 = dsl.B;
        cfa.a(str6);
        cfd cfdVarN5 = bqs.n(byx.g(str6, new cfp((int) dsl.F), dso.e, 4));
        cfp cfpVar6 = new cfp((int) dsl.F);
        e = cdo.w(cdoVar2, dsl.D, cfpVar6, cfdVarN5, null, dsl.E, dsl.C, null, null, null, 16645977);
        cdo cdoVar3 = drw.a;
        String str7 = dsl.H;
        cfa.a(str7);
        cfd cfdVarN6 = bqs.n(byx.g(str7, new cfp((int) dsl.L), dso.f, 4));
        cfp cfpVar7 = new cfp((int) dsl.L);
        f = cdo.w(cdoVar3, dsl.J, cfpVar7, cfdVarN6, null, dsl.K, dsl.I, null, null, null, 16645977);
        cdo cdoVar4 = drw.a;
        String str8 = dsl.N;
        cfa.a(str8);
        cfd cfdVarN7 = bqs.n(byx.g(str8, new cfp((int) dsl.R), dso.g, 4));
        cfp cfpVar8 = new cfp((int) dsl.R);
        g = cdo.w(cdoVar4, dsl.P, cfpVar8, cfdVarN7, null, dsl.Q, dsl.O, null, null, null, 16645977);
        cdo cdoVar5 = drw.a;
        String str9 = dsl.T;
        cfa.a(str9);
        cfd cfdVarN8 = bqs.n(byx.g(str9, new cfp((int) dsl.X), dso.h, 4));
        cfp cfpVar9 = new cfp((int) dsl.X);
        h = cdo.w(cdoVar5, dsl.V, cfpVar9, cfdVarN8, null, dsl.W, dsl.U, null, null, null, 16645977);
        cdo cdoVar6 = drw.a;
        String str10 = dsl.Z;
        cfa.a(str10);
        cfd cfdVarN9 = bqs.n(byx.g(str10, new cfp((int) dsl.ad), dso.i, 4));
        cfp cfpVar10 = new cfp((int) dsl.ad);
        i = cdo.w(cdoVar6, dsl.ab, cfpVar10, cfdVarN9, null, dsl.ac, dsl.aa, null, null, null, 16645977);
        cdo cdoVar7 = drw.a;
        String str11 = dsl.af;
        cfa.a(str11);
        cfd cfdVarN10 = bqs.n(byx.g(str11, new cfp((int) dsl.aj), dso.j, 4));
        cfp cfpVar11 = new cfp((int) dsl.aj);
        j = cdo.w(cdoVar7, dsl.ah, cfpVar11, cfdVarN10, null, dsl.ai, dsl.ag, null, null, null, 16645977);
        cdo cdoVar8 = drw.a;
        String str12 = dsl.al;
        cfa.a(str12);
        cfd cfdVarN11 = bqs.n(byx.g(str12, new cfp((int) dsl.ap), dso.k, 4));
        cfp cfpVar12 = new cfp((int) dsl.ap);
        k = cdo.w(cdoVar8, dsl.an, cfpVar12, cfdVarN11, null, dsl.ao, dsl.am, null, null, null, 16645977);
        cdo cdoVar9 = drw.a;
        String str13 = dsl.ar;
        cfa.a(str13);
        cfd cfdVarN12 = bqs.n(byx.g(str13, new cfp((int) dsl.av), dso.l, 4));
        cfp cfpVar13 = new cfp((int) dsl.av);
        l = cdo.w(cdoVar9, dsl.at, cfpVar13, cfdVarN12, null, dsl.au, dsl.as, null, null, null, 16645977);
        cdo cdoVar10 = drw.a;
        String str14 = dsl.ax;
        cfa.a(str14);
        cfd cfdVarN13 = bqs.n(byx.g(str14, new cfp((int) dsl.aB), dso.m, 4));
        cfp cfpVar14 = new cfp((int) dsl.aB);
        m = cdo.w(cdoVar10, dsl.az, cfpVar14, cfdVarN13, null, dsl.aA, dsl.ay, null, null, null, 16645977);
        cdo cdoVar11 = drw.a;
        String str15 = dsl.aD;
        cfa.a(str15);
        cfd cfdVarN14 = bqs.n(byx.g(str15, new cfp((int) dsl.aH), dso.n, 4));
        cfp cfpVar15 = new cfp((int) dsl.aH);
        n = cdo.w(cdoVar11, dsl.aF, cfpVar15, cfdVarN14, null, dsl.aG, dsl.aE, null, null, null, 16645977);
        cdo cdoVar12 = drw.a;
        String str16 = dsl.aJ;
        cfa.a(str16);
        cfd cfdVarN15 = bqs.n(byx.g(str16, new cfp((int) dsl.aN), dso.o, 4));
        cfp cfpVar16 = new cfp((int) dsl.aN);
        o = cdo.w(cdoVar12, dsl.aL, cfpVar16, cfdVarN15, null, dsl.aM, dsl.aK, null, null, null, 16645977);
        cdo cdoVar13 = drw.a;
        String str17 = dsl.aP;
        cfa.a(str17);
        cfd cfdVarN16 = bqs.n(byx.g(str17, new cfp((int) dsl.aT), dso.p, 4));
        cfp cfpVar17 = new cfp((int) dsl.aT);
        p = cdo.w(cdoVar13, dsl.aR, cfpVar17, cfdVarN16, null, dsl.aS, dsl.aQ, null, null, null, 16645977);
        cdo cdoVar14 = drw.a;
        String str18 = dsl.aV;
        cfa.a(str18);
        cfd cfdVarN17 = bqs.n(byx.g(str18, new cfp((int) dsl.aZ), dso.q, 4));
        cfp cfpVar18 = new cfp((int) dsl.aZ);
        q = cdo.w(cdoVar14, dsl.aX, cfpVar18, cfdVarN17, null, dsl.aY, dsl.aW, null, null, null, 16645977);
        cdo cdoVar15 = drw.a;
        String str19 = dsl.bb;
        cfa.a(str19);
        cfd cfdVarN18 = bqs.n(byx.g(str19, new cfp((int) dsl.bf), dso.r, 4));
        cfp cfpVar19 = new cfp((int) dsl.bf);
        r = cdo.w(cdoVar15, dsl.bd, cfpVar19, cfdVarN18, null, dsl.be, dsl.bc, null, null, null, 16645977);
        cdo cdoVar16 = drw.a;
        String str20 = dsl.bh;
        cfa.a(str20);
        cfd cfdVarN19 = bqs.n(byx.g(str20, new cfp((int) dsl.bl), dso.s, 4));
        cfp cfpVar20 = new cfp((int) dsl.bl);
        s = cdo.w(cdoVar16, dsl.bj, cfpVar20, cfdVarN19, null, dsl.bk, dsl.bi, null, null, null, 16645977);
        cdo cdoVar17 = drw.a;
        String str21 = dsl.bn;
        cfa.a(str21);
        cfd cfdVarN20 = bqs.n(byx.g(str21, new cfp((int) dsl.br), dso.t, 4));
        cfp cfpVar21 = new cfp((int) dsl.br);
        t = cdo.w(cdoVar17, dsl.bp, cfpVar21, cfdVarN20, null, dsl.bq, dsl.bo, null, null, null, 16645977);
        cdo cdoVar18 = drw.a;
        String str22 = dsl.bt;
        cfa.a(str22);
        cfd cfdVarN21 = bqs.n(byx.g(str22, new cfp((int) dsl.bx), dso.u, 4));
        cfp cfpVar22 = new cfp((int) dsl.bx);
        u = cdo.w(cdoVar18, dsl.bv, cfpVar22, cfdVarN21, null, dsl.bw, dsl.bu, null, null, null, 16645977);
    }
}
