package defpackage;

import android.os.Handler;
import com.google.android.apps.camera.focusindicator.FocusIndicatorView;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class fbq {
    private final uem A;
    private final uem B;
    private final uem C;
    private final uem D;
    private final uem E;
    private final uem F;
    private final uem G;
    private final uem a;
    private final uem b;
    private final uem c;
    private final uem d;
    private final uem e;
    private final uem f;
    private final uem g;
    private final uem h;
    private final uem i;
    private final uem j;
    private final uem k;
    private final uem l;
    private final uem m;
    private final uem n;
    private final uem o;
    private final uem p;
    private final uem q;
    private final uem r;
    private final uem s;
    private final uem t;
    private final uem u;
    private final uem v;
    private final uem w;
    private final uem x;
    private final uem y;
    private final uem z;

    public fbq(uem uemVar, uem uemVar2, uem uemVar3, uem uemVar4, uem uemVar5, uem uemVar6, uem uemVar7, uem uemVar8, uem uemVar9, uem uemVar10, uem uemVar11, uem uemVar12, uem uemVar13, uem uemVar14, uem uemVar15, uem uemVar16, uem uemVar17, uem uemVar18, uem uemVar19, uem uemVar20, uem uemVar21, uem uemVar22, uem uemVar23, uem uemVar24, uem uemVar25, uem uemVar26, uem uemVar27, uem uemVar28, uem uemVar29, uem uemVar30, uem uemVar31, uem uemVar32, uem uemVar33) {
        uemVar.getClass();
        this.a = uemVar;
        this.b = uemVar2;
        uemVar3.getClass();
        this.c = uemVar3;
        this.d = uemVar4;
        this.e = uemVar5;
        this.f = uemVar6;
        uemVar7.getClass();
        this.g = uemVar7;
        uemVar8.getClass();
        this.h = uemVar8;
        uemVar9.getClass();
        this.i = uemVar9;
        this.j = uemVar10;
        uemVar11.getClass();
        this.k = uemVar11;
        this.l = uemVar12;
        uemVar13.getClass();
        this.m = uemVar13;
        uemVar14.getClass();
        this.n = uemVar14;
        uemVar15.getClass();
        this.o = uemVar15;
        uemVar16.getClass();
        this.p = uemVar16;
        uemVar17.getClass();
        this.q = uemVar17;
        uemVar18.getClass();
        this.r = uemVar18;
        uemVar19.getClass();
        this.s = uemVar19;
        uemVar20.getClass();
        this.t = uemVar20;
        uemVar21.getClass();
        this.u = uemVar21;
        uemVar22.getClass();
        this.v = uemVar22;
        uemVar23.getClass();
        this.w = uemVar23;
        uemVar24.getClass();
        this.x = uemVar24;
        uemVar25.getClass();
        this.y = uemVar25;
        uemVar26.getClass();
        this.z = uemVar26;
        uemVar27.getClass();
        this.A = uemVar27;
        uemVar28.getClass();
        this.B = uemVar28;
        uemVar29.getClass();
        this.C = uemVar29;
        uemVar30.getClass();
        this.D = uemVar30;
        uemVar31.getClass();
        this.E = uemVar31;
        uemVar32.getClass();
        this.F = uemVar32;
        uemVar33.getClass();
        this.G = uemVar33;
    }

    /* JADX WARN: Type inference failed for: r5v1, types: [fcb, java.lang.Object] */
    public final fbp a(fbl fblVar, pjo pjoVar, owf owfVar, owf owfVar2, boolean z, boolean z2, int i) {
        uem uemVar = this.b;
        Object objA = this.a.a();
        FocusIndicatorView focusIndicatorViewA = ((hod) uemVar).a();
        uem uemVar2 = this.d;
        ?? A = this.c.a();
        nqa nqaVar = (nqa) uemVar2.a();
        nqaVar.getClass();
        npy npyVar = (npy) this.e.a();
        npyVar.getClass();
        out outVar = (out) this.f.a();
        outVar.getClass();
        Set setA = ((tzz) this.g).a();
        setA.getClass();
        Set setA2 = ((tzz) this.h).a();
        setA2.getClass();
        ((nlf) this.i).a();
        ((mye) this.j.a()).getClass();
        msh mshVar = (msh) this.k.a();
        mshVar.getClass();
        mmk mmkVar = (mmk) this.l.a();
        mmkVar.getClass();
        hbj hbjVar = (hbj) this.m.a();
        hbjVar.getClass();
        hie hieVar = (hie) this.n.a();
        hieVar.getClass();
        rwc rwcVarB = ((lzr) this.o).b();
        gsj gsjVar = (gsj) this.p.a();
        gsjVar.getClass();
        Handler handler = (Handler) this.q.a();
        handler.getClass();
        syj syjVar = (syj) this.r.a();
        syjVar.getClass();
        rwc rwcVar = (rwc) this.s.a();
        rwcVar.getClass();
        rwc rwcVar2 = (rwc) this.t.a();
        rwcVar2.getClass();
        owf owfVarB = ((ihb) this.u).b();
        owf owfVarB2 = ((hkc) this.v).b();
        owf owfVar3 = (owf) this.w.a();
        owfVar3.getClass();
        owf owfVar4 = (owf) this.x.a();
        owfVar4.getClass();
        owf owfVar5 = (owf) this.y.a();
        owfVar5.getClass();
        owf owfVar6 = (owf) this.z.a();
        owfVar6.getClass();
        uem uemVar3 = this.A;
        uem uemVar4 = this.B;
        ocq ocqVarA = ((mmm) uemVar3).a();
        owq owqVar = (owq) uemVar4.a();
        owqVar.getClass();
        owq owqVar2 = (owq) this.C.a();
        owqVar2.getClass();
        jkh jkhVar = (jkh) this.D.a();
        jkhVar.getClass();
        rwc rwcVar3 = (rwc) this.E.a();
        rwcVar3.getClass();
        owf owfVar7 = (owf) this.F.a();
        owfVar7.getClass();
        mwq mwqVar = (mwq) this.G.a();
        mwqVar.getClass();
        pjoVar.getClass();
        owfVar2.getClass();
        return new fbp((gtm) objA, focusIndicatorViewA, A, nqaVar, npyVar, outVar, setA, setA2, mshVar, mmkVar, hbjVar, hieVar, rwcVarB, gsjVar, handler, syjVar, rwcVar, rwcVar2, owfVarB, owfVarB2, owfVar3, owfVar4, owfVar5, owfVar6, ocqVarA, owqVar, owqVar2, jkhVar, rwcVar3, owfVar7, mwqVar, fblVar, pjoVar, owfVar, owfVar2, z, z2, i);
    }
}
