package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class fxz {
    public final uem A;
    public final uem B;
    public final uem C;
    public final uem D;
    public final uem E;
    public final uem F;
    public final uem G;
    public final uem H;
    public final uem I;
    public final uem J;
    public final uem a;
    public final uem b;
    public final uem c;
    public final uem d;
    public final uem e;
    public final uem f;
    public final uem g;
    public final uem h;
    public final uem i;
    public final uem j;
    public final uem k;
    public final uem l;
    public final uem m;
    public final uem n;
    public final uem o;
    public final uem p;
    public final uem q;
    public final uem r;
    public final uem s;
    public final uem t;
    public final uem u;
    public final uem v;
    public final uem w;
    public final uem x;
    public final uem y;
    public final uem z;

    public fxz(uem uemVar, uem uemVar2, uem uemVar3, uem uemVar4, uem uemVar5, uem uemVar6, uem uemVar7, uem uemVar8, uem uemVar9, uem uemVar10, uem uemVar11, uem uemVar12, uem uemVar13, uem uemVar14, uem uemVar15, uem uemVar16, uem uemVar17, uem uemVar18, uem uemVar19, uem uemVar20, uem uemVar21, uem uemVar22, uem uemVar23, uem uemVar24, uem uemVar25, uem uemVar26, uem uemVar27, uem uemVar28, uem uemVar29, uem uemVar30, uem uemVar31, uem uemVar32, uem uemVar33, uem uemVar34, uem uemVar35, uem uemVar36) {
        uemVar.getClass();
        this.a = uemVar;
        uemVar2.getClass();
        this.b = uemVar2;
        uemVar3.getClass();
        this.c = uemVar3;
        uemVar4.getClass();
        this.d = uemVar4;
        uemVar5.getClass();
        this.e = uemVar5;
        uemVar6.getClass();
        this.f = uemVar6;
        this.g = uemVar7;
        uemVar8.getClass();
        this.h = uemVar8;
        uemVar9.getClass();
        this.i = uemVar9;
        uemVar10.getClass();
        this.j = uemVar10;
        uemVar11.getClass();
        this.k = uemVar11;
        uemVar12.getClass();
        this.l = uemVar12;
        uemVar13.getClass();
        this.m = uemVar13;
        uemVar14.getClass();
        this.n = uemVar14;
        this.o = uemVar15;
        uemVar16.getClass();
        this.p = uemVar16;
        uemVar17.getClass();
        this.q = uemVar17;
        uemVar18.getClass();
        this.r = uemVar18;
        uemVar19.getClass();
        this.s = uemVar19;
        uemVar20.getClass();
        this.t = uemVar20;
        uemVar21.getClass();
        this.u = uemVar21;
        uemVar22.getClass();
        this.v = uemVar22;
        uemVar23.getClass();
        this.w = uemVar23;
        this.x = uemVar24;
        uemVar25.getClass();
        this.y = uemVar25;
        uemVar26.getClass();
        this.z = uemVar26;
        uemVar27.getClass();
        this.A = uemVar27;
        uemVar28.getClass();
        this.B = uemVar28;
        uemVar29.getClass();
        this.C = uemVar29;
        uemVar30.getClass();
        this.D = uemVar30;
        uemVar31.getClass();
        this.E = uemVar31;
        uemVar32.getClass();
        this.F = uemVar32;
        uemVar33.getClass();
        this.G = uemVar33;
        uemVar34.getClass();
        this.H = uemVar34;
        uemVar35.getClass();
        this.I = uemVar35;
        uemVar36.getClass();
        this.J = uemVar36;
    }
}
