package defpackage;

import java.util.List;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gxs extends gxl {
    private final List a;

    public gxs(hbj hbjVar) {
        ugl uglVar = new ugl((byte[]) null);
        gyd gydVar = gyd.a;
        tpc tpcVarM = gydVar.m();
        tpcVarM.getClass();
        gyb gybVar = gyb.FACING_BACK;
        gsn.w(gybVar, tpcVarM);
        gsn.t(tpcVarM);
        Float fValueOf = Float.valueOf(0.507838f);
        Float fValueOf2 = Float.valueOf(1.0f);
        Float fValueOf3 = Float.valueOf(2.0f);
        Float fValueOf4 = Float.valueOf(5.0f);
        sbp sbpVarO = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf4);
        sbpVarO.getClass();
        tpcVarM.v(sbpVarO);
        gsn.s(tpcVarM);
        Float fValueOf5 = Float.valueOf(10.0f);
        sbp sbpVarQ = sbp.q(fValueOf, fValueOf2, fValueOf3, fValueOf4, fValueOf5, Float.valueOf(30.0f));
        sbpVarQ.getClass();
        tpcVarM.u(sbpVarQ);
        tpc tpcVarM2 = gydVar.m();
        tpcVarM2.getClass();
        gyb gybVar2 = gyb.FACING_FRONT;
        gsn.w(gybVar2, tpcVarM2);
        gsn.t(tpcVarM2);
        Float fValueOf6 = Float.valueOf(1.4f);
        sbp sbpVarM = sbp.m(fValueOf2, fValueOf6);
        sbpVarM.getClass();
        tpcVarM2.v(sbpVarM);
        gsn.s(tpcVarM2);
        Float fValueOf7 = Float.valueOf(4.0f);
        sbp sbpVarN = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN.getClass();
        tpcVarM2.u(sbpVarN);
        hak.c(hbjVar);
        tpc tpcVarM3 = gydVar.m();
        tpcVarM3.getClass();
        gsn.w(gybVar, tpcVarM3);
        ssc sscVar = ssc.PORTRAIT;
        gsn.u(sscVar, tpcVarM3);
        gsn.v(2.0f, tpcVarM3);
        gsn.t(tpcVarM3);
        Float fValueOf8 = Float.valueOf(1.5172f);
        sbp sbpVarM2 = sbp.m(fValueOf8, fValueOf3);
        sbpVarM2.getClass();
        tpcVarM3.v(sbpVarM2);
        gsn.s(tpcVarM3);
        sbp sbpVarN2 = sbp.n(fValueOf8, fValueOf3, Float.valueOf(3.0f));
        sbpVarN2.getClass();
        tpcVarM3.u(sbpVarN2);
        tpc tpcVarM4 = gydVar.m();
        tpcVarM4.getClass();
        gsn.w(gybVar, tpcVarM4);
        gsn.u(ssc.VIDEO_CAPTURE, tpcVarM4);
        gsn.t(tpcVarM4);
        sbp sbpVarO2 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf4);
        sbpVarO2.getClass();
        tpcVarM4.v(sbpVarO2);
        gsn.s(tpcVarM4);
        Float fValueOf9 = Float.valueOf(20.0f);
        sbp sbpVarQ2 = sbp.q(fValueOf, fValueOf2, fValueOf3, fValueOf4, fValueOf5, fValueOf9);
        sbpVarQ2.getClass();
        tpcVarM4.u(sbpVarQ2);
        tpc tpcVarM5 = gydVar.m();
        tpcVarM5.getClass();
        gsn.w(gybVar, tpcVarM5);
        gsn.u(ssc.VEGA, tpcVarM5);
        gsn.t(tpcVarM5);
        sbp sbpVarN3 = sbp.n(fValueOf2, fValueOf3, fValueOf4);
        sbpVarN3.getClass();
        tpcVarM5.v(sbpVarN3);
        gsn.s(tpcVarM5);
        sbp sbpVarP = sbp.p(fValueOf2, fValueOf3, fValueOf4, fValueOf5, fValueOf9);
        sbpVarP.getClass();
        tpcVarM5.u(sbpVarP);
        tpc tpcVarM6 = gydVar.m();
        tpcVarM6.getClass();
        gsn.w(gybVar, tpcVarM6);
        gsn.u(ssc.CINEMATIC_PAN, tpcVarM6);
        gsn.t(tpcVarM6);
        sbp sbpVarO3 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf4);
        sbpVarO3.getClass();
        tpcVarM6.v(sbpVarO3);
        gsn.s(tpcVarM6);
        sbp sbpVarQ3 = sbp.q(fValueOf, fValueOf2, fValueOf3, fValueOf4, fValueOf5, fValueOf9);
        sbpVarQ3.getClass();
        tpcVarM6.u(sbpVarQ3);
        tpc tpcVarM7 = gydVar.m();
        tpcVarM7.getClass();
        gsn.w(gybVar, tpcVarM7);
        gsn.u(ssc.TIMELAPSE, tpcVarM7);
        gsn.t(tpcVarM7);
        sbp sbpVarO4 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf4);
        sbpVarO4.getClass();
        tpcVarM7.v(sbpVarO4);
        gsn.s(tpcVarM7);
        sbp sbpVarQ4 = sbp.q(fValueOf, fValueOf2, fValueOf3, fValueOf4, fValueOf5, fValueOf9);
        sbpVarQ4.getClass();
        tpcVarM7.u(sbpVarQ4);
        tpc tpcVarM8 = gydVar.m();
        tpcVarM8.getClass();
        gsn.w(gybVar2, tpcVarM8);
        gsn.u(ssc.PHOTO_CAPTURE, tpcVarM8);
        gsn.v(1.4f, tpcVarM8);
        gsn.x(1.4f, tpcVarM8);
        gsn.t(tpcVarM8);
        sbp sbpVarM3 = sbp.m(fValueOf2, fValueOf6);
        sbpVarM3.getClass();
        tpcVarM8.v(sbpVarM3);
        gsn.s(tpcVarM8);
        sbp sbpVarN4 = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN4.getClass();
        tpcVarM8.u(sbpVarN4);
        tpc tpcVarM9 = gydVar.m();
        tpcVarM9.getClass();
        gsn.w(gybVar2, tpcVarM9);
        gsn.u(ssc.NIGHT_SIGHT, tpcVarM9);
        gsn.v(1.4f, tpcVarM9);
        gsn.x(1.4f, tpcVarM9);
        gsn.t(tpcVarM9);
        sbp sbpVarM4 = sbp.m(fValueOf2, fValueOf6);
        sbpVarM4.getClass();
        tpcVarM9.v(sbpVarM4);
        gsn.s(tpcVarM9);
        sbp sbpVarN5 = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN5.getClass();
        tpcVarM9.u(sbpVarN5);
        tpc tpcVarM10 = gydVar.m();
        tpcVarM10.getClass();
        gsn.w(gybVar2, tpcVarM10);
        gsn.u(sscVar, tpcVarM10);
        gsn.v(1.4f, tpcVarM10);
        gsn.x(1.4f, tpcVarM10);
        gsn.t(tpcVarM10);
        sbp sbpVarM5 = sbp.m(fValueOf2, fValueOf6);
        sbpVarM5.getClass();
        tpcVarM10.v(sbpVarM5);
        gsn.s(tpcVarM10);
        sbp sbpVarN6 = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN6.getClass();
        tpcVarM10.u(sbpVarN6);
        tpc tpcVarM11 = gydVar.m();
        tpcVarM11.getClass();
        gsn.w(gybVar2, tpcVarM11);
        gsn.u(ssc.MOTION_LANDSCAPE, tpcVarM11);
        gsn.v(1.4f, tpcVarM11);
        gsn.x(1.4f, tpcVarM11);
        gsn.t(tpcVarM11);
        sbp sbpVarM6 = sbp.m(fValueOf2, fValueOf6);
        sbpVarM6.getClass();
        tpcVarM11.v(sbpVarM6);
        gsn.s(tpcVarM11);
        sbp sbpVarN7 = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN7.getClass();
        tpcVarM11.u(sbpVarN7);
        tpc tpcVarM12 = gydVar.m();
        tpcVarM12.getClass();
        gsn.w(gybVar2, tpcVarM12);
        gsn.u(ssc.MOTION_ACTION_PAN, tpcVarM12);
        gsn.v(1.4f, tpcVarM12);
        gsn.x(1.4f, tpcVarM12);
        gsn.t(tpcVarM12);
        sbp sbpVarM7 = sbp.m(fValueOf2, fValueOf6);
        sbpVarM7.getClass();
        tpcVarM12.v(sbpVarM7);
        gsn.s(tpcVarM12);
        sbp sbpVarN8 = sbp.n(fValueOf2, fValueOf6, fValueOf7);
        sbpVarN8.getClass();
        tpcVarM12.u(sbpVarN8);
        uglVar.addAll(rnt.ae(new gyd[]{gsn.q(tpcVarM), gsn.q(tpcVarM2), gsn.q(tpcVarM3), gsn.q(tpcVarM4), gsn.q(tpcVarM5), gsn.q(tpcVarM6), gsn.q(tpcVarM7), gsn.q(tpcVarM8), gsn.q(tpcVarM9), gsn.q(tpcVarM10), gsn.q(tpcVarM11), gsn.q(tpcVarM12)}));
        gzi gziVar = gzp.a;
        this.a = ske.bi(uglVar);
    }

    @Override // defpackage.gxl
    public final List a() {
        return this.a;
    }
}
