package defpackage;

import java.util.List;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class gya extends gxl {
    private final List a;

    public gya() {
        ugl uglVar = new ugl((byte[]) null);
        gyd gydVar = gyd.a;
        tpc tpcVarM = gydVar.m();
        tpcVarM.getClass();
        gyb gybVar = gyb.FACING_BACK;
        gsn.w(gybVar, tpcVarM);
        gsn.t(tpcVarM);
        Float fValueOf = Float.valueOf(0.50783783f);
        Float fValueOf2 = Float.valueOf(1.0f);
        Float fValueOf3 = Float.valueOf(2.0f);
        sbp sbpVarN = sbp.n(fValueOf, fValueOf2, fValueOf3);
        sbpVarN.getClass();
        tpcVarM.v(sbpVarN);
        gsn.s(tpcVarM);
        sbp sbpVarO = sbp.o(fValueOf, fValueOf2, fValueOf3, Float.valueOf(8.0f));
        sbpVarO.getClass();
        tpcVarM.u(sbpVarO);
        tpc tpcVarM2 = gydVar.m();
        tpcVarM2.getClass();
        gyb gybVar2 = gyb.FACING_FRONT;
        gsn.w(gybVar2, tpcVarM2);
        gsn.t(tpcVarM2);
        Float fValueOf4 = Float.valueOf(1.4f);
        sbp sbpVarM = sbp.m(fValueOf2, fValueOf4);
        sbpVarM.getClass();
        tpcVarM2.v(sbpVarM);
        gsn.s(tpcVarM2);
        Float fValueOf5 = Float.valueOf(4.0f);
        sbp sbpVarN2 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN2.getClass();
        tpcVarM2.u(sbpVarN2);
        tpc tpcVarM3 = gydVar.m();
        tpcVarM3.getClass();
        gsn.w(gybVar, tpcVarM3);
        ssc sscVar = ssc.PORTRAIT;
        gsn.u(sscVar, tpcVarM3);
        gsn.v(2.0f, tpcVarM3);
        gsn.t(tpcVarM3);
        Float fValueOf6 = Float.valueOf(1.5172f);
        sbp sbpVarM2 = sbp.m(fValueOf6, fValueOf3);
        sbpVarM2.getClass();
        tpcVarM3.v(sbpVarM2);
        gsn.s(tpcVarM3);
        sbp sbpVarN3 = sbp.n(fValueOf6, fValueOf3, Float.valueOf(3.0f));
        sbpVarN3.getClass();
        tpcVarM3.u(sbpVarN3);
        tpc tpcVarM4 = gydVar.m();
        tpcVarM4.getClass();
        gsn.w(gybVar, tpcVarM4);
        gsn.u(ssc.VIDEO_CAPTURE, tpcVarM4);
        gsn.t(tpcVarM4);
        sbp sbpVarN4 = sbp.n(fValueOf, fValueOf2, fValueOf3);
        sbpVarN4.getClass();
        tpcVarM4.v(sbpVarN4);
        gsn.s(tpcVarM4);
        Float fValueOf7 = Float.valueOf(7.0f);
        sbp sbpVarO2 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf7);
        sbpVarO2.getClass();
        tpcVarM4.u(sbpVarO2);
        tpc tpcVarM5 = gydVar.m();
        tpcVarM5.getClass();
        gsn.w(gybVar, tpcVarM5);
        gsn.u(ssc.VEGA, tpcVarM5);
        gsn.t(tpcVarM5);
        sbp sbpVarM3 = sbp.m(fValueOf2, fValueOf3);
        sbpVarM3.getClass();
        tpcVarM5.v(sbpVarM3);
        gsn.s(tpcVarM5);
        sbp sbpVarN5 = sbp.n(fValueOf2, fValueOf3, fValueOf7);
        sbpVarN5.getClass();
        tpcVarM5.u(sbpVarN5);
        tpc tpcVarM6 = gydVar.m();
        tpcVarM6.getClass();
        gsn.w(gybVar, tpcVarM6);
        gsn.u(ssc.CINEMATIC_PAN, tpcVarM6);
        gsn.t(tpcVarM6);
        sbp sbpVarN6 = sbp.n(fValueOf, fValueOf2, fValueOf3);
        sbpVarN6.getClass();
        tpcVarM6.v(sbpVarN6);
        gsn.s(tpcVarM6);
        sbp sbpVarO3 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf7);
        sbpVarO3.getClass();
        tpcVarM6.u(sbpVarO3);
        tpc tpcVarM7 = gydVar.m();
        tpcVarM7.getClass();
        gsn.w(gybVar, tpcVarM7);
        gsn.u(ssc.TIMELAPSE, tpcVarM7);
        gsn.t(tpcVarM7);
        sbp sbpVarN7 = sbp.n(fValueOf, fValueOf2, fValueOf3);
        sbpVarN7.getClass();
        tpcVarM7.v(sbpVarN7);
        gsn.s(tpcVarM7);
        sbp sbpVarO4 = sbp.o(fValueOf, fValueOf2, fValueOf3, fValueOf7);
        sbpVarO4.getClass();
        tpcVarM7.u(sbpVarO4);
        tpc tpcVarM8 = gydVar.m();
        tpcVarM8.getClass();
        gsn.w(gybVar2, tpcVarM8);
        gsn.u(ssc.PHOTO_CAPTURE, tpcVarM8);
        gsn.v(1.4f, tpcVarM8);
        gsn.x(1.4f, tpcVarM8);
        gsn.t(tpcVarM8);
        sbp sbpVarM4 = sbp.m(fValueOf2, fValueOf4);
        sbpVarM4.getClass();
        tpcVarM8.v(sbpVarM4);
        gsn.s(tpcVarM8);
        sbp sbpVarN8 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN8.getClass();
        tpcVarM8.u(sbpVarN8);
        tpc tpcVarM9 = gydVar.m();
        tpcVarM9.getClass();
        gsn.w(gybVar2, tpcVarM9);
        gsn.u(ssc.NIGHT_SIGHT, tpcVarM9);
        gsn.v(1.4f, tpcVarM9);
        gsn.x(1.4f, tpcVarM9);
        gsn.t(tpcVarM9);
        sbp sbpVarM5 = sbp.m(fValueOf2, fValueOf4);
        sbpVarM5.getClass();
        tpcVarM9.v(sbpVarM5);
        gsn.s(tpcVarM9);
        sbp sbpVarN9 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN9.getClass();
        tpcVarM9.u(sbpVarN9);
        tpc tpcVarM10 = gydVar.m();
        tpcVarM10.getClass();
        gsn.w(gybVar2, tpcVarM10);
        gsn.u(sscVar, tpcVarM10);
        gsn.v(1.4f, tpcVarM10);
        gsn.x(1.4f, tpcVarM10);
        gsn.t(tpcVarM10);
        sbp sbpVarM6 = sbp.m(fValueOf2, fValueOf4);
        sbpVarM6.getClass();
        tpcVarM10.v(sbpVarM6);
        gsn.s(tpcVarM10);
        sbp sbpVarN10 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN10.getClass();
        tpcVarM10.u(sbpVarN10);
        tpc tpcVarM11 = gydVar.m();
        tpcVarM11.getClass();
        gsn.w(gybVar2, tpcVarM11);
        gsn.u(ssc.MOTION_LANDSCAPE, tpcVarM11);
        gsn.v(1.4f, tpcVarM11);
        gsn.x(1.4f, tpcVarM11);
        gsn.t(tpcVarM11);
        sbp sbpVarM7 = sbp.m(fValueOf2, fValueOf4);
        sbpVarM7.getClass();
        tpcVarM11.v(sbpVarM7);
        gsn.s(tpcVarM11);
        sbp sbpVarN11 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN11.getClass();
        tpcVarM11.u(sbpVarN11);
        tpc tpcVarM12 = gydVar.m();
        tpcVarM12.getClass();
        gsn.w(gybVar2, tpcVarM12);
        gsn.u(ssc.MOTION_ACTION_PAN, tpcVarM12);
        gsn.v(1.4f, tpcVarM12);
        gsn.x(1.4f, tpcVarM12);
        gsn.t(tpcVarM12);
        sbp sbpVarM8 = sbp.m(fValueOf2, fValueOf4);
        sbpVarM8.getClass();
        tpcVarM12.v(sbpVarM8);
        gsn.s(tpcVarM12);
        sbp sbpVarN12 = sbp.n(fValueOf2, fValueOf4, fValueOf5);
        sbpVarN12.getClass();
        tpcVarM12.u(sbpVarN12);
        uglVar.addAll(rnt.ae(new gyd[]{gsn.q(tpcVarM), gsn.q(tpcVarM2), gsn.q(tpcVarM3), gsn.q(tpcVarM4), gsn.q(tpcVarM5), gsn.q(tpcVarM6), gsn.q(tpcVarM7), gsn.q(tpcVarM8), gsn.q(tpcVarM9), gsn.q(tpcVarM10), gsn.q(tpcVarM11), gsn.q(tpcVarM12)}));
        gzi gziVar = gzp.a;
        this.a = ske.bi(uglVar);
    }

    @Override // defpackage.gxl
    public final List a() {
        return this.a;
    }
}
