package defpackage;

import com.google.android.apps.camera.jni.facebeautification.GFS.CZAHo;
import com.google.googlex.gcam.creativecamera.portraitmode.axeo.pAAtrB;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gyi {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzi a;
    public static final gzi b;
    public static final Float c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.cottage_enabled";
        h = gzhVar.g();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.cottage_ois_enabled";
        i = gzhVar2.g();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.cottage_depth_enabled";
        gzhVar3.m();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.cottage_render_pc";
        gzhVar4.m();
        gzh gzhVar5 = new gzh();
        gzhVar5.c(new gyn(1));
        gzhVar5.b = "camera.cottage_anchor_update_reliability_check";
        gzhVar5.o();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.cottage_render_planes";
        gzhVar6.m();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.cottage_enable_gain";
        gzhVar7.m();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.cottage_record_arcore";
        gzhVar8.o();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.cottage_capture_data";
        gzhVar9.o();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.cottage_step_by_step_edu";
        j = gzhVar10.g();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.cottage_first_time_edu";
        k = gzhVar11.g();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.cottage_capture_preview";
        l = gzhVar12.g();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.cottage_use_tpu";
        m = gzhVar13.g();
        gzh gzhVar14 = new gzh();
        gzhVar14.d("Cottage", false);
        gzhVar14.b = "arcore_version_major";
        a = gzhVar14.a();
        gzh gzhVar15 = new gzh();
        gzhVar15.d("Cottage", false);
        gzhVar15.b = "arcore_version_minor";
        b = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.cottage_base_anchor";
        gzhVar16.o();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.cottage_async_segmentation";
        n = gzhVar17.g();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.cottage_suggestion";
        o = gzhVar18.g();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.cottage_suggestion_impression_reset";
        gzhVar19.e();
        c = Float.valueOf(10.0f);
        gzh gzhVar20 = new gzh();
        gzhVar20.b = CZAHo.JDcnFR;
        p = gzhVar20.h();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.cottage_arcore_reliability_check";
        q = gzhVar21.g();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.cottage_biased_guidance";
        gzhVar22.o();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.cottage_multiple_results";
        gzhVar23.o();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.cottage_arcore_bringup";
        gzhVar24.o();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.cottage_unreliable_delay_ms";
        d = gzhVar25.a();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.cottage_unreliable_persistent_delay_ms";
        e = gzhVar26.a();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.cottage_capture_guidance_timeout_ms";
        f = gzhVar27.a();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.cottage_distance_restriction_meters";
        r = gzhVar28.h();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.cottage_capture_availability_timeout_ms";
        g = gzhVar29.a();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.cottage_direction_debounce_scale";
        s = gzhVar30.h();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.cottage_direction_debounce_scale";
        t = gzhVar31.h();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.cottage_saturn_enabled";
        u = gzhVar32.i();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.cottage_bypass_arcore";
        gzhVar33.m();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.cottage_face_detector_model";
        v = gzhVar34.j();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.cottage_portrait_matting_model";
        w = gzhVar35.j();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.cottage_fg_color_est_model";
        x = gzhVar36.j();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.cottage_person_segmenter_model";
        y = gzhVar37.j();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.cottage_foreground_segmenter_model";
        z = gzhVar38.j();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.cottage_raid_matting_model";
        A = gzhVar39.j();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.cottage_shadow_segmenter_model";
        B = gzhVar40.j();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.cottage_attached_objects_segmenter_model";
        C = gzhVar41.j();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.cottage_hoi_classifier_model";
        D = gzhVar42.j();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.cottage_attached_objects_detector_model";
        E = gzhVar43.j();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.cottage_positional_score_scale";
        F = gzhVar44.h();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.cottage_rotational_score_scale";
        G = gzhVar45.h();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.cottage_bypass_too_many_people";
        gzhVar46.o();
    }

    public static void a(hbj hbjVar) {
        hbjVar.j(h, false);
        hbjVar.j(i, true);
        hbjVar.j(j, true);
        hbjVar.j(k, true);
        hbjVar.j(l, true);
        hbjVar.j(m, true);
        hbjVar.d(a, 1);
        hbjVar.d(b, 44);
        hbjVar.j(n, true);
        hbjVar.j(o, true);
        hbjVar.k(p, c);
        hbjVar.j(q, true);
        hbjVar.d(d, 1500);
        hbjVar.d(e, 15000);
        hbjVar.d(f, 20000);
        hbjVar.k(r, Float.valueOf(7.0f));
        hbjVar.d(g, Integer.MAX_VALUE);
        hbjVar.k(s, Float.valueOf(0.9f));
        hbjVar.k(t, Float.valueOf(0.5f));
        hbjVar.l(u, true);
        hbjVar.m(v, "fssd_custom-op_tpu_23.tflite.uncompressed");
        hbjVar.m(w, "27f6d09d5d944709b6e46c0ed9524c08/27f6d09d5d944709b6e46c0ed9524c08.uncompressed");
        hbjVar.m(x, "5098e597cb4a4dd8a0827a2e7b3e2057/5098e597cb4a4dd8a0827a2e7b3e2057.uncompressed");
        hbjVar.m(y, "raid_person_segmenter_from_face_detection_with_occlusions-graph-custom_op_tpu_23.tflite.uncompressed");
        hbjVar.m(A, pAAtrB.jPKXS);
        hbjVar.m(z, "raid_foreground_mosaic_512_qat_tpu_23.tflite.uncompressed");
        hbjVar.m(B, "shadow_segmenter_finetuned_ptq_Dec2024_batch1-graph-custom_op_p23.tflite.uncompressed");
        hbjVar.m(C, "raid_instance_segmenter_with_objects_no_people-graph-custom_op_tpu_p23.tflite.uncompressed");
        hbjVar.m(D, "hoi_classifier_256x256_rgb_and_boxes-graph-custom_op_tpu_p23.tflite.uncompressed");
        hbjVar.m(E, "mobile_raid_v26_640_qat_u8_attached_objects_trained_no_post-graph-custom_op_tpu_p23.tflite.uncompressed");
        hbjVar.k(F, Float.valueOf(8.0f));
        hbjVar.k(G, Float.valueOf(4.0f));
    }
}
