package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gym {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final gzg W;
    public static final gzg X;
    public static final gzg Y;
    public static final gzg Z;
    public static final gzi a;
    public static final gzg aa;
    public static final gzg ab;
    public static final gzg ac;
    public static final gzg ad;
    public static final gzg ae;
    public static final gzg af;
    public static final gzg ag;
    public static final gzg ah;
    public static final gzg ai;
    public static final gzg aj;
    public static final gzg ak;
    public static final gzg al;
    public static final gzg am;
    public static final gzg an;
    public static final gzg ao;
    public static final gzg ap;
    public static final gzg aq;
    public static final gzg ar;
    public static final gzg as;
    public static final gzg at;
    public static final gzg au;
    public static final gzg av;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzi k;
    public static final gzi l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    /* JADX WARN: Type inference failed for: r0v83, types: [java.lang.Object, java.util.function.Supplier] */
    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camcorder.bitrate";
        a = gzhVar.a();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camcorder.capture_rate";
        gzhVar2.e = scn.L(0, 24, 30, 60, 120, 240, new Integer[0]);
        b = gzhVar2.a();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "detect_face_on_front_camera";
        m = gzhVar3.i();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "detect_face_on_non_front_camera";
        n = gzhVar4.i();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camcorder.fragmented_muxer";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camcorder.h265";
        gzhVar6.e();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "enable_hevc_setting";
        o = gzhVar7.i();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camcorder.jellybean";
        gzhVar8.e();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camcorder.jellybean_setting";
        gzhVar9.o();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camcorder.codec_sm";
        p = gzhVar10.i();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camcorder.codec_video";
        q = gzhVar11.i();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camcorder.no_audio";
        gzhVar12.e();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camcorder.ois";
        r = gzhVar13.g();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camcorder.stereo";
        s = gzhVar14.g();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camcorder.sf_share";
        gzhVar15.e();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camcorder.trk_yuv";
        t = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camcorder.viewfinder_effect";
        gzhVar17.o();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camcorder.vfe_limit_30fps";
        gzhVar18.e();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "max_1080p_video_duration_seconds";
        c = gzhVar19.a();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "max_2160p_video_duration_seconds";
        d = gzhVar20.a();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "max_hfr_video_duration_seconds";
        e = gzhVar21.a();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "UNLOCK_AF_AE_WITH_SCENE_CHANGE_FOR_FRONT_CAM";
        u = gzhVar22.i();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camcorder.vidqual_front";
        gzhVar23.e = scn.L(144, 240, 288, 480, 720, 1080, 2160);
        f = gzhVar23.a();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camcorder.vidqual_back";
        gzhVar24.e = scn.L(144, 240, 288, 480, 720, 1080, 2160, 2268, 4320);
        g = gzhVar24.a();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "zoom_override_enabled";
        v = gzhVar25.i();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "zoom_min_override_enabled";
        w = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camcorder.max_zoom";
        x = gzhVar27.h();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camcorder.max_zoom_30fps";
        y = gzhVar28.h();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camcorder.max_zoom_default";
        z = gzhVar29.h();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camcorder.max_zoom_hfr";
        A = gzhVar30.h();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camcorder.24fps";
        B = gzhVar31.i();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camcorder.4k60fps";
        C = gzhVar32.i();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camcorder.stokes_dyn";
        D = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camcorder.fb_preview_4k60fps";
        E = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camcorder.stokes_thr";
        F = gzhVar35.i();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camcorder.stokes_mra";
        G = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camcorder.stokes_asm";
        H = gzhVar37.i();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camcorder.stokes_uw";
        I = gzhVar38.i();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camcorder.washington_md";
        gzhVar39.e = scn.K(0, 1, 2, 3, 4);
        h = gzhVar39.a();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camcorder.slowmo_snapshot";
        J = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camcorder.screenshot_snapshot";
        gzhVar41.o();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camcorder.washington";
        K = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camcorder.ext_mic_state";
        gzhVar43.e = scn.J(0, 1, 2, 3);
        i = gzhVar43.a();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camcorder.use_gcamux";
        L = gzhVar44.i();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camcorder.noop_muxer";
        gzhVar45.e();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camcorder.no_recorder";
        M = gzhVar46.i();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camcorder.video_file_max_size";
        Object obj = gzhVar47.b;
        String str = (String) obj;
        N = new gzg(str, (String) gzhVar47.c, gzhVar47.a, gzhVar47.d);
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camcorder.3a_metadata";
        O = gzhVar48.i();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camcorder.fix_crtime";
        P = gzhVar49.i();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camcorder.fb_preview";
        Q = gzhVar50.i();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camcorder.washington_l";
        R = gzhVar51.i();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camcorder.washington_a";
        S = gzhVar52.i();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camcorder.washington_a_multi";
        gzhVar53.o();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camcorder.washington_c";
        T = gzhVar54.i();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camcorder.washington_c_front";
        U = gzhVar55.i();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "camcorder.sync_fps";
        V = gzhVar56.i();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "camcorder.log_3a";
        W = gzhVar57.i();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "camcorder.auto_stop_on_frame_drop";
        X = gzhVar58.f();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "camcorder.camera_perfetto_trace_frame_drops";
        gzhVar59.o();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camcorder_perfetto_trigger_frame_drops";
        gzhVar60.d("Video", false);
        j = gzhVar60.a();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camcorder.ir_fs";
        gzhVar61.e();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camcorder.front_variable_fps_range";
        Y = gzhVar62.i();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = "camcorder.ts";
        Z = gzhVar63.i();
        gzh gzhVar64 = new gzh();
        gzhVar64.b = "camcorder.ts60";
        gzhVar64.e();
        gzh gzhVar65 = new gzh();
        gzhVar65.b = "camcorder.ap";
        aa = gzhVar65.i();
        gzh gzhVar66 = new gzh();
        gzhVar66.b = "camcorder.ap_pipeline";
        ab = gzhVar66.i();
        gzh gzhVar67 = new gzh();
        gzhVar67.b = "camcorder.audio_zoom";
        ac = gzhVar67.i();
        gzh gzhVar68 = new gzh();
        gzhVar68.b = "camcorder.use_bt709";
        ad = gzhVar68.i();
        gzh gzhVar69 = new gzh();
        gzhVar69.b = "camcorder.add_silent_audio";
        ae = gzhVar69.i();
        gzh gzhVar70 = new gzh();
        gzhVar70.b = "camcorder.default_resolution_4K";
        gzhVar70.o();
        gzh gzhVar71 = new gzh();
        gzhVar71.b = "camcorder.fb_preview_1080p60fps";
        af = gzhVar71.i();
        gzh gzhVar72 = new gzh();
        gzhVar72.b = "camcorder.1080p60_thr";
        ag = gzhVar72.i();
        gzh gzhVar73 = new gzh();
        gzhVar73.b = "camcorder.front_4k";
        ah = gzhVar73.i();
        gzh gzhVar74 = new gzh();
        gzhVar74.b = "camcorder.front_4k60";
        ai = gzhVar74.i();
        gzh gzhVar75 = new gzh();
        gzhVar75.b = "camcorder.amber";
        aj = gzhVar75.i();
        gzh gzhVar76 = new gzh();
        gzhVar76.b = "camcorder.amber_ft_edu";
        ak = gzhVar76.f();
        gzh gzhVar77 = new gzh();
        gzhVar77.b = "camcorder.amethyst";
        al = gzhVar77.i();
        gzh gzhVar78 = new gzh();
        gzhVar78.b = "camcorder.amethyst_opt";
        am = gzhVar78.i();
        gzh gzhVar79 = new gzh();
        gzhVar79.b = "camcorder.halifax";
        gzhVar79.o();
        gzh gzhVar80 = new gzh();
        gzhVar80.b = "camcorder.hedgehog";
        an = gzhVar80.i();
        gzh gzhVar81 = new gzh();
        gzhVar81.b = "camcorder.hedgehog_all";
        ao = gzhVar81.i();
        gzh gzhVar82 = new gzh();
        gzhVar82.b = "camcorder.hedgehog_hbm_pri";
        k = gzhVar82.a();
        gzh gzhVar83 = new gzh();
        gzhVar83.b = "camcorder.hedgehog_hbm_sec";
        l = gzhVar83.a();
        gzh gzhVar84 = new gzh();
        gzhVar84.b = "camcorder.3a_video_metadata_extended";
        gzhVar84.o();
        gzh gzhVar85 = new gzh();
        gzhVar85.b = "camcorder.awb_bg_stats_video_metadata";
        gzhVar85.o();
        gzh gzhVar86 = new gzh();
        gzhVar86.b = "camcorder.emerald";
        gzhVar86.e();
        gzh gzhVar87 = new gzh();
        gzhVar87.b = "camcorder.thermal_recording_wrn";
        ap = gzhVar87.i();
        gzh gzhVar88 = new gzh();
        gzhVar88.b = "camcorder.enable_feature_central";
        gzhVar88.e();
        gzh gzhVar89 = new gzh();
        gzhVar89.b = "camcorder.xmp_dates";
        gzhVar89.o();
        gzh gzhVar90 = new gzh();
        gzhVar90.b = "camcorder.fps_thermal_throttle";
        aq = gzhVar90.i();
        gzh gzhVar91 = new gzh();
        gzhVar91.b = "camcorder.ruby";
        ar = gzhVar91.i();
        gzh gzhVar92 = new gzh();
        gzhVar92.b = "camcorder.graphite";
        as = gzhVar92.i();
        gzh gzhVar93 = new gzh();
        gzhVar93.b = "camcorder.ble_sco_intent";
        gzhVar93.e();
        gzh gzhVar94 = new gzh();
        gzhVar94.b = "camcorder.ble_audio";
        gzhVar94.n();
        gzh gzhVar95 = new gzh();
        gzhVar95.b = "camcorder.green_sand";
        at = gzhVar95.i();
        gzh gzhVar96 = new gzh();
        gzhVar96.b = "camcorder.fossil";
        au = gzhVar96.i();
        gzh gzhVar97 = new gzh();
        gzhVar97.b = "camcorder.sdm";
        gzhVar97.o();
        gzh gzhVar98 = new gzh();
        gzhVar98.b = "camcorder.sdm.trial";
        gzhVar98.e();
        gzh gzhVar99 = new gzh();
        gzhVar99.b = "camcorder.ds";
        gzhVar99.o();
        gzh gzhVar100 = new gzh();
        gzhVar100.b = "camcorder.ds_video";
        gzhVar100.o();
        gzh gzhVar101 = new gzh();
        gzhVar101.b = "camcorder.enable_crashing_on_encoder_errors";
        gzhVar101.n();
        gzh gzhVar102 = new gzh();
        gzhVar102.b = "camcorder.scalable_vpipe";
        gzhVar102.e();
        gzh gzhVar103 = new gzh();
        gzhVar103.b = "camcorder.buffer_pool_muxer";
        av = gzhVar103.i();
        gzh gzhVar104 = new gzh();
        gzhVar104.b = "camcorder.show_toast_if_metadata_too_large";
        gzhVar104.o();
        gzh gzhVar105 = new gzh();
        gzhVar105.b = "camcorder.zircon";
        gzhVar105.o();
        gzh gzhVar106 = new gzh();
        gzhVar106.b = "camcorder.malachite";
        gzhVar106.o();
    }

    public static void a(hbj hbjVar) {
        qxj qxjVar;
        hbjVar.d(a, null);
        hbjVar.d(b, null);
        hbjVar.l(m, true);
        hbjVar.l(n, true);
        hbjVar.l(o, true);
        hbjVar.l(p, true);
        hbjVar.l(q, true);
        hbjVar.j(r, true);
        hbjVar.j(s, true);
        hbjVar.l(t, true);
        hbjVar.d(c, 0);
        hbjVar.d(d, 0);
        hbjVar.d(e, 0);
        hbjVar.l(u, false);
        hbjVar.d(f, null);
        hbjVar.d(g, null);
        hbjVar.l(v, true);
        hbjVar.l(w, true);
        gzg gzgVar = y;
        Float fValueOf = Float.valueOf(5.0f);
        hbjVar.k(gzgVar, fValueOf);
        gzg gzgVar2 = z;
        Float fValueOf2 = Float.valueOf(3.0f);
        hbjVar.k(gzgVar2, fValueOf2);
        hbjVar.k(A, fValueOf2);
        hbjVar.k(x, fValueOf);
        hbjVar.l(B, false);
        hbjVar.l(C, true);
        hbjVar.l(D, false);
        hbjVar.l(E, true);
        hbjVar.l(F, true);
        hbjVar.l(G, false);
        hbjVar.l(H, true);
        hbjVar.l(I, false);
        hbjVar.l(J, true);
        hbjVar.l(K, false);
        hbjVar.d(i, null);
        hbjVar.l(L, true);
        hbjVar.l(M, false);
        gzg gzgVar3 = N;
        Long l2 = 107373133824L;
        String str = gzgVar3.b;
        if (str != null) {
            String str2 = gzgVar3.a;
            qxr qxrVar = hbg.a;
            String str3 = str + "__" + str2;
            l2.getClass();
            int i2 = qxt.d;
            qxjVar = new qxj(qxrVar, str3, l2, false);
        } else {
            qxjVar = null;
        }
        hbjVar.b.put(gzgVar3, new gox(l2, qxjVar));
        hbjVar.l(O, true);
        hbjVar.d(h, null);
        hbjVar.l(P, true);
        hbjVar.l(Q, false);
        hbjVar.l(R, false);
        hbjVar.l(S, false);
        hbjVar.l(T, false);
        hbjVar.l(V, false);
        hbjVar.i(X);
        hbjVar.d(j, 2);
        hbjVar.l(W, false);
        hbjVar.l(Y, true);
        hbjVar.l(Z, false);
        hbjVar.l(aa, true);
        hbjVar.l(ab, true);
        hbjVar.l(ac, false);
        hbjVar.l(ae, true);
        hbjVar.l(ad, true);
        hbjVar.l(af, false);
        hbjVar.l(ag, false);
        hbjVar.l(ah, false);
        hbjVar.l(ai, true);
        hbjVar.l(aj, false);
        hbjVar.i(ak);
        hbjVar.l(al, false);
        hbjVar.l(am, false);
        hbjVar.l(an, true);
        hbjVar.l(ao, false);
        hbjVar.d(k, 255);
        hbjVar.d(l, 0);
        hbjVar.l(ap, true);
        hbjVar.l(aq, true);
        hbjVar.l(ar, true);
        hbjVar.l(as, true);
        hbjVar.l(U, false);
        hbjVar.l(au, false);
        hbjVar.l(at, false);
        hbjVar.l(av, true);
    }
}
