package defpackage;

import com.google.android.apps.camera.focusindicator.CIAk.YyLACfm;
import com.google.android.apps.camera.jni.saliency.tLp.KsvNaXS;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class gyq {
    private static final Float a = Float.valueOf(4.84f);

    public static void a(hbj hbjVar, hbj hbjVar2, pnq pnqVar, hbc hbcVar) {
        hbjVar.g(gyg.f, Float.valueOf(1.3229325E7f));
        hbjVar.g(gyg.g, Float.valueOf(3.807744E7f));
        hbjVar.l(gzo.aU, true);
        hbjVar.l(gzo.bb, true);
        boolean z = pnqVar.v;
        hbjVar.c(gzo.l, Integer.valueOf(true != z ? 1600 : 1500));
        hbjVar.g(gzo.bk, Float.valueOf(1.580689f));
        hbjVar.j(gzo.am, true);
        hbjVar.l(gzo.ac, true);
        hbjVar.l(gzo.ad, true);
        hbjVar.l(gzo.bs, true);
        hbjVar.l(gzo.al, true);
        hbjVar.l(gzo.ai, false);
        hbjVar.j(gzo.bA, false);
        hbjVar.j(gzo.bC, z);
        hbjVar.l(gzo.bd, true);
        boolean z2 = pnqVar.w;
        hbjVar.g(hba.l, Float.valueOf(true != z2 ? 0.54906833f : 0.494478f));
        gzg gzgVar = hba.n;
        Float fValueOf = Float.valueOf(5.0f);
        hbjVar.g(gzgVar, fValueOf);
        hbjVar.g(hba.j, Float.valueOf(true != z2 ? 8.0f : 10.0f));
        hbjVar.c(hba.a, Integer.valueOf(true != z2 ? 1 : 10));
        hbjVar.l(hba.i, z);
        hbjVar.l(hba.k, true);
        hbjVar.h(gzo.aR, KsvNaXS.Vka);
        hbjVar.g(gyh.a, Float.valueOf(0.626f));
        hbjVar.g(gyh.b, Float.valueOf(0.81f));
        hbjVar.l(gyh.c, z2);
        hbjVar.l(gyh.g, z2);
        hbjVar.l(gyh.e, z2);
        hbjVar.l(gyh.f, z2);
        hbjVar.l(gze.g, true);
        gzg gzgVar2 = gze.b;
        Float fValueOf2 = Float.valueOf(1.0f);
        hbjVar.g(gzgVar2, fValueOf2);
        hbjVar.l(gze.h, true);
        hbjVar.l(gze.l, true);
        hbjVar.l(gze.n, false);
        hbjVar.l(gzb.b, true);
        hbjVar.l(gzb.c, true);
        hbjVar.l(gzb.d, true);
        hbjVar.l(gyv.d, z);
        hbjVar.l(gyv.e, false);
        hbjVar.l(gym.E, false);
        hbjVar.l(gym.af, false);
        hbjVar.l(gym.ag, true);
        hbjVar.l(gym.Q, false);
        hbjVar.l(gym.K, true);
        hbjVar.l(gym.R, true);
        hbjVar.l(gym.S, true);
        hbjVar.l(gym.T, true);
        hbjVar.l(gym.V, true);
        hbjVar.l(gym.W, true);
        hbjVar.l(gym.Y, false);
        hbjVar.l(gym.ah, true);
        float f = true != z2 ? 7.0f : 20.0f;
        gzg gzgVar3 = gym.y;
        Float fValueOf3 = Float.valueOf(f);
        hbjVar.g(gzgVar3, fValueOf3);
        hbjVar.g(gym.z, fValueOf3);
        hbjVar.g(gym.A, Float.valueOf(7.0f));
        hbjVar.g(gym.x, fValueOf3);
        hbjVar.l(gym.w, false);
        hbjVar.l(gzo.Q, false);
        hbjVar.l(gym.am, true);
        hbjVar.l(gym.aj, true);
        hbjVar.l(gym.Z, false);
        hbjVar.l(gym.I, true);
        hbjVar.l(gym.ac, true);
        hbjVar.l(gym.B, true);
        hbjVar.l(gym.U, true);
        hbjVar.l(gym.at, true);
        hbjVar.c(gym.k, z2 ? 161 : 181);
        hbjVar.l(gym.ao, true);
        hbjVar.l(gym.au, true);
        hbjVar.l(gym.H, false);
        hbjVar.l(hax.c, z2);
        hbc hbcVar2 = hbc.DOGFOOD;
        hbcVar.b(hbcVar2);
        hbjVar.l(hax.j, z2 && hbcVar.b(hbcVar2));
        if (z2) {
            hbcVar.b(hbcVar2);
        }
        hbjVar.h(haq.f, "avenh-model0-rio.tflite.uncompressed");
        hbjVar.l(gys.d, true);
        hbjVar.l(gyx.b, true);
        hbjVar.l(gyx.c, true);
        hbjVar.l(gyx.f, true);
        hbjVar.l(gyx.e, true);
        hbjVar.l(gyx.g, true);
        hbjVar.h(gyx.h, "deeprestore_face_float32_512x512_v13_rc2_float-graph-custom_op_p23.tflite.uncompressed");
        hbjVar.c(gyx.a, 4);
        hbjVar.l(gyx.i, true);
        hbjVar.h(has.g, "siamese_fe_darwinn_custom_op_rio_a0.tflite.uncompressed");
        hbjVar.h(has.h, "siamese_end2end_darwinn_custom_op_rio_a0.tflite.uncompressed");
        hbjVar.l(gzc.j, true);
        hbjVar.l(gzc.B, true);
        hbjVar.l(gzc.x, true);
        hbjVar.c(gzc.f, 2048);
        hbjVar.l(gzc.C, z2);
        hbjVar.l(gzc.R, z2);
        hbjVar.l(gzc.T, z2);
        hbjVar.h(gzc.F, rnt.ac(Integer.valueOf(nkw.PHOTO.u), Integer.valueOf(nkw.NIGHT_SIGHT.u), new Object[0]));
        hbjVar.l(gzc.U, z2);
        hbjVar.l(gzc.D, z2);
        hbjVar.l(gzc.V, z2);
        gzg gzgVar4 = gzc.H;
        Float fValueOf4 = Float.valueOf(0.5f);
        hbjVar.g(gzgVar4, fValueOf4);
        hbjVar.g(gzc.I, Float.valueOf(-1.0f));
        hbjVar.h(gzc.E, "hawk_full_fov_custom-op-p23.tflite.uncompressed");
        hbjVar.l(gyz.b, true);
        hbjVar.h(gyz.c, "a1ee2cc664984df28c3624291d398fb6.uncompressed");
        hbjVar.h(gyz.d, "a6e0c8748401410a834a9029d7050e25.uncompressed");
        hbjVar.h(gyz.e, "dbdaa025a5bf4d0889e146bc35281e3c.uncompressed");
        hbjVar.l(gzs.ab, true);
        hbjVar.l(gzs.at, true);
        hbjVar.l(gzs.aU, true);
        hbjVar.l(gzs.ar, true);
        hbjVar.l(hac.r, true);
        hbjVar.l(hac.q, true);
        hbjVar.l(gzs.ae, true);
        hbjVar.l(hac.O, z2);
        hbjVar.g(hac.Q, Float.valueOf(-5.2f));
        hbjVar.g(hac.R, Float.valueOf(-5.0f));
        hbjVar.g(hac.S, Float.valueOf(-4.5f));
        hbjVar.g(gzs.Z, Float.valueOf(999.0f));
        hbjVar.l(hac.L, true);
        hbjVar.l(gzo.bD, true);
        hbjVar.l(hab.d, true);
        hbjVar.l(hab.e, true);
        hbjVar.l(hab.f, true);
        hbjVar.l(hab.g, true);
        hbjVar.l(hab.h, true);
        hbjVar.h(hab.i, "motion-custom_op-p23.tflite.uncompressed");
        hbjVar.h(hab.j, "saliency-custom_op-p23.tflite.uncompressed");
        hbjVar.l(gze.i, true);
        hbjVar.j(gzz.h, false);
        hbjVar.l(gzz.l, false);
        hbjVar.l(gzz.x, true);
        hbjVar.l(gzz.w, true);
        hbjVar.l(gzz.E, true);
        hbjVar.l(haa.A, true);
        hbjVar.l(haa.aa, true);
        hbjVar.l(haa.W, true);
        hbjVar.l(haa.ab, true);
        hbjVar.l(haa.B, true);
        hbjVar.l(haa.Y, true);
        gzi gziVar = haa.d;
        hbc hbcVar3 = hbc.ENG;
        hbjVar.c(gziVar, Integer.valueOf(true != hbcVar.b(hbcVar3) ? 5 : 10));
        hbjVar.l(gzo.aV, true);
        hbjVar.l(haa.y, true);
        hbjVar.l(haa.z, true);
        hbjVar.l(haa.o, true);
        hbjVar.l(haa.q, true);
        hbjVar.l(haa.D, true);
        hbjVar.l(haa.Z, true);
        hbjVar.c(hae.b, Integer.valueOf(((Integer) hbjVar2.a(hae.c).get()).intValue() * 5));
        hbjVar.c(hae.a, 300);
        hbjVar.l(hae.k, false);
        hbjVar.l(hae.l, true);
        hbjVar.l(hae.x, true);
        hbjVar.l(han.c, z2);
        hbjVar.l(han.d, z2);
        hbjVar.j(han.k, false);
        hbjVar.l(hak.w, true);
        hbjVar.l(hak.v, true);
        hbjVar.l(hak.F, true);
        hbjVar.l(hak.G, true);
        hbjVar.g(hak.c, Float.valueOf(1.5172f));
        hbjVar.g(hak.d, Float.valueOf(2.0f));
        hbjVar.l(hak.Z, true);
        hbjVar.g(hak.X, Float.valueOf(3.0f));
        hbjVar.l(hak.p, true);
        hbjVar.l(hak.q, true);
        hbjVar.l(hak.A, true);
        hbjVar.l(hak.K, true);
        hbjVar.l(hak.L, true);
        hbjVar.l(hak.aa, true);
        hbjVar.l(hak.ad, true);
        hbjVar.l(hak.ae, true);
        hbjVar.h(hak.N, true != hbcVar.b(hbcVar3) ? "" : "c757a03ae8d64d1b9375002b75dcdbbc/c757a03ae8d64d1b9375002b75dcdbbc.uncompressed");
        hbjVar.h(hak.M, "4cdbd4b13ea54a309eb235a75232ae6d/4cdbd4b13ea54a309eb235a75232ae6d.uncompressed");
        hbjVar.h(hak.P, "5751e2e2a711430695dac2c034cfd295/5751e2e2a711430695dac2c034cfd295.uncompressed");
        hbjVar.h(hak.R, true == hbcVar.b(hbcVar3) ? "0ea471704af14008b0483bc9b630a85c/0ea471704af14008b0483bc9b630a85c.uncompressed" : "");
        hbjVar.h(hak.S, "efaffa0bfaf74be2ad2e17aeff79f3db/efaffa0bfaf74be2ad2e17aeff79f3db.uncompressed");
        hbjVar.h(hak.T, "cac29f5597f5453bbabb54f6f2080e39/cac29f5597f5453bbabb54f6f2080e39.uncompressed");
        hbjVar.h(hak.U, "a7ab2018912b4f958760b7763b36256a/a7ab2018912b4f958760b7763b36256a.uncompressed");
        hbjVar.c(gyk.b, Integer.valueOf(true != z2 ? 2016 : 2000));
        hbjVar.c(gyk.c, Integer.valueOf(true != z2 ? 1508 : 1500));
        hbjVar.c(gyk.a, 0);
        hbjVar.l(hak.s, false);
        hbjVar.l(hak.t, true);
        hbjVar.h(hak.u, "P23");
        hbjVar.l(haw.l, true);
        hbjVar.l(haw.n, true);
        hbjVar.g(haw.u, fValueOf2);
        hbjVar.l(gzo.Z, true);
        hbjVar.l(gzo.ab, true);
        hbjVar.l(hba.g, true);
        hbjVar.l(hba.h, true);
        hbjVar.l(gzo.aa, z2);
        gzi gziVar2 = hau.a;
        hbjVar.l(gyw.j, true);
        hbjVar.l(gzy.j, true);
        hbjVar.l(gzy.k, true);
        hbjVar.g(gzy.n, a);
        hbjVar.l(gzs.O, true);
        hbjVar.l(gzs.Q, true);
        hbjVar.h(gzs.P, "lancet_alpha_v2-p23.tflite.uncompressed");
        hbjVar.l(gzs.au, true);
        hbjVar.h(gzs.aw, "pecan-p23-custom_op.tflite.uncompressed");
        hbjVar.l(gzs.aA, true);
        hbjVar.h(gzs.ax, "pecan-p23-luma-hybrid-custom_op.tflite.uncompressed");
        hbjVar.h(gzs.aL, YyLACfm.kSbwUZLP);
        int i = gyu.a;
        hbjVar.l(gyo.f, true);
        hbjVar.l(haa.w, true);
        hbjVar.l(haa.aj, true);
        hbjVar.l(gyf.c, true);
        hbjVar.l(hai.b, false);
        hbjVar.l(gzs.H, false);
        hbjVar.l(gzs.I, true);
        hbjVar.l(gzs.aF, true);
        hbjVar.l(hae.w, true);
        hbjVar.j(hal.a, z2);
        hbjVar.l(gyg.h, true);
        hbjVar.l(gyg.i, true);
        hbjVar.l(gyg.j, true);
        hbjVar.l(gyg.d, true);
        hbjVar.l(gzq.d, false);
        hbjVar.l(gzq.e, false);
        hbjVar.g(hal.l, fValueOf4);
        hbjVar.g(hal.m, fValueOf2);
        hbjVar.g(hal.n, fValueOf2);
        hbjVar.g(hal.o, fValueOf);
        hbjVar.g(hal.p, fValueOf);
        hbjVar.g(hal.q, Float.valueOf(30.0f));
        if (hbcVar.b(hbcVar2)) {
            hbjVar.l(gzp.k, true);
        }
        if (z) {
            hbjVar.g(gzp.n, Float.valueOf(0.75f));
        }
    }
}
