package defpackage;

import androidx.coordinatorlayout.widget.pcp.OPuAVreQM;
import com.google.android.apps.camera.autotimer.analysis.jni.wVCD.HHdu;
import com.google.android.apps.camera.coach.YOHg.INRGuObcrHjSQz;
import com.google.android.apps.camera.rectiface.Iqz.mPfBwqXsnpXI;
import com.google.android.play.core.install.rwb.GAQqzWiWWcYOgy;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gzc {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final String a = "102";
    public static final String b = "105";
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    public static void a(hbj hbjVar, hbc hbcVar) {
        hbjVar.l(j, false);
        hbjVar.l(B, false);
        hbjVar.l(s, false);
        hbjVar.l(u, false);
        hbjVar.l(v, false);
        hbjVar.l(w, false);
        hbjVar.l(x, false);
        hbjVar.l(t, false);
        hbjVar.l(z, false);
        hbjVar.l(y, false);
        hbjVar.d(c, 150);
        hbjVar.d(d, 50);
        hbjVar.d(e, 2000);
        hbjVar.d(f, 1280);
        hbjVar.l(A, true);
        hbjVar.l(C, false);
        hbjVar.l(D, false);
        hbjVar.m(F, Integer.toString(nkw.PHOTO.u));
        hbjVar.l(G, hbcVar.a(hbc.FISHFOOD));
        gzg gzgVar = H;
        Float fValueOf = Float.valueOf(0.0f);
        hbjVar.k(gzgVar, fValueOf);
        hbjVar.k(I, fValueOf);
        gzg gzgVar2 = J;
        Float fValueOf2 = Float.valueOf(-1.0f);
        hbjVar.k(gzgVar2, fValueOf2);
        hbjVar.k(K, Float.valueOf(2.45f));
        hbjVar.k(L, Float.valueOf(4.9f));
        hbjVar.l(M, false);
        hbjVar.l(N, false);
        hbjVar.l(O, false);
        hbjVar.l(P, false);
        hbjVar.l(Q, false);
        hbjVar.l(R, false);
        hbjVar.k(S, fValueOf2);
        hbjVar.l(T, false);
        hbjVar.l(U, false);
        hbjVar.l(V, false);
        hbjVar.m(E, "hawk_full_fov_custom-op-p23.tflite.uncompressed");
        hbjVar.d(g, Integer.MAX_VALUE);
        hbjVar.l(k, false);
        hbjVar.k(m, Float.valueOf(2.68f));
        hbjVar.l(n, false);
        hbjVar.l(p, false);
        hbjVar.k(o, fValueOf2);
        hbjVar.k(q, Float.valueOf(1.0f));
        hbjVar.k(r, Float.valueOf(1.99f));
        hbjVar.m(l, null);
        hbjVar.d(h, 2);
        hbjVar.d(i, 3);
    }

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.falcon_enabled";
        j = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.cyclops_enabled";
        k = gzhVar2.i();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.cyclops_fullframe_enabled";
        gzhVar3.o();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.cyclops.model.tpu";
        l = gzhVar4.j();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.cyclops.model.gpu";
        gzhVar5.l();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.cyclops.model.tpu.full_frame";
        gzhVar6.l();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.cyclops.model.gpu.full_frame";
        gzhVar7.l();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.cyclops_preferred";
        gzhVar8.o();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.cyclops_save_debug_images";
        gzhVar9.o();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.cyclops_save_more_debug_images";
        gzhVar10.o();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.cyclops_use_single_frame_hdr";
        gzhVar11.o();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.cyclops_f_number_scale";
        m = gzhVar12.h();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.cyclops_use_tpu";
        n = gzhVar13.i();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.cyclops_annotate";
        gzhVar14.o();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.cyclops_max_shot_capture_time_ms";
        o = gzhVar15.h();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.cyclops_force_trigger_face";
        gzhVar16.o();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.cyclops_power_hint";
        p = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = mPfBwqXsnpXI.fiSKj;
        gzhVar18.m();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.cyclops_force_fusion";
        gzhVar19.o();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.cyclops_use_most_recent_frame_for_base_frame";
        gzhVar20.m();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = HHdu.eZEgBHUF;
        q = gzhVar21.h();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.cyclops_upper_limit";
        r = gzhVar22.h();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.falcon_md_enabled";
        s = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.falcon_annotate";
        t = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.falcon_save_original";
        u = gzhVar25.i();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.falcon_process_original";
        v = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.falcon_save_secondary";
        w = gzhVar27.i();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.falcon_power_hint";
        x = gzhVar28.i();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = GAQqzWiWWcYOgy.jKxppHFRDP;
        y = gzhVar29.i();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.falcon_force_fusion";
        z = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.falcon_ahwb";
        gzhVar31.o();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.falcon_standby";
        gzhVar32.o();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.falcon_flush_sample_count";
        c = gzhVar33.a();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.falcon_mm_badge";
        A = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.falcon_tpu_enabled";
        gzhVar35.m();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.gyrfalcon_enabled";
        B = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.falcon_lowlight_lux_threshold";
        d = gzhVar37.a();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.falcon_min_exposure_time_us";
        e = gzhVar38.a();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.falcon_min_primary_dimension";
        f = gzhVar39.a();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.falcon_max_active_shot";
        g = gzhVar40.a();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.hawk_enabled";
        C = gzhVar41.i();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.hawk_tpu_enabled";
        D = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.hawk_tpu_full_fov_asset_name";
        E = gzhVar43.j();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.hawk_supported_modes";
        F = gzhVar44.j();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.hawk_power_hint";
        G = gzhVar45.i();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.hawk_boost_big_option";
        H = gzhVar46.h();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.hawk_boost_mid_option";
        I = gzhVar47.h();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.hawk_boost_little_option";
        J = gzhVar48.h();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.hawk_threshold";
        K = gzhVar49.h();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = OPuAVreQM.fASEDbZHSauYVQk;
        L = gzhVar50.h();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camera.hawk_save_debug";
        M = gzhVar51.i();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camera.hawk_save_more_debug";
        N = gzhVar52.i();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera.hawk_annotate";
        O = gzhVar53.i();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera.hawk_force_fusion";
        P = gzhVar54.i();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camera.hawk_crash_on_not_engaged";
        Q = gzhVar55.i();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "camera.hawk_disable_thermal";
        gzhVar56.e();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "camera.hawk_trim";
        R = gzhVar57.i();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "camera.hawk_downsample_tele_zoom_ratio";
        S = gzhVar58.h();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "camera.hawk_throttled_tele_frames_enabled";
        T = gzhVar59.i();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camera.hawk_luma_secondary_enabled";
        U = gzhVar60.i();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camera.hawk_full_fov_enhancement";
        V = gzhVar61.i();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camera.bennu_enabled";
        gzhVar62.o();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = INRGuObcrHjSQz.QxcfyThmPcwRDG;
        h = gzhVar63.a();
        gzh gzhVar64 = new gzh();
        gzhVar64.b = "camera.bennu_max_zsl_count";
        i = gzhVar64.a();
        gzh gzhVar65 = new gzh();
        gzhVar65.b = "camera.bennu_save_debug_images";
        gzhVar65.o();
    }
}
