package defpackage;

import com.google.android.apps.camera.coach.YOHg.INRGuObcrHjSQz;
import com.google.android.apps.camera.facemetadata.conversions.jni.HM.oUZhwRhE;
import com.google.android.gms.common.internal.oQFY.clFzVRcygwbq;
import com.google.googlex.gcam.dirtylens.PrCd.TOnSyMaYeslEl;
import java.util.concurrent.TimeUnit;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gzo {
    public static final gzi A;
    public static final gzi B;
    public static final gzi C;
    public static final gzi D;
    public static final gzi E;
    public static final gzi F;
    public static final gzi G;
    public static final gzi H;
    public static final gzi I;
    public static final gzi J;
    public static final gzi K;
    public static final gzi L;
    public static final gzi M;
    public static final gzi N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final gzg W;
    public static final gzg X;
    public static final gzg Y;
    public static final gzg Z;
    public static final gzi a;
    public static final gzg aA;
    public static final gzg aB;
    public static final gzg aC;
    public static final gzg aD;
    public static final gzg aE;
    public static final gzg aF;
    public static final gzg aG;
    public static final gzg aH;
    public static final gzg aI;
    public static final gzg aJ;
    public static final gzg aK;
    public static final gzg aL;
    public static final gzg aM;
    public static final gzg aN;
    public static final gzg aO;
    public static final gzg aP;
    public static final gzg aQ;
    public static final gzg aR;
    public static final gzg aS;
    public static final gzg aT;
    public static final gzg aU;
    public static final gzg aV;
    public static final gzg aW;
    public static final gzg aX;
    public static final gzg aY;
    public static final gzg aZ;
    public static final gzg aa;
    public static final gzg ab;
    public static final gzg ac;
    public static final gzg ad;
    public static final gzg ae;
    public static final gzg af;
    public static final gzg ag;
    public static final gzg ah;
    public static final gzg ai;
    public static final gzg aj;
    public static final gzg ak;
    public static final gzg al;
    public static final gzg am;
    public static final gzg an;
    public static final gzg ao;
    public static final gzg ap;
    public static final gzg aq;
    public static final gzg ar;
    public static final gzg as;
    public static final gzg at;
    public static final gzg au;
    public static final gzg av;
    public static final gzg aw;
    public static final gzg ax;
    public static final gzg ay;
    public static final gzg az;
    public static final gzi b;
    public static final gzg bA;
    public static final gzg bB;
    public static final gzg bC;
    public static final gzg bD;
    public static final gzg bE;
    public static final gzg bF;
    public static final gzg bG;
    public static final gzg bH;
    public static final gzg bI;
    public static final gzg bJ;
    public static final gzg ba;
    public static final gzg bb;
    public static final gzg bc;
    public static final gzg bd;
    public static final gzg be;
    public static final gzg bf;
    public static final gzg bg;
    public static final gzg bh;
    public static final gzg bi;
    public static final gzg bj;
    public static final gzg bk;
    public static final gzg bl;
    public static final gzg bm;
    public static final gzg bn;
    public static final gzg bo;
    public static final gzg bp;
    public static final gzg bq;
    public static final gzg br;
    public static final gzg bs;
    public static final gzg bt;
    public static final gzg bu;
    public static final gzg bv;
    public static final gzg bw;
    public static final gzg bx;
    public static final gzg by;
    public static final gzg bz;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzi k;
    public static final gzi l;
    public static final gzi m;
    public static final gzi n;
    public static final gzi o;
    public static final gzi p;
    public static final gzi q;
    public static final gzi r;
    public static final gzi s;
    public static final gzi t;
    public static final gzi u;
    public static final gzi v;
    public static final gzi w;
    public static final gzi x;
    public static final gzi y;
    public static final gzi z;

    public static void a(hbj hbjVar, pnp pnpVar, hbc hbcVar) {
        hbjVar.l(O, true);
        hbjVar.l(P, true);
        hbjVar.l(Q, true);
        hbjVar.j(R, true);
        hbjVar.l(S, true);
        hbjVar.l(T, true);
        hbjVar.l(U, true);
        hbjVar.m(V, "");
        hbjVar.m(W, "");
        hbjVar.m(X, "");
        hbjVar.m(Y, "");
        hbjVar.n(ae, "camera-feedback@google.com");
        hbjVar.n(af, "camera-feedback@google.com");
        hbjVar.n(ag, "pixel-dogfood-discuss@google.com");
        hbjVar.d(a, null);
        hbjVar.l(ai, true);
        hbjVar.i(aj);
        hbjVar.d(b, 2);
        hbjVar.d(c, 0);
        hbjVar.l(ak, true);
        hbjVar.l(al, false);
        hbjVar.d(d, 512);
        hbjVar.d(e, 22500000);
        hbjVar.l(ao, true);
        hbjVar.m(ap, "3.6");
        hbjVar.l(aq, hbcVar == hbc.RELEASE || hbcVar == hbc.DOGFOOD);
        hbjVar.l(ar, true);
        hbjVar.d(i, Integer.valueOf((int) TimeUnit.HOURS.toSeconds(24L)));
        hbjVar.d(j, 1800000);
        hbjVar.l(as, true);
        hbjVar.l(at, true);
        hbjVar.l(au, nvh.a != null);
        hbjVar.l(av, false);
        hbjVar.l(aw, false);
        hbjVar.d(k, 5000);
        hbjVar.d(l, -1);
        hbjVar.d(m, -1);
        hbjVar.l(ax, false);
        hbjVar.l(ay, true);
        hbc hbcVar2 = hbc.FISHFOOD;
        hbcVar.a(hbcVar2);
        hbjVar.d(o, 2000);
        hbjVar.l(aG, nvj.r != null);
        hbjVar.l(aC, false);
        hbjVar.i(aD);
        hbc hbcVar3 = hbc.ENG;
        hbcVar.equals(hbcVar3);
        hbjVar.l(aF, true);
        hbjVar.d(p, 60);
        hbjVar.j(aH, true);
        hbjVar.d(q, 2000);
        hbjVar.l(aJ, false);
        hbjVar.l(aK, false);
        hbjVar.l(aL, true);
        hbjVar.d(f, -5937);
        hbjVar.j(am, false);
        hbjVar.d(g, -855643953);
        hbjVar.d(h, -855643953);
        hbjVar.l(an, true);
        hbjVar.d(r, 2);
        hbjVar.l(aO, false);
        hbjVar.l(aP, true);
        hbjVar.l(aX, false);
        hbjVar.l(aS, true);
        hbjVar.l(aU, false);
        hbjVar.l(aV, false);
        hbjVar.l(aW, true);
        hbjVar.l(aY, true);
        hbjVar.l(aZ, false);
        hbjVar.l(ba, false);
        hbjVar.l(bb, false);
        hbjVar.l(aT, true);
        hbjVar.l(aI, false);
        hbjVar.l(bc, true);
        hbjVar.l(aN, false);
        hbjVar.l(aM, true);
        hbjVar.l(bd, false);
        hbjVar.l(be, true);
        hbjVar.d(u, 7);
        hbjVar.d(v, 30);
        hbjVar.d(x, 30);
        hbjVar.d(w, 1000);
        hbjVar.d(y, 250);
        hbjVar.d(z, 0);
        hbjVar.l(bf, true);
        hbjVar.d(A, null);
        hbjVar.l(bg, true);
        hbjVar.l(Z, false);
        hbjVar.l(aa, false);
        hbjVar.l(ab, false);
        hbjVar.l(ah, false);
        hbjVar.d(B, 3);
        hbjVar.d(C, 3);
        hbjVar.d(D, -1);
        hbjVar.d(E, -1);
        hbjVar.d(K, 4);
        hbjVar.d(F, 1000);
        hbjVar.l(bi, false);
        hbjVar.l(bh, true);
        hbjVar.k(bk, Float.valueOf(1.408535f));
        hbjVar.d(G, Integer.MAX_VALUE);
        hbjVar.d(H, Integer.MAX_VALUE);
        hbjVar.d(I, Integer.MAX_VALUE);
        hbjVar.d(J, Integer.MAX_VALUE);
        hbjVar.l(bl, false);
        hbjVar.m(bj, "https://support.google.com/pixelphone/gethelp");
        hbjVar.l(bm, true);
        hbjVar.l(bn, true);
        hbjVar.l(bo, hbcVar.a(hbcVar3));
        hbjVar.l(bp, hbcVar.a(hbcVar2));
        boolean z2 = pnpVar.d;
        hbjVar.l(aB, true);
        hbjVar.l(ac, false);
        hbjVar.l(ad, false);
        hbjVar.d(L, 1);
        hbjVar.l(bq, true);
        hbjVar.l(br, true);
        hbjVar.l(bs, false);
        hbjVar.l(aE, true);
        hbjVar.j(bt, true);
        hbjVar.m(aQ, "");
        hbjVar.m(aR, "");
        hbjVar.l(bu, true);
        hbjVar.l(bv, true);
        hbjVar.l(bx, true);
        hbjVar.l(by, true);
        hbjVar.l(bz, true);
        hbjVar.j(bA, true);
        hbjVar.j(bB, false);
        hbjVar.j(bC, true);
        hbjVar.d(M, 2000);
        hbjVar.d(N, 500);
        hbjVar.l(bD, false);
        hbjVar.l(bE, true);
        hbjVar.j(bG, true);
        hbjVar.l(bF, true);
        hbjVar.l(bH, true);
        hbjVar.l(bI, false);
        hbjVar.l(bw, false);
        hbjVar.d(s, 5000);
        hbjVar.d(t, 500);
        hbjVar.l(bJ, hbcVar.b(hbc.DOGFOOD));
    }

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.scudo_caching";
        O = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.bind_assistant";
        P = gzhVar2.i();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.flash.ind";
        gzhVar3.e();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.auto_fps_default";
        Q = gzhVar4.i();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.auto_fps";
        R = gzhVar5.g();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "avc_profile_high_supported";
        S = gzhVar6.i();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "back_flash_off_by_default";
        T = gzhVar7.i();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "back_flash_availability";
        U = gzhVar8.i();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "blocklisted_resolutions_back";
        V = gzhVar9.j();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "blocklisted_resolutions_front";
        W = gzhVar10.j();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "blocklisted_preview_resolutions_back";
        X = gzhVar11.j();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "blocklisted_preview_resolutions_front";
        Y = gzhVar12.j();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.narrow_cam";
        gzhVar13.e();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.p20_lens_setup";
        Z = gzhVar14.i();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.tele_lens";
        aa = gzhVar15.i();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.p21_front_setup";
        ab = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.wide_cam";
        gzhVar17.e();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "ripper_embedded";
        ac = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.enable_hw_buff_uflag";
        ad = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.chk_anim_trnstns";
        gzhVar20.m();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.disable_phenotype";
        gzhVar21.e();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.disable_clearcut";
        gzhVar22.e();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.clearcut_debug";
        gzhVar23.e();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "contact_us_mailing_list_address_default";
        ae = gzhVar24.k();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "contact_us_mailing_list_address_for_droid_canary_and_fishfood";
        af = gzhVar25.k();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "contact_us_mailing_list_address_for_google_food";
        ag = gzhVar26.k();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.vid_meta_fatal";
        gzhVar27.m();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.developer.enable";
        gzhVar28.n();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.fake_therm_state";
        a = gzhVar29.a();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.ignore_temp";
        gzhVar30.e();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.mock_low_storage";
        gzhVar31.e();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.photo_fixed_framerate";
        ah = gzhVar32.i();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.debug_hw_ver";
        gzhVar33.o();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "exif_model_make_sanitization_enabled";
        ai = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.exp.activity";
        gzhVar35.e();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.faceannouncer";
        aj = gzhVar36.f();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.faceboxes";
        gzhVar37.e();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = INRGuObcrHjSQz.dZTlWAKwuh;
        b = gzhVar38.a();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.video_preview_frame_extra_delay";
        c = gzhVar39.a();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera_vf_image_stealing";
        ak = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera_fs_thread_prewarm";
        gzhVar41.c(new gyn(4));
        gzhVar41.o();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.enable_base_frame_debug";
        al = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "filmstrip_tiny_bounds";
        d = gzhVar43.a();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "filmstrip_maximum_smooth_pixels";
        e = gzhVar44.a();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.focus.debug";
        gzhVar45.e();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.front.flashColor";
        f = gzhVar46.a();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.front_torch_request";
        am = gzhVar47.g();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.front.backgroundIlluminationColor";
        g = gzhVar48.a();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.front.viewfinderIlluminationColor";
        h = gzhVar49.a();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camera.front.translucentSelfieIllumination";
        an = gzhVar50.i();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "google_lens_enabled";
        ao = gzhVar51.i();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "google_lens_min_supported_photos_app_version";
        ap = gzhVar52.j();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera_hermes_enabled";
        aq = gzhVar53.i();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera_hermes_gc_enabled";
        ar = gzhVar54.i();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camera_hermes_interval_seconds";
        i = gzhVar55.a();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "hermes_activity_finish_millis";
        j = gzhVar56.a();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "high_performance_ipe_supported";
        as = gzhVar57.i();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "hybrid_ae_only_ois_jitter_for_back_camera_enabled";
        at = gzhVar58.i();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "hybrid_ae_supported";
        au = gzhVar59.i();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camera.enable_lkcnry";
        gzhVar60.o();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camera.use_local_logger";
        av = gzhVar61.i();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camera.use_perf_logger";
        aw = gzhVar62.i();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = "camera.logger_throttle_millis";
        k = gzhVar63.a();
        gzh gzhVar64 = new gzh();
        gzhVar64.b = "max_allowed_allocator_memory_mb";
        l = gzhVar64.a();
        gzh gzhVar65 = new gzh();
        gzhVar65.b = "max_allowed_native_memory_mb";
        m = gzhVar65.a();
        gzh gzhVar66 = new gzh();
        gzhVar66.b = "measure_integration_enabled";
        ax = gzhVar66.i();
        gzh gzhVar67 = new gzh();
        gzhVar67.b = "ois_api_supported";
        ay = gzhVar67.i();
        gzh gzhVar68 = new gzh();
        gzhVar68.b = "ois_api_version";
        n = gzhVar68.a();
        gzh gzhVar69 = new gzh();
        gzhVar69.b = "camera.onscreen_logcat";
        az = gzhVar69.e();
        gzh gzhVar70 = new gzh();
        gzhVar70.b = "camera.onscreen_log";
        aA = gzhVar70.e();
        gzh gzhVar71 = new gzh();
        gzhVar71.b = "selfie_mirror_log";
        gzhVar71.e();
        gzh gzhVar72 = new gzh();
        gzhVar72.b = "mn_enabled";
        aB = gzhVar72.i();
        gzh gzhVar73 = new gzh();
        gzhVar73.b = oUZhwRhE.XGyIJLcQ;
        gzhVar73.o();
        gzh gzhVar74 = new gzh();
        gzhVar74.b = "camera_perfetto_trigger_millis";
        gzhVar74.d("General", false);
        o = gzhVar74.a();
        gzh gzhVar75 = new gzh();
        gzhVar75.b = "camera.prod_testing";
        aC = gzhVar75.i();
        gzh gzhVar76 = new gzh();
        gzhVar76.b = "camera.progress_overlay";
        aD = gzhVar76.f();
        gzh gzhVar77 = new gzh();
        gzhVar77.b = "camera.enable_slowmo";
        aE = gzhVar77.i();
        gzh gzhVar78 = new gzh();
        gzhVar78.b = "fatal_error_sql_error_checks_enabled";
        gzhVar78.m();
        gzh gzhVar79 = new gzh();
        gzhVar79.b = "camera.shot_tracking";
        aF = gzhVar79.i();
        gzh gzhVar80 = new gzh();
        gzhVar80.b = "camera.shot_tracking.sql_checks";
        gzhVar80.o();
        gzh gzhVar81 = new gzh();
        gzhVar81.b = "camera.shot_tracking.stuck_age_seconds";
        p = gzhVar81.a();
        gzh gzhVar82 = new gzh();
        gzhVar82.b = "pd_calibration_data_supported";
        aG = gzhVar82.i();
        gzh gzhVar83 = new gzh();
        gzhVar83.b = "camera.60fps";
        aH = gzhVar83.g();
        gzh gzhVar84 = new gzh();
        gzhVar84.b = "unflipped_selfie_default";
        aI = gzhVar84.i();
        gzh gzhVar85 = new gzh();
        gzhVar85.b = "scripting_enabled";
        gzhVar85.o();
        gzh gzhVar86 = new gzh();
        gzhVar86.b = "camera_slow_launch_dialog_trigger_ms";
        gzhVar86.d("General", false);
        q = gzhVar86.a();
        gzh gzhVar87 = new gzh();
        gzhVar87.b = "enable_social_share";
        gzhVar87.d("SocialShare", false);
        aJ = gzhVar87.i();
        gzh gzhVar88 = new gzh();
        gzhVar88.b = "enable_social_share_opt_in";
        aK = gzhVar88.i();
        gzh gzhVar89 = new gzh();
        gzhVar89.b = "enable_bounce_animation_on_social_share_menu";
        aL = gzhVar89.i();
        gzh gzhVar90 = new gzh();
        gzhVar90.b = "fixate_nearby_share";
        aM = gzhVar90.i();
        gzh gzhVar91 = new gzh();
        gzhVar91.b = "camera.obfuscation_share_enabled";
        aN = gzhVar91.i();
        gzh gzhVar92 = new gzh();
        gzhVar92.b = "camera.strict_vm";
        gzhVar92.m();
        gzh gzhVar93 = new gzh();
        gzhVar93.b = "camera.strict_vm_die_on_violation";
        gzhVar93.o();
        gzh gzhVar94 = new gzh();
        gzhVar94.b = "camera.strict_vm_visual_warning_on_violation";
        gzhVar94.m();
        gzh gzhVar95 = new gzh();
        gzhVar95.b = "camera.strict_vm_diskread";
        gzhVar95.m();
        gzh gzhVar96 = new gzh();
        gzhVar96.b = "camera.syshealth_info";
        gzhVar96.e();
        gzh gzhVar97 = new gzh();
        gzhVar97.b = "camera.memory_monitor_overlay";
        gzhVar97.m();
        gzh gzhVar98 = new gzh();
        gzhVar98.b = "camera.double_tap_launch_bottom_sheet";
        r = gzhVar98.a();
        gzh gzhVar99 = new gzh();
        gzhVar99.b = "camera.fs_resource_tracking";
        gzhVar99.e();
        gzh gzhVar100 = new gzh();
        gzhVar100.b = "camera.fs_resource_tracking_retention_timeout_ms";
        s = gzhVar100.a();
        gzh gzhVar101 = new gzh();
        gzhVar101.b = "camera.fs_resource_tracking_total_acquired_count";
        t = gzhVar101.a();
        gzh gzhVar102 = new gzh();
        gzhVar102.b = "camera.dbg.bugtoast";
        gzhVar102.o();
        gzh gzhVar103 = new gzh();
        gzhVar103.b = "camera.dbg.3a_bugtoast";
        gzhVar103.o();
        gzh gzhVar104 = new gzh();
        gzhVar104.b = "camera.skip_oobe";
        aO = gzhVar104.i();
        gzh gzhVar105 = new gzh();
        gzhVar105.b = "camera.location_default";
        aP = gzhVar105.i();
        gzh gzhVar106 = new gzh();
        gzhVar106.b = "camera.res.override_back";
        aQ = gzhVar106.j();
        gzh gzhVar107 = new gzh();
        gzhVar107.b = "camera.res.override_front";
        aR = gzhVar107.j();
        gzh gzhVar108 = new gzh();
        gzhVar108.b = "camera.double_tap_launch_edu_enabled";
        aS = gzhVar108.i();
        gzh gzhVar109 = new gzh();
        gzhVar109.b = "use_pck_storage";
        gzhVar109.e();
        gzh gzhVar110 = new gzh();
        gzhVar110.b = "unflipped_selfie_enabled";
        aT = gzhVar110.i();
        gzh gzhVar111 = new gzh();
        gzhVar111.b = "use_physical_raw";
        aU = gzhVar111.i();
        gzh gzhVar112 = new gzh();
        gzhVar112.b = "camera.pck_reprocessing_yuv";
        aV = gzhVar112.i();
        gzh gzhVar113 = new gzh();
        gzhVar113.b = "use_minimal_q_storage_v2";
        gzhVar113.n();
        gzh gzhVar114 = new gzh();
        gzhVar114.b = "camera.no_media_type_none_on_q_or_above";
        aW = gzhVar114.i();
        gzh gzhVar115 = new gzh();
        gzhVar115.b = "use_immersive_rounded_corners";
        aX = gzhVar115.i();
        gzh gzhVar116 = new gzh();
        gzhVar116.b = "camera.ddepth_rear";
        aY = gzhVar116.i();
        gzh gzhVar117 = new gzh();
        gzhVar117.b = "camera.ddepth_front";
        aZ = gzhVar117.i();
        gzh gzhVar118 = new gzh();
        gzhVar118.b = "camera.ddepth_debug";
        gzhVar118.o();
        gzh gzhVar119 = new gzh();
        gzhVar119.b = "camera.ddepth_preference_override";
        ba = gzhVar119.i();
        gzh gzhVar120 = new gzh();
        gzhVar120.b = "camera.ddepth_rear_use_opencl";
        bb = gzhVar120.i();
        gzh gzhVar121 = new gzh();
        gzhVar121.b = "camera.alloc_tracker";
        gzhVar121.m();
        gzh gzhVar122 = new gzh();
        gzhVar122.b = "camera.mediafile_stuck_notification";
        gzhVar122.m();
        gzh gzhVar123 = new gzh();
        gzhVar123.b = "camera.mediafile_stuck_crash";
        gzhVar123.m();
        gzh gzhVar124 = new gzh();
        gzhVar124.b = "camera.custom_hotkeys";
        gzhVar124.e();
        gzh gzhVar125 = new gzh();
        gzhVar125.b = "camera.no_low_fb";
        bc = gzhVar125.i();
        gzh gzhVar126 = new gzh();
        gzhVar126.b = "camera.fb_hcheck";
        gzhVar126.o();
        gzh gzhVar127 = new gzh();
        gzhVar127.b = "camera.log_frame_availability";
        gzhVar127.e();
        gzh gzhVar128 = new gzh();
        gzhVar128.b = "camera.allow_fine_haptics";
        bd = gzhVar128.i();
        gzh gzhVar129 = new gzh();
        gzhVar129.b = "camera.jankmonitor_full";
        gzhVar129.o();
        gzh gzhVar130 = new gzh();
        gzhVar130.b = "camera.laplog";
        be = gzhVar130.i();
        gzh gzhVar131 = new gzh();
        gzhVar131.b = "camera.perfetto_trigger_activity_start_frame_drops";
        u = gzhVar131.a();
        gzh gzhVar132 = new gzh();
        gzhVar132.c(new gyn(11));
        gzhVar132.b = "post_shot_jank_perfetto_trigger_threshold";
        v = gzhVar132.a();
        gzh gzhVar133 = new gzh();
        gzhVar133.c(new gyn(12));
        gzhVar133.b = "failed_launch_perfetto_trigger_threshold_millis";
        w = gzhVar133.a();
        gzh gzhVar134 = new gzh();
        gzhVar134.c(new gyn(13));
        gzhVar134.b = "session_jank_perfetto_trigger_threshold";
        x = gzhVar134.a();
        gzh gzhVar135 = new gzh();
        gzhVar135.d("General", false);
        gzhVar135.b = "svj_threshold_millis";
        y = gzhVar135.a();
        gzh gzhVar136 = new gzh();
        gzhVar136.d("General", false);
        gzhVar136.b = "sst_threshold_millis";
        z = gzhVar136.a();
        gzh gzhVar137 = new gzh();
        gzhVar137.b = "camera.sparrow";
        bf = gzhVar137.i();
        gzh gzhVar138 = new gzh();
        gzhVar138.b = "camera.crash_unknown_thermal_status";
        gzhVar138.n();
        gzh gzhVar139 = new gzh();
        gzhVar139.b = "camera.dots_of_doom";
        gzhVar139.m();
        gzh gzhVar140 = new gzh();
        gzhVar140.b = clFzVRcygwbq.rXOcMMELLvn;
        gzhVar140.m();
        gzh gzhVar141 = new gzh();
        gzhVar141.b = "camera.gl.log_caller_stacktrace";
        gzhVar141.m();
        gzh gzhVar142 = new gzh();
        gzhVar142.b = "camera.gl.log_contexts";
        gzhVar142.m();
        gzh gzhVar143 = new gzh();
        gzhVar143.b = "camera.gl.crash_if_exec_rejected";
        gzhVar143.o();
        gzh gzhVar144 = new gzh();
        gzhVar144.b = "camera.storage_space_override";
        A = gzhVar144.a();
        gzh gzhVar145 = new gzh();
        gzhVar145.b = "camera.jpeg_data_rotation";
        bg = gzhVar145.i();
        gzh gzhVar146 = new gzh();
        gzhVar146.b = "camera.debug_lossless_image";
        gzhVar146.m();
        gzh gzhVar147 = new gzh();
        gzhVar147.b = "test_only_camera_device_disable";
        gzhVar147.e = scn.J(0, 1, 2, 3);
        B = gzhVar147.a();
        gzh gzhVar148 = new gzh();
        gzhVar148.b = "test_only_camera_open_disable";
        gzhVar148.e = scn.J(0, 1, 2, 3);
        C = gzhVar148.a();
        gzh gzhVar149 = new gzh();
        gzhVar149.b = "test_only_camera_id_rear";
        gzhVar149.e = rzm.a(seo.f(-1, 9), rzv.a);
        D = gzhVar149.a();
        gzh gzhVar150 = new gzh();
        gzhVar150.b = "test_only_camera_id_front";
        gzhVar150.e = rzm.a(seo.f(-1, 9), rzv.a);
        E = gzhVar150.a();
        gzh gzhVar151 = new gzh();
        gzhVar151.c(new gyn(14));
        gzhVar151.b = "open_duration_threshold_for_fallback_millis";
        F = gzhVar151.a();
        gzh gzhVar152 = new gzh();
        gzhVar152.b = "camera.thread_throttling";
        bh = gzhVar152.i();
        gzh gzhVar153 = new gzh();
        gzhVar153.c(new gyn(15));
        gzhVar153.b = "enumeration_failures_before_reboot_threshold";
        G = gzhVar153.a();
        gzh gzhVar154 = new gzh();
        gzhVar154.c(new gyn(16));
        gzhVar154.b = TOnSyMaYeslEl.Yui;
        H = gzhVar154.a();
        gzh gzhVar155 = new gzh();
        gzhVar155.c(new gyn(5));
        gzhVar155.b = "fatal_failures_before_reboot_threshold";
        I = gzhVar155.a();
        gzh gzhVar156 = new gzh();
        gzhVar156.c(new gyn(6));
        gzhVar156.b = "fatal_failures_after_reboot_threshold";
        J = gzhVar156.a();
        gzh gzhVar157 = new gzh();
        gzhVar157.b = "fatal_error_tracker_days_to_reset";
        gzhVar157.d("General", false);
        K = gzhVar157.a();
        gzh gzhVar158 = new gzh();
        gzhVar158.b = "fatal_error_dogfood_notification";
        gzhVar158.o();
        gzh gzhVar159 = new gzh();
        gzhVar159.c(new gyn(7));
        gzhVar159.b = "working_camera_fallback_enabled";
        bi = gzhVar159.i();
        gzh gzhVar160 = new gzh();
        gzhVar160.b = "camera.share_preview_analysis";
        gzhVar160.o();
        gzh gzhVar161 = new gzh();
        gzhVar161.b = "camera.viewfinder_yuv";
        gzhVar161.o();
        gzh gzhVar162 = new gzh();
        gzhVar162.c(new gyn(8));
        gzhVar162.b = "support_link";
        bj = gzhVar162.j();
        gzh gzhVar163 = new gzh();
        gzhVar163.b = "camera.naruto";
        gzhVar163.m();
        gzh gzhVar164 = new gzh();
        gzhVar164.b = "camera.analysis.private";
        gzhVar164.o();
        gzh gzhVar165 = new gzh();
        gzhVar165.b = "camera.viewfinder_effect_enabled_photo";
        gzhVar165.o();
        gzh gzhVar166 = new gzh();
        gzhVar166.b = "camera.viewfinder_effect_disabled_photo";
        gzhVar166.o();
        gzh gzhVar167 = new gzh();
        gzhVar167.b = "camera.viewfinder_effect_disabled_night";
        gzhVar167.o();
        gzh gzhVar168 = new gzh();
        gzhVar168.b = "camera.crash_on_invalid_meta_data_from_media_store";
        gzhVar168.m();
        gzh gzhVar169 = new gzh();
        gzhVar169.b = "camera.mediastorage_crash_on_second_publish";
        gzhVar169.o();
        gzh gzhVar170 = new gzh();
        gzhVar170.b = "ideal_aov_rad";
        bk = gzhVar170.h();
        gzh gzhVar171 = new gzh();
        gzhVar171.b = "support_viewfinder_double_tap";
        gzhVar171.d("General", false);
        bl = gzhVar171.i();
        gzh gzhVar172 = new gzh();
        gzhVar172.b = "enable_survey";
        gzhVar172.d("Survey", false);
        gzhVar172.o();
        gzh gzhVar173 = new gzh();
        gzhVar173.b = "camera.enable_dogfood_notifications";
        gzhVar173.o();
        gzh gzhVar174 = new gzh();
        gzhVar174.b = "enable_countdown_indicator";
        bm = gzhVar174.i();
        gzh gzhVar175 = new gzh();
        gzhVar175.b = "enable_mars";
        bn = gzhVar175.i();
        gzh gzhVar176 = new gzh();
        gzhVar176.b = "camera.enable_inapp_update";
        bo = gzhVar176.i();
        gzh gzhVar177 = new gzh();
        gzhVar177.b = "camera.topshotp";
        gzhVar177.o();
        gzh gzhVar178 = new gzh();
        gzhVar178.b = "camera.topshotns";
        gzhVar178.m();
        gzh gzhVar179 = new gzh();
        gzhVar179.b = "camera.enable_request_override";
        gzhVar179.o();
        gzh gzhVar180 = new gzh();
        gzhVar180.b = "camera.enable_sideline";
        bp = gzhVar180.i();
        gzh gzhVar181 = new gzh();
        gzhVar181.b = "photosphere_frame_server_api_enabled";
        gzhVar181.e();
        gzh gzhVar182 = new gzh();
        gzhVar182.b = "camera.pd_dump";
        gzhVar182.m();
        gzh gzhVar183 = new gzh();
        gzhVar183.b = "camera.shot_tracking.crash_when_stuck";
        gzhVar183.o();
        gzh gzhVar184 = new gzh();
        gzhVar184.b = "camera.enable_video_test_animation";
        gzhVar184.o();
        gzh gzhVar185 = new gzh();
        gzhVar185.b = "camera.video_test_animation_renderer_type";
        L = gzhVar185.a();
        gzh gzhVar186 = new gzh();
        gzhVar186.b = "camera.hal_capture_status";
        bq = gzhVar186.i();
        gzh gzhVar187 = new gzh();
        gzhVar187.b = "enable_sensitive_image_rotation";
        br = gzhVar187.i();
        gzh gzhVar188 = new gzh();
        gzhVar188.b = "executor_stats";
        gzhVar188.m();
        gzh gzhVar189 = new gzh();
        gzhVar189.b = "enable_extra_haptic";
        bs = gzhVar189.i();
        gzh gzhVar190 = new gzh();
        gzhVar190.b = "vendor.camera.eis.debug";
        gzhVar190.m();
        gzh gzhVar191 = new gzh();
        gzhVar191.b = "camera.eis_tr_supported";
        bt = gzhVar191.g();
        gzh gzhVar192 = new gzh();
        gzhVar192.b = "camera.sound_pool_with_media_usage";
        gzhVar192.e();
        gzh gzhVar193 = new gzh();
        gzhVar193.b = "camera.active_camera_info";
        gzhVar193.d("General", false);
        gzhVar193.o();
        gzh gzhVar194 = new gzh();
        gzhVar194.b = "camera.policy_check";
        bu = gzhVar194.i();
        gzh gzhVar195 = new gzh();
        gzhVar195.b = "camera.fs_auto_resume";
        gzhVar195.o();
        gzh gzhVar196 = new gzh();
        gzhVar196.b = "camera.enable_autobahn";
        bv = gzhVar196.i();
        gzh gzhVar197 = new gzh();
        gzhVar197.b = "camera.enable_freeway";
        bw = gzhVar197.i();
        gzh gzhVar198 = new gzh();
        gzhVar198.b = "camera.enable_video_flattening";
        bx = gzhVar198.i();
        gzh gzhVar199 = new gzh();
        gzhVar199.b = "camera.enable_autobahn_3a_control";
        by = gzhVar199.i();
        gzh gzhVar200 = new gzh();
        gzhVar200.b = "camera.enable_autobahn_fusion";
        bz = gzhVar200.i();
        gzh gzhVar201 = new gzh();
        gzhVar201.b = "camera.enable_squeak_now";
        gzhVar201.m();
        gzh gzhVar202 = new gzh();
        gzhVar202.b = "camera.enable_medium_res";
        bA = gzhVar202.g();
        gzh gzhVar203 = new gzh();
        gzhVar203.b = "camera.toast_remote_data";
        bB = gzhVar203.g();
        gzh gzhVar204 = new gzh();
        gzhVar204.b = "camera.enable_raw_setting";
        bC = gzhVar204.g();
        gzh gzhVar205 = new gzh();
        gzhVar205.b = "camera.enable_hollywood_timer";
        bD = gzhVar205.i();
        gzh gzhVar206 = new gzh();
        gzhVar206.b = "enable_init_executor_reroute";
        gzhVar206.d("General", false);
        gzhVar206.o();
        gzh gzhVar207 = new gzh();
        gzhVar207.b = "init_executor_reroute_time_millis";
        gzhVar207.d("General", false);
        M = gzhVar207.a();
        gzh gzhVar208 = new gzh();
        gzhVar208.b = "shutter_blocked_time_threshold_millis";
        gzhVar208.d("General", false);
        N = gzhVar208.a();
        gzh gzhVar209 = new gzh();
        gzhVar209.b = "camera.libyuv_utils";
        bE = gzhVar209.i();
        gzh gzhVar210 = new gzh();
        gzhVar210.b = "camera.prewarm_viewfinder_surfaceview";
        bF = gzhVar210.i();
        gzh gzhVar211 = new gzh();
        gzhVar211.b = "camera.gate_activity_controller_init";
        bG = gzhVar211.g();
        gzh gzhVar212 = new gzh();
        gzhVar212.b("General");
        gzhVar212.b = "camera_close_on_pause";
        bH = gzhVar212.i();
        gzh gzhVar213 = new gzh();
        gzhVar213.c(new gyn(9));
        gzhVar213.b = "first_ps_flag";
        bI = gzhVar213.i();
        gzh gzhVar214 = new gzh();
        gzhVar214.b = "camera.enable_gm3_settings";
        gzhVar214.e();
        gzh gzhVar215 = new gzh();
        gzhVar215.c(new gyn(10));
        gzhVar215.b = "camera.enable_pathfinder";
        bJ = gzhVar215.i();
        gzh gzhVar216 = new gzh();
        gzhVar216.b = "camera.enable_video_quick_options_pathfinder";
        gzhVar216.o();
    }
}
