package defpackage;

import com.google.android.apps.camera.jni.facebeautification.GFS.CZAHo;
import com.google.android.gms.wearable.aXYS.zflNUOOzDfM;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gzp {
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = zflNUOOzDfM.xdptOh;
        k = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.serengeti_raw_gyro";
        gzhVar2.m();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.serengeti_ns_duration";
        a = gzhVar3.a();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.serengeti_save_debug";
        gzhVar4.e();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.serengeti_hyperfocal";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.serengeti_ans";
        l = gzhVar6.i();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.serengeti_free_awb";
        gzhVar7.m();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.serengeti_preview_downsample";
        b = gzhVar8.a();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.serengeti_free_ans";
        gzhVar9.m();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.serengeti_lock_ae";
        gzhVar10.m();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.serengeti_num_targets";
        c = gzhVar11.a();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = CZAHo.HddrGuFLgBLa;
        d = gzhVar12.a();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.serengeti_full_res";
        m = gzhVar13.i();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.serengeti_downsample_factor";
        n = gzhVar14.h();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.serengeti_delay";
        e = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.serengeti_delay_ans";
        f = gzhVar16.a();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.serengeti_log_debug";
        gzhVar17.d("Serengeti", false);
        o = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.serengeti_enable_pd";
        gzhVar18.m();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.serengeti_focus";
        gzhVar19.m();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.serengeti_zoom";
        gzhVar20.o();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.serengeti_uw";
        gzhVar21.m();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.serengeti_enable_dual_ev";
        gzhVar22.o();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.serengeti_ark_focus";
        gzhVar23.o();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.serengeti_fp16";
        gzhVar24.o();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.serengeti_enable_bento";
        gzhVar25.m();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.serengeti_disk_cache";
        gzhVar26.m();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.serengeti_tracker_smoothing_factor";
        g = gzhVar27.a();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.serengeti_ois_threshold";
        h = gzhVar28.a();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.serengeti_ois_smoothing_factor";
        i = gzhVar29.a();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.serengeti_ois_delay";
        j = gzhVar30.a();
    }
}
