package defpackage;

import androidx.coordinatorlayout.widget.pcp.OPuAVreQM;
import com.bumptech.glide.qd.MyBPCgKwEjJI;
import com.google.android.apps.camera.focusindicator.CIAk.YyLACfm;
import com.google.android.apps.camera.jni.gxp.Caan.yoGAhrpjU;
import com.google.android.apps.camera.toast.vvJ.CGlJpiVWrCQOq;
import com.google.android.apps.camera.ui.hotshot.yElM.PNlJufQ;
import com.google.android.clockwork.common.wearable.wearmaterial.progressindicator.XlTc.IQwwK;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gzs {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final gzg W;
    public static final gzg X;
    public static final gzg Y;
    public static final gzg Z;
    public static final gzi a;
    public static final gzg aA;
    public static final gzg aB;
    public static final gzg aC;
    public static final gzg aD;
    public static final gzg aE;
    public static final gzg aF;
    public static final gzg aG;
    public static final gzg aH;
    public static final gzg aI;
    public static final gzg aJ;
    public static final gzg aK;
    public static final gzg aL;
    public static final gzg aM;
    public static final gzg aN;
    public static final gzg aO;
    public static final gzg aP;
    public static final gzg aQ;
    public static final gzg aR;
    public static final gzg aS;
    public static final gzg aT;
    public static final gzg aU;
    public static final gzg aV;
    public static final gzg aa;
    public static final gzg ab;
    public static final gzg ac;
    public static final gzg ad;
    public static final gzg ae;
    public static final gzg af;
    public static final gzg ag;
    public static final gzg ah;
    public static final gzg ai;
    public static final gzg aj;
    public static final gzg ak;
    public static final gzg al;
    public static final gzg am;
    public static final gzg an;
    public static final gzg ao;
    public static final gzg ap;
    public static final gzg aq;
    public static final gzg ar;
    public static final gzg as;
    public static final gzg at;
    public static final gzg au;
    public static final gzg av;
    public static final gzg aw;
    public static final gzg ax;
    public static final gzg ay;
    public static final gzg az;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzi k;
    public static final gzi l;
    public static final gzi m;
    public static final gzi n;
    public static final gzi o;
    public static final gzi p;
    public static final gzi q;
    public static final gzi r;
    public static final gzi s;
    public static final gzi t;
    public static final gzi u;
    public static final gzi v;
    public static final gzi w;
    public static final gzi x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.3a.debug_meta";
        gzhVar.e = scn.J(Integer.valueOf(gzr.OFF.ordinal()), Integer.valueOf(gzr.PERIODIC.ordinal()), Integer.valueOf(gzr.ALL.ordinal()), Integer.valueOf(gzr.SHUTTER_ASAP.ordinal()));
        a = gzhVar.a();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.3a.debug_meta_all";
        gzhVar2.o();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.3a.debug_meta_xmp";
        y = gzhVar3.i();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.3a.debug_meta_last_frame";
        z = gzhVar4.i();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.3a.debug_exclusive_fs_session";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.3a_conv";
        A = gzhVar6.i();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.extburst.RESTART";
        gzhVar7.e();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "gcam.hdrplus_wb_source";
        gzhVar8.e = scn.J(0, 1, 2, 3);
        b = gzhVar8.a();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "gcam.psaf_frame_count";
        gzhVar9.e = rzm.a(seo.f(0, 10), rzv.a);
        c = gzhVar9.a();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = OPuAVreQM.nuaBoyxu;
        B = gzhVar10.h();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "gcam.psaf_sb_thresh";
        C = gzhVar11.h();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "gcam.zsl_buffer_size";
        d = gzhVar12.a();
        gzh gzhVar13 = new gzh();
        gzhVar13.d("HdrPlus", false);
        gzhVar13.b = "camera_hdr_gxp_restart_remote";
        D = gzhVar13.i();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.hdr_gxp.RESTART";
        E = gzhVar14.i();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "gcam.max_burst_size";
        e = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.p3_available";
        F = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.p3_force";
        gzhVar17.e();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.p3_default";
        G = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.enable_eevee_all";
        H = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.enable_eevee_layla";
        I = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.enable_eevee_skyla";
        J = gzhVar21.i();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.shasta_psl";
        K = gzhVar22.i();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.shasta_zsl";
        L = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.shasta.frame_retention_ms";
        f = gzhVar24.a();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.shasta.force";
        gzhVar25.o();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.shasta.factor";
        M = gzhVar26.h();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.post_zsl_capture_burst_size";
        g = gzhVar27.a();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.shasta_zsl.max_exptime_ms";
        N = gzhVar28.h();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = CGlJpiVWrCQOq.oKfMNN;
        h = gzhVar29.a();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.lancet_enabled";
        O = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.lancet_model_asset_name";
        P = gzhVar31.j();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.lancet_dsp_enabled";
        Q = gzhVar32.i();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.kepler_v1_enabled";
        R = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.kepler_v1_model_asset_name";
        S = gzhVar34.j();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.update_min_zoom_for_ml_upscalers";
        T = gzhVar35.g();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.spatial_rgb_enabled";
        U = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.spatial_rgb_force";
        gzhVar37.e();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.wiener_force";
        V = gzhVar38.i();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.slowraw";
        gzhVar39.e();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.slowraw.continuous";
        gzhVar40.e();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.slowraw.continuous_bursts";
        i = gzhVar41.a();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.flash_animation_experiment";
        gzhVar42.e();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.flash_anim_fade_in_ms";
        j = gzhVar43.a();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.flash_anim_fade_out_ms";
        k = gzhVar44.a();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.flash_anim_max_alpha";
        W = gzhVar45.h();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.force_low_light_fps";
        gzhVar46.e();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "gcam.live_tb";
        X = gzhVar47.i();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.uw_binning_supported";
        Y = gzhVar48.g();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "gcam.live_tb.forcedtbfactor";
        l = gzhVar49.a();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "gcam.live_tb.brightness_threshold";
        Z = gzhVar50.h();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "hdrnet_enabled";
        aa = gzhVar51.i();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camera.hdrnet.height";
        m = gzhVar52.a();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera.hdrnet.hi-res";
        ab = gzhVar53.i();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera.nonzsl_extended_base_frame_selection";
        ac = gzhVar54.f();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "gcam.vf.verbose";
        gzhVar55.e();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "camera.zsl.extended_buffer_factor";
        ad = gzhVar56.h();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "camera.oriana_enabled";
        ae = gzhVar57.i();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "camera.oriana_in_threshold";
        af = gzhVar58.h();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "camera.oriana_out_threshold";
        ag = gzhVar59.h();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camera.oriana_reengage_threshold";
        ah = gzhVar60.h();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camera.disable_hdrplus_postview";
        ai = gzhVar61.i();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camera.disable_hdrplus_postview_psl";
        gzhVar62.o();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = "camera.bento_enabled";
        aj = gzhVar63.i();
        gzh gzhVar64 = new gzh();
        gzhVar64.b = "camera.bento_max_shot_capture_time_ms";
        ak = gzhVar64.h();
        gzh gzhVar65 = new gzh();
        gzhVar65.d("HdrPlus", false);
        gzhVar65.b = "bento_use_separable_merge";
        al = gzhVar65.i();
        gzh gzhVar66 = new gzh();
        gzhVar66.b = "camera.bento_use_separable_merge";
        am = gzhVar66.i();
        gzh gzhVar67 = new gzh();
        gzhVar67.b = "camera.bento_first";
        gzhVar67.o();
        gzh gzhVar68 = new gzh();
        gzhVar68.b = "camera.bento_tet_factor";
        gzhVar68.l();
        gzh gzhVar69 = new gzh();
        gzhVar69.b = "camera.bento_force_apply";
        gzhVar69.o();
        gzh gzhVar70 = new gzh();
        gzhVar70.b = "camera.bento_annotate_final_image";
        gzhVar70.o();
        gzh gzhVar71 = new gzh();
        gzhVar71.b = "camera.hdr_plus_torch_thermal_throttling";
        an = gzhVar71.i();
        gzh gzhVar72 = new gzh();
        gzhVar72.b = "camera.gpu_sampled_image";
        ao = gzhVar72.i();
        gzh gzhVar73 = new gzh();
        gzhVar73.b = "camera.include_ultra_short_frame";
        ap = gzhVar73.i();
        gzh gzhVar74 = new gzh();
        gzhVar74.b = "camera.include_dropped_bracketing_frame";
        gzhVar74.n();
        gzh gzhVar75 = new gzh();
        gzhVar75.b = "gcam.metering.recompute_ae";
        aq = gzhVar75.i();
        gzh gzhVar76 = new gzh();
        gzhVar76.b = "gcam.front_ae_motion_options";
        ar = gzhVar76.i();
        gzh gzhVar77 = new gzh();
        gzhVar77.b = MyBPCgKwEjJI.JlNH;
        as = gzhVar77.i();
        gzh gzhVar78 = new gzh();
        gzhVar78.b = "gcam.ts_base";
        at = gzhVar78.i();
        gzh gzhVar79 = new gzh();
        gzhVar79.b = "camera.pecan_enabled";
        au = gzhVar79.i();
        gzh gzhVar80 = new gzh();
        gzhVar80.b = "camera.pecan_pie_enabled";
        av = gzhVar80.i();
        gzh gzhVar81 = new gzh();
        gzhVar81.b = "camera.pecan_override";
        gzhVar81.e = scn.K(0, 1, 2, 3, 4);
        n = gzhVar81.a();
        gzh gzhVar82 = new gzh();
        gzhVar82.b = "camera.pecan_model_asset_name";
        aw = gzhVar82.j();
        gzh gzhVar83 = new gzh();
        gzhVar83.b = "camera.pecan_light_model_asset_name";
        ax = gzhVar83.j();
        gzh gzhVar84 = new gzh();
        gzhVar84.b = "camera.pecan_pie_model_asset_name";
        ay = gzhVar84.j();
        gzh gzhVar85 = new gzh();
        gzhVar85.b = "camera.pecan_dedicated_ns_only";
        az = gzhVar85.i();
        gzh gzhVar86 = new gzh();
        gzhVar86.b = "camera.pecan_light_mode_enabled";
        aA = gzhVar86.i();
        gzh gzhVar87 = new gzh();
        gzhVar87.b = "camera.low_payload_threshold";
        o = gzhVar87.a();
        gzh gzhVar88 = new gzh();
        gzhVar88.b = "gcam.gpu_power_boost_enabled";
        gzhVar88.o();
        gzh gzhVar89 = new gzh();
        gzhVar89.b = PNlJufQ.QQcgX;
        aB = gzhVar89.i();
        gzh gzhVar90 = new gzh();
        gzhVar90.b = "gcam.pistachio_enabled";
        gzhVar90.o();
        gzh gzhVar91 = new gzh();
        gzhVar91.b = "gcam.hawk_boost_big_option";
        aC = gzhVar91.h();
        gzh gzhVar92 = new gzh();
        gzhVar92.b = "gcam.hawk_boost_mid_option";
        aD = gzhVar92.h();
        gzh gzhVar93 = new gzh();
        gzhVar93.b = "gcam.hawk_boost_little_option";
        aE = gzhVar93.h();
        gzh gzhVar94 = new gzh();
        gzhVar94.b = "gcam.use_hardware_jpeg_encoder";
        aF = gzhVar94.i();
        gzh gzhVar95 = new gzh();
        gzhVar95.b = "gcam.jpeg_compression_boost_big_option";
        aG = gzhVar95.h();
        gzh gzhVar96 = new gzh();
        gzhVar96.b = yoGAhrpjU.yLyFTnFsikrtoqp;
        aH = gzhVar96.h();
        gzh gzhVar97 = new gzh();
        gzhVar97.b = "gcam.jpeg_compression_boost_little_option";
        aI = gzhVar97.h();
        gzh gzhVar98 = new gzh();
        gzhVar98.d("HdrPlus", false);
        gzhVar98.b = "jpeg_compression_cpu_affinity_mask";
        p = gzhVar98.a();
        gzh gzhVar99 = new gzh();
        gzhVar99.b = "gcam.jpeg_compression_cpu_affinity_mask";
        q = gzhVar99.a();
        gzh gzhVar100 = new gzh();
        gzhVar100.b = "gcam.walnut_enabled";
        aJ = gzhVar100.i();
        gzh gzhVar101 = new gzh();
        gzhVar101.b = yoGAhrpjU.zwukzOBfh;
        aK = gzhVar101.i();
        gzh gzhVar102 = new gzh();
        gzhVar102.b = "gcam.walnut_model_asset_name";
        aL = gzhVar102.j();
        gzh gzhVar103 = new gzh();
        gzhVar103.b = "camera.almond_enabled";
        aM = gzhVar103.i();
        gzh gzhVar104 = new gzh();
        gzhVar104.b = "camera.almond_model_asset_name";
        aN = gzhVar104.j();
        gzh gzhVar105 = new gzh();
        gzhVar105.b = "camera.almond_force_apply_limited_by_times";
        gzhVar105.o();
        gzh gzhVar106 = new gzh();
        gzhVar106.b = "camera.mochi_enabled";
        gzhVar106.o();
        gzh gzhVar107 = new gzh();
        gzhVar107.b = "camera.mochi_force_apply";
        gzhVar107.o();
        gzh gzhVar108 = new gzh();
        gzhVar108.b = "camera.mst_based_ce_enabled";
        gzhVar108.o();
        gzh gzhVar109 = new gzh();
        gzhVar109.b = "camera.hdr_memory_reserve";
        aO = gzhVar109.i();
        gzh gzhVar110 = new gzh();
        gzhVar110.b = "slow_hdr_plus_capture_latency_threshold";
        gzhVar110.d("HdrPlus", false);
        r = gzhVar110.a();
        gzh gzhVar111 = new gzh();
        gzhVar111.b = "slow_shot_perfetto_trigger";
        gzhVar111.d("HdrPlus", false);
        gzhVar111.e();
        gzh gzhVar112 = new gzh();
        gzhVar112.b = "gcam.hazelnut_enabled";
        aP = gzhVar112.i();
        gzh gzhVar113 = new gzh();
        gzhVar113.d("HdrPlus", false);
        gzhVar113.b = "eager_simultaneous_merge_and_finish_remote";
        aQ = gzhVar113.f();
        gzh gzhVar114 = new gzh();
        gzhVar114.b = "gcam.eager_simultaneous_merge_and_finish";
        aR = gzhVar114.f();
        gzh gzhVar115 = new gzh();
        gzhVar115.b = "camera.ghawb_clut_control_enabled";
        gzhVar115.o();
        gzh gzhVar116 = new gzh();
        gzhVar116.b = "camera.ghawb_clut_product_class";
        gzhVar116.l();
        gzh gzhVar117 = new gzh();
        gzhVar117.b = "camera.ghawb_clut_available_cameras";
        s = gzhVar117.a();
        gzh gzhVar118 = new gzh();
        gzhVar118.b = "gcam.spatial_merge_processor_error_fallback";
        aS = gzhVar118.f();
        gzh gzhVar119 = new gzh();
        gzhVar119.b = "gcam.brazil_nut_enabled";
        aT = gzhVar119.i();
        gzh gzhVar120 = new gzh();
        gzhVar120.b = "camera.legacy_pre_slm";
        aU = gzhVar120.i();
        gzh gzhVar121 = new gzh();
        gzhVar121.b = "camera.use_eclipse";
        gzhVar121.o();
        gzh gzhVar122 = new gzh();
        gzhVar122.b = "camera.gcam_enable_thread_priority";
        gzhVar122.m();
        gzh gzhVar123 = new gzh();
        gzhVar123.b = "camera.gcam_trace_image_lifetime";
        gzhVar123.o();
        gzh gzhVar124 = new gzh();
        gzhVar124.b = "camera.native_metadata_converter";
        gzhVar124.m();
        gzh gzhVar125 = new gzh();
        gzhVar125.c(new gyn(18));
        gzhVar125.b = "camera.pollux";
        gzhVar125.o();
        gzh gzhVar126 = new gzh();
        gzhVar126.b = "camera.pollux_force";
        gzhVar126.o();
        gzh gzhVar127 = new gzh();
        gzhVar127.b = "camera.pollux_ticket_threshold";
        t = gzhVar127.a();
        gzh gzhVar128 = new gzh();
        gzhVar128.b = "camera.pollux_disk_space_mb_threshold";
        u = gzhVar128.a();
        gzh gzhVar129 = new gzh();
        gzhVar129.b = "camera.pollux_disk_health_threshold";
        v = gzhVar129.a();
        gzh gzhVar130 = new gzh();
        gzhVar130.b = "camera.pollux_use_wb";
        gzhVar130.o();
        gzh gzhVar131 = new gzh();
        gzhVar131.b = IQwwK.ezJFMyyabSLfD;
        w = gzhVar131.a();
        gzh gzhVar132 = new gzh();
        gzhVar132.b = "camera.pollux_wb_health_threshold";
        x = gzhVar132.a();
        gzh gzhVar133 = new gzh();
        gzhVar133.b = "camera.pollux_ignore_disk_health";
        gzhVar133.o();
        gzh gzhVar134 = new gzh();
        gzhVar134.b = "camera.pollux_ignore_wb";
        gzhVar134.o();
        gzh gzhVar135 = new gzh();
        gzhVar135.b = "camera.roshi_wide";
        aV = gzhVar135.i();
        gzh gzhVar136 = new gzh();
        gzhVar136.b = "camera.always_check_metadata_converters_id";
        gzhVar136.m();
        gzh gzhVar137 = new gzh();
        gzhVar137.b = "camera.sometimes_check_metadata_converters_id";
        gzhVar137.m();
        gzh gzhVar138 = new gzh();
        gzhVar138.b = "gcam.af_roi_sharpness_enabled";
        gzhVar138.m();
    }

    public static void a(hbj hbjVar) {
        hbjVar.d(a, Integer.valueOf(gzr.SHUTTER_ASAP.ordinal()));
        hbjVar.l(z, true);
        hbjVar.l(y, true);
        hbjVar.d(b, 2);
        hbjVar.d(c, 2);
        hbjVar.k(B, null);
        hbjVar.k(C, null);
        hbjVar.l(D, true);
        hbjVar.l(E, true);
        hbjVar.d(e, 7);
        hbjVar.d(d, 9);
        hbjVar.l(F, true);
        hbjVar.l(G, false);
        hbjVar.l(K, true);
        hbjVar.l(L, true);
        hbjVar.k(M, null);
        hbjVar.d(g, null);
        hbjVar.d(f, null);
        hbjVar.k(N, Float.valueOf(66.666664f));
        hbjVar.d(h, -1);
        hbjVar.l(O, false);
        gzg gzgVar = P;
        String str = YyLACfm.qUBHAyKxlG;
        hbjVar.m(gzgVar, str);
        hbjVar.l(R, false);
        hbjVar.m(S, str);
        hbjVar.j(T, false);
        hbjVar.l(Q, false);
        hbjVar.l(U, true);
        hbjVar.l(V, false);
        hbjVar.d(i, 20);
        hbjVar.l(X, true);
        hbjVar.d(l, -1);
        hbjVar.k(Z, Float.valueOf(-0.5f));
        hbjVar.l(aa, true);
        hbjVar.d(m, 768);
        hbjVar.l(ab, false);
        hbjVar.i(ac);
        hbjVar.l(A, true);
        hbjVar.k(ad, Float.valueOf(1.0f));
        hbjVar.d(j, 66);
        hbjVar.d(k, 166);
        hbjVar.k(W, Float.valueOf(0.76f));
        hbjVar.l(ai, true);
        hbjVar.l(ae, false);
        hbjVar.k(af, Float.valueOf(-2.0f));
        hbjVar.k(ag, Float.valueOf(-3.21f));
        hbjVar.k(ah, Float.valueOf(-3.18f));
        hbjVar.l(an, true);
        hbjVar.l(ao, true);
        hbjVar.l(ap, true);
        hbjVar.l(aq, false);
        hbjVar.l(as, true);
        hbjVar.l(at, false);
        hbjVar.d(o, -1);
        hbjVar.l(au, false);
        hbjVar.l(av, false);
        hbjVar.m(aw, str);
        hbjVar.m(ax, str);
        hbjVar.m(ay, str);
        hbjVar.d(n, 0);
        hbjVar.l(az, false);
        hbjVar.l(aA, false);
        gzg gzgVar2 = aC;
        Float fValueOf = Float.valueOf(0.0f);
        hbjVar.k(gzgVar2, fValueOf);
        hbjVar.k(aD, fValueOf);
        gzg gzgVar3 = aE;
        Float fValueOf2 = Float.valueOf(-1.0f);
        hbjVar.k(gzgVar3, fValueOf2);
        hbjVar.l(aF, false);
        hbjVar.k(aG, fValueOf2);
        hbjVar.k(aH, fValueOf2);
        hbjVar.k(aI, fValueOf2);
        hbjVar.d(p, 0);
        hbjVar.d(q, 0);
        hbjVar.l(aJ, true);
        hbjVar.l(aK, true);
        hbjVar.m(aL, str);
        hbjVar.l(aM, false);
        hbjVar.m(aN, str);
        hbjVar.l(aB, true);
        hbjVar.l(aO, false);
        hbjVar.l(aP, true);
        hbjVar.d(r, 10000);
        hbjVar.l(H, false);
        hbjVar.l(I, false);
        hbjVar.l(J, false);
        hbjVar.i(aQ);
        hbjVar.i(aR);
        hbjVar.l(aj, false);
        hbjVar.k(ak, fValueOf2);
        hbjVar.l(al, true);
        hbjVar.l(am, true);
        hbjVar.d(s, 0);
        hbjVar.i(aS);
        hbjVar.l(aT, true);
        hbjVar.l(aU, false);
        hbjVar.j(Y, true);
        hbjVar.d(t, 18);
        hbjVar.d(u, 200);
        hbjVar.d(v, 40);
        hbjVar.d(w, 200);
        hbjVar.d(x, 40);
        hbjVar.l(aV, false);
        hbjVar.l(ar, true);
    }
}
