package defpackage;

import androidx.coordinatorlayout.widget.pcp.OPuAVreQM;
import com.google.android.apps.camera.toast.vvJ.CGlJpiVWrCQOq;
import com.google.android.gms.analytics.EQvQ.UvOvSgfD;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class gzz {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzg d;
    public static final gzg e;
    public static final gzg f;
    public static final gzg g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.micro_datacoll";
        gzhVar.e();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.micro_fragmented";
        gzhVar2.e();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.enable_jpgcheck";
        gzhVar3.o();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.micro_cam_pose";
        gzhVar4.n();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.micro_creation";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.micro_no_gyro";
        gzhVar6.e();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.enable_micro_he";
        d = gzhVar7.i();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.micro_longp_hires";
        gzhVar8.e();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.micro_longp_md";
        e = gzhVar9.i();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.micro_longp_pre_audio";
        gzhVar10.o();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.micro_motion";
        f = gzhVar11.i();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.micro_motion_v2";
        g = gzhVar12.i();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.micro_profile";
        gzhVar13.e();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.micro_tone_map";
        h = gzhVar14.g();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.micro_tooltip";
        i = gzhVar15.f();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.micro_trimtoast";
        gzhVar16.e();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.enable_micro";
        j = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "micro_video_supported";
        k = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.micro_prestab";
        l = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.micro_v2_format";
        m = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = CGlJpiVWrCQOq.iPkAXXMhNLjX;
        gzhVar21.e();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.mv_dump_yuv";
        gzhVar22.e();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.mv_verbose";
        gzhVar23.e();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = OPuAVreQM.uKjjAPJujciJSGE;
        n = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.micro_stab_locked";
        gzhVar25.e();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.micro_render_stab_mesh";
        gzhVar26.e();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.micro_longp_slide";
        o = gzhVar27.i();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.longp_topshot_indicator";
        p = gzhVar28.i();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.longp_zoom_lock";
        q = gzhVar29.i();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.longp_top_shot_animation";
        a = gzhVar30.a();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.micro_debug_trimmer";
        gzhVar31.e();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.micro_overlay_metrics";
        gzhVar32.e();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.micro_bottom_sheet";
        r = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.motion_photo_bottom_sheet";
        s = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.micro_ls_always_prestab";
        t = gzhVar35.i();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.micro_longp_help";
        u = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.longp_topshot_notification";
        v = gzhVar37.i();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.micro_dynamic_i";
        gzhVar38.o();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.direct_encode";
        w = gzhVar39.i();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.micro_full_color_range";
        x = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.micro_newtrimmer";
        gzhVar41.o();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = UvOvSgfD.NQcn;
        y = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.r_pending_vids";
        z = gzhVar43.i();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.check_pending_vids";
        A = gzhVar44.i();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.micro_ls_cthreshold";
        b = gzhVar45.a();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.ls_on_mash";
        gzhVar46.m();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.mv_eis_gyro_thr";
        gzhVar47.o();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.mv_tt";
        B = gzhVar48.i();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.mv_tt_level";
        c = gzhVar49.a();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camera.mv_force_auto_for_testing";
        gzhVar50.o();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camera.mv_proc_longer";
        gzhVar51.m();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camera.default_topshot_off";
        C = gzhVar52.i();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera.default_motion_photo_off";
        D = gzhVar53.i();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera.mv_trigger_low_zoom";
        E = gzhVar54.i();
    }
}
