package defpackage;

import com.google.android.apps.camera.debug.metrics.CYLp.GdpuLBytnYW;
import com.google.android.apps.camera.ui.zoomlock.Gx.nWEkBGOQPWQp;
import com.google.android.build.data.JKx.wzgaYJqO;
import com.google.android.libraries.oliveoil.natives.TtaZ.VnmwoBe;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class haa {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final gzg W;
    public static final gzg X;
    public static final gzg Y;
    public static final gzg Z;
    public static final gzi a;
    public static final gzg aa;
    public static final gzg ab;
    public static final gzg ac;
    public static final gzg ad;
    public static final gzg ae;
    public static final gzg af;
    public static final gzg ag;
    public static final gzg ah;
    public static final gzg ai;
    public static final gzg aj;
    public static final gzg ak;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzg f;
    public static final gzg g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.d("Topshot", false);
        gzhVar.b = "camera_mts_aesthetic";
        f = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.d("Topshot", false);
        gzhVar2.b = "camera_mts_actions_front";
        g = gzhVar2.i();
        gzh gzhVar3 = new gzh();
        gzhVar3.d("Topshot", false);
        gzhVar3.b = "camera_mts_actions_back";
        h = gzhVar3.i();
        gzh gzhVar4 = new gzh();
        gzhVar4.d("Topshot", false);
        gzhVar4.b = "camera_mts_face_interactions";
        i = gzhVar4.i();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.mts_accel_faces_front";
        j = gzhVar5.i();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.mts_accel_faces_back";
        k = gzhVar6.i();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.mts_accel_action_front";
        l = gzhVar7.i();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.mts_accel_action_back";
        m = gzhVar8.i();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.mts_smartcapturenet_enable";
        n = gzhVar9.i();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.mts_smartcapturenet_2";
        o = gzhVar10.i();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.mts_pose";
        p = gzhVar11.i();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.mts_pose_and_pet";
        q = gzhVar12.i();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.mts_sc_accel_tpu";
        r = gzhVar13.i();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.mts_4k";
        s = gzhVar14.i();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.mts_ls_dupe_last";
        t = gzhVar15.i();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.mts_ts_ls_dupe_last";
        u = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.mts_fc_extraction";
        gzhVar17.o();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.mts_smart_zoom";
        v = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.mts_hgd";
        w = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.mts_scoring_dbg";
        gzhVar20.o();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.mts_postview";
        x = gzhVar21.f();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.mts_reprocess";
        y = gzhVar22.i();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = wzgaYJqO.cFYCC;
        z = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.mts_fast_hdr";
        A = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.mts_fast_de_ts";
        gzhVar25.o();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.mts_fast_de_ls";
        B = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.mts_ts_de_d2x";
        gzhVar27.o();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.mts_ls_de_d2x";
        C = gzhVar28.i();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.mts_alt_w_main";
        gzhVar29.e();
        gzh gzhVar30 = new gzh();
        gzhVar30.d("Topshot", false);
        gzhVar30.b = "mts_max_alt_1";
        D = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.mts_max_alt_1";
        E = gzhVar31.i();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.non_face_mts_max_alt";
        a = gzhVar32.a();
        gzh gzhVar33 = new gzh();
        gzhVar33.d("Topshot", false);
        gzhVar33.b = "camera_mts_lowlight_or_zoom";
        F = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.mts_postproc";
        G = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.mts_gpu";
        H = gzhVar35.i();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.mts_hw_enc_w";
        I = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.d("Topshot", false);
        gzhVar37.b = "mts_face_diversity";
        J = gzhVar37.i();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.mts_face_diversity";
        K = gzhVar38.i();
        gzh gzhVar39 = new gzh();
        gzhVar39.d("Topshot", false);
        gzhVar39.b = "mts_aesthetic_diversity";
        L = gzhVar39.i();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.mts_aesthetic_diversity";
        M = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.d("Topshot", false);
        gzhVar41.b = GdpuLBytnYW.NTlZwiZLSuHtTL;
        N = gzhVar41.i();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.mts_long_shot_diversity";
        O = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.mts_nima_aesthetic_tpu";
        P = gzhVar43.i();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.mts_enable_nima_v2";
        Q = gzhVar44.i();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.mts_motion_photo_threshold";
        R = gzhVar45.i();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.mts_durfix_ls";
        S = gzhVar46.i();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.mts_durfix_ts";
        T = gzhVar47.i();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.mts_new_topshot_weight";
        U = gzhVar48.i();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.mts_wait_ef";
        V = gzhVar49.i();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camera.mts_full_res";
        gzhVar50.o();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camera.mts_full_br";
        gzhVar51.o();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = VnmwoBe.WpoVNmZknxVzn;
        W = gzhVar52.i();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "disable_mts_full_res_ls";
        gzhVar53.d("Topshot", false);
        X = gzhVar53.i();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = nWEkBGOQPWQp.mKBmMlK;
        gzhVar54.o();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camera.mts_12mp_ls";
        Y = gzhVar55.i();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "camera.mts_scoring_rate_limiting";
        Z = gzhVar56.i();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "camera.mts_full_br_ls";
        aa = gzhVar57.i();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "camera.mts_full_color_range";
        ab = gzhVar58.i();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "camera.mts_func_encoder";
        ac = gzhVar59.i();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camera.mts_encoder_pq";
        gzhVar60.o();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camera.mts_pq_min";
        b = gzhVar61.a();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camera.mts_pq_max";
        c = gzhVar62.a();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = "camera.mts_prewarm";
        ad = gzhVar63.f();
        gzh gzhVar64 = new gzh();
        gzhVar64.b = "camera.mts_kuafu";
        ae = gzhVar64.i();
        gzh gzhVar65 = new gzh();
        gzhVar65.b = "camera.mts_gpu_yuv";
        af = gzhVar65.i();
        gzh gzhVar66 = new gzh();
        gzhVar66.b = "camera.mts_early_first_alt";
        gzhVar66.e();
        gzh gzhVar67 = new gzh();
        gzhVar67.b = "camera.mts_newscore";
        ag = gzhVar67.i();
        gzh gzhVar68 = new gzh();
        gzhVar68.b = "camera.longshot_xtra_frames";
        ah = gzhVar68.i();
        gzh gzhVar69 = new gzh();
        gzhVar69.b = "camera.longshot_lazy_proc";
        ai = gzhVar69.i();
        gzh gzhVar70 = new gzh();
        gzhVar70.b = "camera.mts_direct_encode";
        gzhVar70.o();
        gzh gzhVar71 = new gzh();
        gzhVar71.b = "camera.mts_lite";
        gzhVar71.o();
        gzh gzhVar72 = new gzh();
        gzhVar72.b = "camera.mts_face_attributes_batch_size";
        d = gzhVar72.a();
        gzh gzhVar73 = new gzh();
        gzhVar73.b = "camera.mts_ts_bitrate";
        e = gzhVar73.a();
        gzh gzhVar74 = new gzh();
        gzhVar74.b = "camera.mts_dynamic_topshot_INFERENCE";
        aj = gzhVar74.i();
        gzh gzhVar75 = new gzh();
        gzhVar75.b = "camera.mts_1_fps";
        gzhVar75.o();
        gzh gzhVar76 = new gzh();
        gzhVar76.b = "camera.mts_tm_encoder";
        ak = gzhVar76.i();
        gzh gzhVar77 = new gzh();
        gzhVar77.b = "camera.mts_save_no_tm";
        gzhVar77.e();
        gzh gzhVar78 = new gzh();
        gzhVar78.b = "camera.mts_ls_reprocess";
        gzhVar78.o();
    }
}
