package defpackage;

import com.google.googlex.gcam.creativecamera.portraitmode.axeo.pAAtrB;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hac {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzi k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.enable_cuttlef";
        l = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "total_exposure_threshold_front";
        m = gzhVar2.h();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "total_exposure_threshold_rear";
        n = gzhVar3.h();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.promote_night_sight";
        o = gzhVar4.i();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.cuttle.sky_eager_init";
        p = gzhVar5.i();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.cuttlefish_bone";
        q = gzhVar6.i();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.cuttlefish_bone_cancel";
        gzhVar7.m();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.cuttlefish_bone_abort_min_capture_ms";
        a = gzhVar8.a();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.cuttlefish_bone_timeout_ms";
        b = gzhVar9.a();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.cuttlefish_bone_force_capture_animation";
        gzhVar10.o();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.cuttle.max_burst_size";
        c = gzhVar11.a();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.catfish_enabled";
        r = gzhVar12.i();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.catfish.debug";
        gzhVar13.e();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "camera.catfish.max_frames";
        d = gzhVar14.a();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.catfish_flash_anim_capture_threshold_ms";
        e = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.cuttle.motion_ef";
        s = gzhVar16.f();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.garfish_enabled";
        gzhVar17.o();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.garfish.zsl_buffer_size";
        f = gzhVar18.a();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.cuttle.motion_metadata";
        t = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.cuttle.sky";
        u = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.cuttle.max_exp_ms";
        v = gzhVar21.h();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.cuttle.rerun_fd";
        w = gzhVar22.i();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.cuttle.fastaf";
        x = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.cuttle.enable_timeout";
        y = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.cuttle.custom_timeout_ms";
        g = gzhVar25.a();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.catshark_enabled.RESTART";
        z = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.catshark_cheese";
        A = gzhVar27.i();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.catshark_in_threshold";
        B = gzhVar28.h();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.catshark_out_threshold";
        C = gzhVar29.h();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.catshark_cheese_in_threshold";
        D = gzhVar30.h();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = pAAtrB.YsJVGTgP;
        E = gzhVar31.h();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.catshark_full_threshold";
        F = gzhVar32.h();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.catshark_af";
        G = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.catshark_minibar_enabled";
        H = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.catshark_hires_zoom_in_threshold";
        I = gzhVar35.h();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.catshark_hires_zoom_out_threshold";
        J = gzhVar36.h();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.cuttle.extended";
        K = gzhVar37.i();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.hollywood";
        L = gzhVar38.i();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "camera.force_cuttle.extended";
        gzhVar39.o();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "camera.cuttleface_edu";
        M = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.cuttle.extended.scene";
        N = gzhVar41.i();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.cuttle.extended.fz.RESTART";
        gzhVar42.n();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.cuttle.extended.uwz.RESTART";
        O = gzhVar43.i();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.cuttle.extended.threshold";
        P = gzhVar44.h();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.cuttle.extended.threshold.hires";
        Q = gzhVar45.h();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.cuttle.extended.uwz.threshold";
        R = gzhVar46.h();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.cuttle.extended.uwz.threshold.hires";
        S = gzhVar47.h();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = "camera.kepler_enabled";
        T = gzhVar48.i();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.kepler_min_frame_count";
        h = gzhVar49.a();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camera.kepler_merge_frame_count";
        i = gzhVar50.a();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camera.kepler_capture_threshold_ms";
        j = gzhVar51.a();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camera.kepler_stream_enabled";
        U = gzhVar52.i();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera.kepler_hevc_enabled";
        gzhVar53.n();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera.kepler_frame_duration_ms";
        k = gzhVar54.a();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camera.cuttle_formal_lock_control";
        gzhVar55.o();
    }
}
