package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hae {
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "face_detect_mode_use_extended";
        i = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "flash_intensity_for_photo_modes";
        a = gzhVar2.a();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "flash_intensity_for_photo_modes_enabled";
        j = gzhVar3.i();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "global_imagereader_ticket_limit";
        gzhVar4.a();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "max_hdr_plus_imagereader_image_count";
        b = gzhVar5.a();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "max_hdr_plus_burst_frame_count";
        c = gzhVar6.a();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "max_imagereader_image_count";
        d = gzhVar7.a();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "pd_image_format_is_raw_depth";
        k = gzhVar8.i();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "pd_image_format_is_raw_depth10";
        l = gzhVar9.i();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.auto_hdrp_conf";
        gzhVar10.e();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.hdrp_conf";
        gzhVar11.e();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.f_tuning";
        gzhVar12.e = scn.I(0, 1, 2);
        e = gzhVar12.a();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "bgae.enabled";
        m = gzhVar13.f();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "gcam.sm.denom";
        f = gzhVar14.a();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "gcam.sm.denom_night";
        g = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "gcam.sm.denom_night_limited";
        h = gzhVar16.a();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "gcam.sm.enabled";
        n = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "gcam.sm.log";
        o = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "gcam.debug";
        p = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.hwhdr_intent";
        q = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.hwhdr_inapp";
        gzhVar21.e();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.raw_mode";
        r = gzhVar22.i();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "portrait_use_pd";
        s = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "portrait_use_stereo";
        t = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "portrait_use_ml";
        u = gzhVar25.i();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "simultaneous_af_ae_trigger_supported";
        v = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.data_stream";
        gzhVar27.o();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.enable_gasd_metadata";
        w = gzhVar28.i();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.lead_cam_id";
        x = gzhVar29.i();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.mrir_front";
        y = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.use_frameserver_zoom";
        gzhVar31.m();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.tele_rm";
        z = gzhVar32.g();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.dac_readout";
        gzhVar33.o();
    }
}
