package defpackage;

import com.google.android.apps.camera.jni.gxp.Caan.yoGAhrpjU;
import com.google.android.apps.camera.ui.gridlines.gBW.mNLbzhCxd;
import com.google.android.libraries.oliveoil.natives.TtaZ.VnmwoBe;
import com.google.android.material.button.xlT.JvFFEwFNdCrxf;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hak {
    public static final gzg A;
    public static final gzg B;
    public static final gzg C;
    public static final gzg D;
    public static final gzg E;
    public static final gzg F;
    public static final gzg G;
    public static final gzg H;
    public static final gzg I;
    public static final gzg J;
    public static final gzg K;
    public static final gzg L;
    public static final gzg M;
    public static final gzg N;
    public static final gzg O;
    public static final gzg P;
    public static final gzg Q;
    public static final gzg R;
    public static final gzg S;
    public static final gzg T;
    public static final gzg U;
    public static final gzg V;
    public static final gzg W;
    public static final gzg X;
    public static final gzg Y;
    public static final gzg Z;
    public static final gzi a;
    public static final gzg aa;
    public static final gzg ab;
    public static final gzg ac;
    public static final gzg ad;
    public static final gzg ae;
    public static final gzg af;
    public static final gzg ag;
    public static final gzg ah;
    public static final gzg ai;
    public static final gzg aj;
    public static final gzg ak;
    public static final gzg al;
    private static final sgv am = sgv.g("hak");
    public static final gzg b;
    public static final gzg c;
    public static final gzg d;
    public static final gzg e;
    public static final gzg f;
    public static final gzg g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;
    public static final gzg z;

    public static boolean a(hbj hbjVar) {
        return hbjVar.p(y) && hbjVar.p(z);
    }

    public static boolean b(hbj hbjVar) {
        gzg gzgVar = ai;
        if (!hbjVar.o(gzgVar) && hbjVar.p(aj)) {
            ((sgt) am.b().M(1092)).s("UNBINNED_CROP is not supported, but it is enabled. Disabling UNBINNED_CROP.");
        }
        return hbjVar.p(aj) && hbjVar.o(gzgVar);
    }

    public static void c(hbj hbjVar) {
        gzg gzgVar = al;
        hbjVar.o(gzgVar);
        hbjVar.o(gzgVar);
    }

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.gouda.depthdata";
        b = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.gouda.min_zoom_factor_back";
        c = gzhVar2.h();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "gouda_default_zoom_factor_back";
        d = gzhVar3.h();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "gouda_doubletap_zoom_factor";
        e = gzhVar4.h();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "gouda_use_default_zoom_factor_front_for_test";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "gouda_default_zoom_factor_front_for_test";
        f = gzhVar6.h();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "max_gouda_inflight_shots";
        a = gzhVar7.a();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "portrait_availability";
        g = gzhVar8.i();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "portrait_rear_availability";
        h = gzhVar9.i();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.gouda_debug_img";
        i = gzhVar10.i();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.gouda.raw";
        j = gzhVar11.i();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.gouda_sec_img";
        k = gzhVar12.i();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "segmenter_force_cpu_inference";
        l = gzhVar13.i();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "segmenter_allow_fp16_processing";
        m = gzhVar14.i();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "segmenter_allow_texture_type";
        n = gzhVar15.i();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.gouda.cl_seg";
        o = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "segmenter_use_darwinn_tpu_delegate";
        p = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.gouda.matting_enabled";
        q = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.gouda.firefly_cpu";
        r = gzhVar19.i();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.gouda.firefly_xeno_jet_cl";
        s = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.gouda.use_darwinn_offline_compilation";
        t = gzhVar21.i();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.gouda.darwinn_product_class";
        u = gzhVar22.j();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.gouda.depth_use_opencl";
        v = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.gouda.stdepth";
        w = gzhVar24.i();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.gouda.force_run_stdepth";
        gzhVar25.e();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.gouda.front_learned";
        x = gzhVar26.i();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.gouda.front_learned_v2";
        gzhVar27.o();
        gzh gzhVar28 = new gzh();
        gzhVar28.d("Portrait", false);
        gzhVar28.b = "gouda_rear_rgbpd";
        y = gzhVar28.i();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.gouda.rear_rgbpd";
        z = gzhVar29.i();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.gouda.force_internal_face_detection";
        gzhVar30.o();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.gouda.pirate_enable";
        A = gzhVar31.i();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.gouda.primary_raw";
        B = gzhVar32.i();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.gouda.use_dynamic_depth";
        C = gzhVar33.i();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = yoGAhrpjU.dbPzUJNGbYsI;
        D = gzhVar34.i();
        gzh gzhVar35 = new gzh();
        gzhVar35.b = "camera.gouda.shasta_zsl";
        E = gzhVar35.i();
        gzh gzhVar36 = new gzh();
        gzhVar36.b = "camera.gouda.spotlight_enhance";
        F = gzhVar36.i();
        gzh gzhVar37 = new gzh();
        gzhVar37.b = "camera.gouda.spotlight_enhance_v2";
        G = gzhVar37.i();
        gzh gzhVar38 = new gzh();
        gzhVar38.b = "camera.gouda.single_output";
        H = gzhVar38.i();
        gzh gzhVar39 = new gzh();
        gzhVar39.b = "portrait_enable_cpu_boost";
        I = gzhVar39.i();
        gzh gzhVar40 = new gzh();
        gzhVar40.b = "portrait_enable_gpu_boost";
        J = gzhVar40.i();
        gzh gzhVar41 = new gzh();
        gzhVar41.b = "camera.gouda.portrait_depth_use_tpu";
        K = gzhVar41.i();
        gzh gzhVar42 = new gzh();
        gzhVar42.b = "camera.gouda.portrait_matting_use_tpu";
        L = gzhVar42.i();
        gzh gzhVar43 = new gzh();
        gzhVar43.b = "camera.gouda.hair_matting_use_tpu";
        gzhVar43.o();
        gzh gzhVar44 = new gzh();
        gzhVar44.b = "camera.gouda.portrait_segmenter_use_tpu";
        gzhVar44.o();
        gzh gzhVar45 = new gzh();
        gzhVar45.b = "camera.gouda.rear_pdlearned_model";
        M = gzhVar45.j();
        gzh gzhVar46 = new gzh();
        gzhVar46.b = "camera.gouda.rear_pdlearned_remosaic_model";
        N = gzhVar46.j();
        gzh gzhVar47 = new gzh();
        gzhVar47.b = "camera.gouda.front_pdlearned_model";
        O = gzhVar47.j();
        gzh gzhVar48 = new gzh();
        gzhVar48.b = yoGAhrpjU.ZVHKkqj;
        P = gzhVar48.j();
        gzh gzhVar49 = new gzh();
        gzhVar49.b = "camera.gouda.physeter_model";
        Q = gzhVar49.j();
        gzh gzhVar50 = new gzh();
        gzhVar50.b = "camera.gouda.enable_physeter";
        gzhVar50.o();
        gzh gzhVar51 = new gzh();
        gzhVar51.b = "camera.gouda.pdstereo_remosaic_model";
        R = gzhVar51.j();
        gzh gzhVar52 = new gzh();
        gzhVar52.b = "camera.gouda.monocular_model";
        S = gzhVar52.j();
        gzh gzhVar53 = new gzh();
        gzhVar53.b = "camera.gouda.depth_postprocessor_model";
        T = gzhVar53.j();
        gzh gzhVar54 = new gzh();
        gzhVar54.b = "camera.gouda.portrait_matting_model";
        U = gzhVar54.j();
        gzh gzhVar55 = new gzh();
        gzhVar55.b = "camera.gouda.portrait_multiclass_segmenter";
        V = gzhVar55.k();
        gzh gzhVar56 = new gzh();
        gzhVar56.b = "camera.gouda.hair_matting_model";
        W = gzhVar56.k();
        gzh gzhVar57 = new gzh();
        gzhVar57.b = "camera.gouda.max_zoom";
        X = gzhVar57.h();
        gzh gzhVar58 = new gzh();
        gzhVar58.b = "camera.gouda.allow_widest_front";
        Y = gzhVar58.i();
        gzh gzhVar59 = new gzh();
        gzhVar59.b = "camera.gouda.max_zoom_override";
        Z = gzhVar59.i();
        gzh gzhVar60 = new gzh();
        gzhVar60.b = "camera.gouda.wide_rm";
        gzhVar60.o();
        gzh gzhVar61 = new gzh();
        gzhVar61.b = "camera.gouda.portrait_rm_zoom";
        aa = gzhVar61.i();
        gzh gzhVar62 = new gzh();
        gzhVar62.b = "camera.gouda.enable_pd_disparity_model";
        ab = gzhVar62.i();
        gzh gzhVar63 = new gzh();
        gzhVar63.b = "camera.gouda.pd_disparity_model";
        ac = gzhVar63.j();
        gzh gzhVar64 = new gzh();
        gzhVar64.d("Portrait", false);
        gzhVar64.b = "gouda_enable_lancet_remote";
        ad = gzhVar64.i();
        gzh gzhVar65 = new gzh();
        gzhVar65.b = "camera.gouda.enable_lancet";
        ae = gzhVar65.i();
        gzh gzhVar66 = new gzh();
        gzhVar66.b = VnmwoBe.XXOXSVnzlb;
        af = gzhVar66.i();
        gzh gzhVar67 = new gzh();
        gzhVar67.b = "camera.milk.enable_front";
        gzhVar67.o();
        gzh gzhVar68 = new gzh();
        gzhVar68.b = "camera.milk.rear_model";
        ag = gzhVar68.j();
        gzh gzhVar69 = new gzh();
        gzhVar69.b = "camera.milk.rear_model_thumbnail";
        ah = gzhVar69.j();
        gzh gzhVar70 = new gzh();
        gzhVar70.b = "camera.milk.front_model";
        gzhVar70.l();
        gzh gzhVar71 = new gzh();
        gzhVar71.b = "camera.milk.front_model_thumbnail";
        gzhVar71.l();
        gzh gzhVar72 = new gzh();
        gzhVar72.b = "camera.milk.record_vfe_inputs";
        gzhVar72.o();
        gzh gzhVar73 = new gzh();
        gzhVar73.b = "camera.milk.record_thumbnail_inputs";
        gzhVar73.o();
        gzh gzhVar74 = new gzh();
        gzhVar74.b = "camera.gouda.support_unbinned_crop";
        ai = gzhVar74.g();
        gzh gzhVar75 = new gzh();
        gzhVar75.b = "camera.gouda.enable_unbinned_crop";
        aj = gzhVar75.i();
        gzh gzhVar76 = new gzh();
        gzhVar76.b = "camera.gouda.dac_readout";
        gzhVar76.o();
        gzh gzhVar77 = new gzh();
        gzhVar77.b = "camera.gouda.single_physical";
        ak = gzhVar77.g();
        gzh gzhVar78 = new gzh();
        gzhVar78.b = "camera.gouda.enable_mermaid";
        gzhVar78.o();
        gzh gzhVar79 = new gzh();
        gzhVar79.b = mNLbzhCxd.VxbIAnxknY;
        gzhVar79.o();
        gzh gzhVar80 = new gzh();
        gzhVar80.b = "camera.gouda.support_scallop";
        al = gzhVar80.g();
        gzh gzhVar81 = new gzh();
        gzhVar81.b = JvFFEwFNdCrxf.iiQFaPNemnprLZi;
        gzhVar81.o();
        gzh gzhVar82 = new gzh();
        gzhVar82.b = "camera.gouda.arcore_feature";
        gzhVar82.o();
        gzh gzhVar83 = new gzh();
        gzhVar83.b = "camera.enable_seashell";
        gzhVar83.o();
    }
}
