package defpackage;

import com.google.android.clockwork.common.wearable.wearmaterial.list.CaNf.PJGqOKsIpSdZ;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hav {
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzi g;
    public static final gzi h;
    public static final gzi i;
    public static final gzi j;
    public static final gzi k;
    public static final gzi l;
    public static final gzi m;
    public static final gzi n;
    public static final gzi o;
    public static final gzi p;
    public static final gzi q;
    public static final gzi r;
    public static final gzi s;
    public static final gzi t;
    public static final gzi u;
    public static final gzi v;
    public static final gzi w;
    public static final gzi x;
    public static final gzi y;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "focus_tracking_threshold";
        a = gzhVar.a();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "hdr_net_threshold";
        b = gzhVar2.a();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "lens_suggestion_thermal_threshold";
        c = gzhVar3.a();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "portrait_threshold";
        d = gzhVar4.a();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "rectiface_shape_correction_threshold";
        e = gzhVar5.a();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "smart_metering_threshold";
        f = gzhVar6.a();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "temporal_binning_threshold";
        g = gzhVar7.a();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "torch_threshold";
        h = gzhVar8.a();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "video_ts_threshold";
        i = gzhVar9.a();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "swiss_threshold";
        j = gzhVar10.a();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "falcon_threshold";
        k = gzhVar11.a();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "hawk_threshold";
        l = gzhVar12.a();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "cyclops_threshold";
        m = gzhVar13.a();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = "boba_threshold";
        n = gzhVar14.a();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "video_display_early_threshold";
        o = gzhVar15.a();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "video_display_late_threshold";
        p = gzhVar16.a();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "video_recording_early_threshold";
        q = gzhVar17.a();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "video_recording_late_threshold";
        r = gzhVar18.a();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "taxi_autoswitch_thermal_threshold";
        s = gzhVar19.a();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "microvideo_thermal_threshold";
        t = gzhVar20.a();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "face_deblur_thermal_threshold";
        u = gzhVar21.a();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "saturn_threshold";
        v = gzhVar22.a();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = PJGqOKsIpSdZ.iVKqk;
        w = gzhVar23.a();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "milk_threshold";
        x = gzhVar24.a();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.pollux_thermal_status_threshold";
        y = gzhVar25.a();
    }
}
