package defpackage;

import com.google.android.apps.camera.jni.saliency.tLp.KsvNaXS;
import com.google.android.play.core.install.rwb.GAQqzWiWWcYOgy;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class haw {
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzg f;
    public static final gzg g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.enable_cheetah";
        f = gzhVar.i();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.cheetah_eis_log";
        gzhVar2.e();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.cheetah_fps";
        gzhVar3.e();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.cheetah_psm";
        gzhVar4.e();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.cheetah_info";
        gzhVar5.e();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.cheetah_3a";
        gzhVar6.e();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera.cheetah_selected_t";
        gzhVar7.e();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.cheetah_upperbound_enabled";
        g = gzhVar8.i();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.cheetah_snapshot";
        h = gzhVar9.i();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.cheetah_lock_af_static";
        i = gzhVar10.i();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.cheetah_auto_mode";
        j = gzhVar11.i();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.cheetah_speed";
        gzhVar12.e = scn.K(0, 1, 2, 3, 4);
        a = gzhVar12.a();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.cheetah_auto_bitrate_multiplier";
        k = gzhVar13.h();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = KsvNaXS.AhaPIndcKwlU;
        l = gzhVar14.i();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera.cheetah_long_thresh";
        m = gzhVar15.h();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera_leopard_enabled";
        gzhVar16.d("Timelapse", false);
        n = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.leopard_v2_enabled";
        o = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.leopard_enabled";
        p = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.leopard_forced";
        gzhVar19.o();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.leopard_fnum";
        b = gzhVar20.a();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.leopard_ultra_long";
        q = gzhVar21.i();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.leopard_ultra_long_thresh";
        r = gzhVar22.h();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = GAQqzWiWWcYOgy.ZWKZHkMUcgLrb;
        s = gzhVar23.h();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = "camera.leopard_out_threshold";
        t = gzhVar24.h();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.leopard_stable_duration_ms_threshold";
        c = gzhVar25.a();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.leopard_rcam_min_zoom";
        u = gzhVar26.h();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.leopard_hybrid_ae";
        v = gzhVar27.i();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.cheetah_delay_recording_ms";
        d = gzhVar28.a();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.leopard_scene_mode_enabled";
        w = gzhVar29.i();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.leopard_downsample_before_denoise";
        x = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.leopard_eis_crop_ratio";
        y = gzhVar31.h();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.cheetah_reselect_ratio";
        e = gzhVar32.a();
    }
}
