package defpackage;

import androidx.compose.foundation.text.modifiers.Yk.LmJPKwPBa;
import com.google.android.apps.camera.imax.cyclops.audio.xcIh.cdVQ;
import com.google.android.apps.camera.toast.vvJ.CGlJpiVWrCQOq;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hba {
    public static final gzi a;
    public static final gzi b;
    public static final gzi c;
    public static final gzi d;
    public static final gzi e;
    public static final gzi f;
    public static final gzg g;
    public static final gzg h;
    public static final gzg i;
    public static final gzg j;
    public static final gzg k;
    public static final gzg l;
    public static final gzg m;
    public static final gzg n;
    public static final gzg o;
    public static final gzg p;
    public static final gzg q;
    public static final gzg r;
    public static final gzg s;
    public static final gzg t;
    public static final gzg u;
    public static final gzg v;
    public static final gzg w;
    public static final gzg x;
    public static final gzg y;

    static {
        gzh gzhVar = new gzh();
        gzhVar.b = "camera.zoom.debug_window";
        gzhVar.m();
        gzh gzhVar2 = new gzh();
        gzhVar2.b = "camera.uw_front_zoom_ui";
        g = gzhVar2.i();
        gzh gzhVar3 = new gzh();
        gzhVar3.b = "camera.toggle_zoom_bar";
        h = gzhVar3.i();
        gzh gzhVar4 = new gzh();
        gzhVar4.b = "camera.zoom_decimal_point";
        gzhVar4.n();
        gzh gzhVar5 = new gzh();
        gzhVar5.b = "camera.zoom_ultra_wide_round_down";
        i = gzhVar5.i();
        gzh gzhVar6 = new gzh();
        gzhVar6.b = "camera.zoom_decimal_point_threshold";
        j = gzhVar6.h();
        gzh gzhVar7 = new gzh();
        gzhVar7.b = "camera_ruler_zoom_slider";
        String str = LmJPKwPBa.hBbhIJ;
        gzhVar7.d(str, false);
        k = gzhVar7.i();
        gzh gzhVar8 = new gzh();
        gzhVar8.b = "camera.zoom_slider_extra_dot";
        gzhVar8.e = scn.J(1, 10, 15, 20);
        a = gzhVar8.a();
        gzh gzhVar9 = new gzh();
        gzhVar9.b = "camera.ultra_wide_zoom_ratio_facing_back";
        l = gzhVar9.h();
        gzh gzhVar10 = new gzh();
        gzhVar10.b = "camera.tele_zoom_ratio_facing_back";
        m = gzhVar10.h();
        gzh gzhVar11 = new gzh();
        gzhVar11.b = "camera.ultra_tele_zoom_ratio_facing_back";
        n = gzhVar11.h();
        gzh gzhVar12 = new gzh();
        gzhVar12.b = "camera.max_zoom_ratio_facing_back";
        o = gzhVar12.h();
        gzh gzhVar13 = new gzh();
        gzhVar13.b = "camera.fake_zoom_toggle";
        gzhVar13.n();
        gzh gzhVar14 = new gzh();
        gzhVar14.b = cdVQ.ShlAoihdfOMJSAp;
        gzhVar14.d(str, false);
        b = gzhVar14.a();
        gzh gzhVar15 = new gzh();
        gzhVar15.b = "camera_zoom_slider_tap_to_show";
        gzhVar15.d(str, false);
        p = gzhVar15.i();
        gzh gzhVar16 = new gzh();
        gzhVar16.b = "camera.extra_zoom_linger";
        q = gzhVar16.i();
        gzh gzhVar17 = new gzh();
        gzhVar17.b = "camera.zoom.slider.bar";
        r = gzhVar17.i();
        gzh gzhVar18 = new gzh();
        gzhVar18.b = "camera.zoom.debug";
        s = gzhVar18.i();
        gzh gzhVar19 = new gzh();
        gzhVar19.b = "camera.zoom.initial_zoom";
        t = gzhVar19.h();
        gzh gzhVar20 = new gzh();
        gzhVar20.b = "camera.enable_compose_zoom";
        u = gzhVar20.i();
        gzh gzhVar21 = new gzh();
        gzhVar21.b = "camera.enable_experimental_zoom_configs";
        gzhVar21.m();
        gzh gzhVar22 = new gzh();
        gzhVar22.b = "camera.remove_zoom_haptics";
        gzhVar22.m();
        gzh gzhVar23 = new gzh();
        gzhVar23.b = "camera.zoom.enable_manual_lens_integration";
        v = gzhVar23.i();
        gzh gzhVar24 = new gzh();
        gzhVar24.b = CGlJpiVWrCQOq.fpHSKbfGZBrhK;
        gzhVar24.m();
        gzh gzhVar25 = new gzh();
        gzhVar25.b = "camera.zoom_level_logging";
        gzhVar25.e();
        gzh gzhVar26 = new gzh();
        gzhVar26.b = "camera.zoom_animation_duration";
        c = gzhVar26.a();
        gzh gzhVar27 = new gzh();
        gzhVar27.b = "camera.zoom_curve_control_full";
        w = gzhVar27.j();
        gzh gzhVar28 = new gzh();
        gzhVar28.b = "camera.zoom_curve_control_preset";
        d = gzhVar28.a();
        gzh gzhVar29 = new gzh();
        gzhVar29.b = "camera.custom_zoom_ui_config";
        x = gzhVar29.j();
        gzh gzhVar30 = new gzh();
        gzhVar30.b = "camera.zoom_custom_scale_gesture_detector";
        y = gzhVar30.i();
        gzh gzhVar31 = new gzh();
        gzhVar31.b = "camera.zoom_scale_touch_slop";
        e = gzhVar31.a();
        gzh gzhVar32 = new gzh();
        gzhVar32.b = "camera.zoom_scale_min_span";
        f = gzhVar32.a();
        gzh gzhVar33 = new gzh();
        gzhVar33.b = "camera.log_viewfinder_on_scale";
        gzhVar33.e();
        gzh gzhVar34 = new gzh();
        gzhVar34.b = "camera.log_zoom_fs_parameter_lifecycle";
        gzhVar34.n();
    }
}
