package defpackage;

import android.util.DisplayMetrics;
import com.google.googlex.gcam.Gcam;
import com.google.googlex.gcam.hdrplus.NativeMetadataConverter;
import java.util.concurrent.Executor;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hzx implements tzt {
    private final tzx A;
    private final tzx B;
    private final tzx C;
    private final tzx D;
    private final tzx E;
    private final tzx F;
    private final tzx G;
    private final tzx H;
    private final tzx I;
    private final tzx J;
    private final tzx K;
    private final tzx L;
    private final tzx M;
    private final tzx N;
    private final tzx O;
    private final tzx P;
    private final tzx Q;
    private final tzx R;
    private final tzx S;
    private final tzx T;
    private final tzx U;
    private final tzx V;
    private final tzx a;
    private final tzx b;
    private final tzx c;
    private final tzx d;
    private final tzx e;
    private final tzx f;
    private final tzx g;
    private final tzx h;
    private final tzx i;
    private final tzx j;
    private final tzx k;
    private final tzx l;
    private final tzx m;
    private final tzx n;
    private final tzx o;
    private final tzx p;
    private final tzx q;
    private final tzx r;
    private final tzx s;
    private final tzx t;
    private final tzx u;
    private final tzx v;
    private final tzx w;
    private final tzx x;
    private final tzx y;
    private final tzx z;

    public hzx(tzx tzxVar, tzx tzxVar2, tzx tzxVar3, tzx tzxVar4, tzx tzxVar5, tzx tzxVar6, tzx tzxVar7, tzx tzxVar8, tzx tzxVar9, tzx tzxVar10, tzx tzxVar11, tzx tzxVar12, tzx tzxVar13, tzx tzxVar14, tzx tzxVar15, tzx tzxVar16, tzx tzxVar17, tzx tzxVar18, tzx tzxVar19, tzx tzxVar20, tzx tzxVar21, tzx tzxVar22, tzx tzxVar23, tzx tzxVar24, tzx tzxVar25, tzx tzxVar26, tzx tzxVar27, tzx tzxVar28, tzx tzxVar29, tzx tzxVar30, tzx tzxVar31, tzx tzxVar32, tzx tzxVar33, tzx tzxVar34, tzx tzxVar35, tzx tzxVar36, tzx tzxVar37, tzx tzxVar38, tzx tzxVar39, tzx tzxVar40, tzx tzxVar41, tzx tzxVar42, tzx tzxVar43, tzx tzxVar44, tzx tzxVar45, tzx tzxVar46, tzx tzxVar47, tzx tzxVar48) {
        this.a = tzxVar;
        this.b = tzxVar2;
        this.c = tzxVar3;
        this.d = tzxVar4;
        this.e = tzxVar5;
        this.f = tzxVar6;
        this.g = tzxVar7;
        this.h = tzxVar8;
        this.i = tzxVar9;
        this.j = tzxVar10;
        this.k = tzxVar11;
        this.l = tzxVar12;
        this.m = tzxVar13;
        this.n = tzxVar14;
        this.o = tzxVar15;
        this.p = tzxVar16;
        this.q = tzxVar17;
        this.r = tzxVar18;
        this.s = tzxVar19;
        this.t = tzxVar20;
        this.u = tzxVar21;
        this.v = tzxVar22;
        this.w = tzxVar23;
        this.x = tzxVar24;
        this.y = tzxVar25;
        this.z = tzxVar26;
        this.A = tzxVar27;
        this.B = tzxVar28;
        this.C = tzxVar29;
        this.D = tzxVar30;
        this.E = tzxVar31;
        this.F = tzxVar32;
        this.G = tzxVar33;
        this.H = tzxVar34;
        this.I = tzxVar35;
        this.J = tzxVar36;
        this.K = tzxVar37;
        this.L = tzxVar38;
        this.M = tzxVar39;
        this.N = tzxVar40;
        this.O = tzxVar41;
        this.P = tzxVar42;
        this.Q = tzxVar43;
        this.R = tzxVar44;
        this.S = tzxVar45;
        this.T = tzxVar46;
        this.U = tzxVar47;
        this.V = tzxVar48;
    }

    @Override // defpackage.uem, defpackage.uel
    public final /* synthetic */ Object a() {
        DisplayMetrics displayMetrics = (DisplayMetrics) this.a.a();
        hyd hydVar = (hyd) this.b.a();
        cxb cxbVar = (cxb) this.c.a();
        NativeMetadataConverter nativeMetadataConverterA = ((tgs) this.d).a();
        tgp tgpVar = (tgp) this.e.a();
        pjo pjoVar = (pjo) this.f.a();
        qrh qrhVar = (qrh) this.g.a();
        kqp kqpVar = (kqp) this.h.a();
        Gcam gcam = (Gcam) this.i.a();
        tgn tgnVarA = ((hyt) this.j).a();
        ice iceVarA = ((icf) this.k).a();
        hbj hbjVar = (hbj) this.m.a();
        luj lujVar = (luj) this.n.a();
        our ourVar = (our) this.p.a();
        kgk kgkVar = (kgk) this.q.a();
        iao iaoVar = (iao) this.r.a();
        gox goxVar = (gox) this.t.a();
        tzx tzxVar = this.u;
        hbc hbcVarB = hmp.b();
        iso isoVarA = ((hfl) tzxVar).a();
        hyf hyfVar = (hyf) this.v.a();
        hxy hxyVar = (hxy) this.w.a();
        hyh hyhVar = (hyh) this.x.a();
        hzq hzqVar = (hzq) this.y.a();
        owf owfVar = (owf) this.z.a();
        pbn pbnVar = (pbn) this.A.a();
        kgg kggVar = (kgg) this.B.a();
        iso isoVar = (iso) this.C.a();
        hzj hzjVar = (hzj) this.D.a();
        Executor executor = (Executor) this.E.a();
        lob lobVar = (lob) this.F.a();
        lgo lgoVar = (lgo) this.G.a();
        pnq pnqVar = (pnq) this.H.a();
        cxb cxbVarA = ((iik) this.I).a();
        pjp pjpVarA = ((pab) this.J).a();
        kow kowVar = (kow) this.K.a();
        tzx tzxVar2 = this.l;
        tzx tzxVar3 = this.o;
        tzx tzxVar4 = this.s;
        tzx tzxVar5 = this.L;
        tzx tzxVar6 = this.M;
        hxd hxdVarA = ((hxe) tzxVar5).a();
        mhq mhqVar = (mhq) tzxVar6.a();
        idt idtVar = (idt) this.N.a();
        ibb ibbVar = (ibb) this.O.a();
        owf owfVar2 = (owf) this.P.a();
        tzx tzxVar7 = this.Q;
        tzx tzxVar8 = this.R;
        return new hzw(displayMetrics, hydVar, cxbVar, nativeMetadataConverterA, tgpVar, pjoVar, qrhVar, kqpVar, gcam, tgnVarA, iceVarA, tzxVar2, hbjVar, lujVar, tzxVar3, ourVar, kgkVar, iaoVar, tzxVar4, goxVar, hbcVarB, isoVarA, hyfVar, hxyVar, hyhVar, hzqVar, owfVar, pbnVar, kggVar, isoVar, hzjVar, executor, lobVar, lgoVar, pnqVar, cxbVarA, pjpVarA, kowVar, hxdVarA, mhqVar, idtVar, ibbVar, owfVar2, ((gad) tzxVar7).b(), (owf) tzxVar8.a(), new fri(), ((Boolean) this.S.a()).booleanValue(), ((ibg) this.T).a(), (nkw) this.U.a(), (ihs) this.V.a(), new hgc());
    }
}
