package defpackage;

import com.google.android.apps.camera.ui.layout.GcaLayout;
import com.google.android.apps.camera.ui.layout.MainActivityLayout;
import com.google.android.apps.camera.ui.shutterbutton.ShutterButton;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class izc implements mxe, mxh, nck {
    tzx A;
    tzx B;
    tzx C;
    tzx D;
    tzx E;
    tzx F;
    tzx G;
    tzx H;
    tzx I;
    tzx J;
    tzx K;
    tzx L;
    tzx M;
    tzx N;
    tzx O;
    tzx P;
    tzx Q;
    tzx R;
    tzx S;
    tzx T;
    tzx U;
    tzx V;
    tzx W;
    tzx X;
    tzx Y;
    tzx Z;
    public final izm a;
    final tzx aA;
    final tzx aB;
    final tzx aC;
    final tzx aD;
    final tzx aE;
    final tzx aF;
    final tzx aG;
    final tzx aH;
    final tzx aI;
    final tzx aJ;
    final tzx aK;
    final tzx aL;
    final tzx aM;
    final tzx aN;
    final tzx aO;
    final tzx aP;
    final tzx aQ;
    final tzx aR;
    final tzx aS;
    final tzx aT;
    final tzx aU;
    final tzx aV;
    final tzx aW;
    final tzx aX;
    final tzx aY;
    final tzx aZ;
    final tzx aa;
    final tzx ab;
    final tzx ac;
    final tzx ad;
    final tzx ae;
    final tzx af;
    final tzx ag;
    final tzx ah;
    final tzx ai;
    final tzx aj;
    final tzx ak;
    final tzx al;
    final tzx am;
    final tzx an;
    final tzx ao;
    final tzx ap;
    final tzx aq;
    final tzx ar;
    final tzx as;
    final tzx at;
    final tzx au;
    final tzx av;
    final tzx aw;
    final tzx ax;
    final tzx ay;
    final tzx az;
    public final izc b = this;
    final tzx bA;
    final tzx bB;
    final tzx bC;
    final tzx bD;
    public final tzx bE;
    public final tzx bF;
    final tzx bG;
    final tzx bH;
    final tzx bI;
    public final tzx bJ;
    final tzx bK;
    final tzx bL;
    final tzx bM;
    final tzx bN;
    final tzx bO;
    final tzx bP;
    final tzx bQ;
    final tzx bR;
    final tzx bS;
    final tzx bT;
    final tzx bU;
    final tzx bV;
    final tzx bW;
    final tzx bX;
    final tzx bY;
    final tzx bZ;
    final tzx ba;
    final tzx bb;
    final tzx bc;
    final tzx bd;
    final tzx be;
    final tzx bf;
    final tzx bg;
    final tzx bh;
    final tzx bi;
    final tzx bj;
    final tzx bk;
    final tzx bl;
    final tzx bm;
    final tzx bn;
    final tzx bo;
    final tzx bp;
    final tzx bq;
    final tzx br;
    final tzx bs;
    final tzx bt;
    final tzx bu;
    final tzx bv;
    final tzx bw;
    final tzx bx;
    final tzx by;
    final tzx bz;
    tzx c;
    final tzx cA;
    final tzx cB;
    final tzx cC;
    final tzx cD;
    final tzx cE;
    final tzx cF;
    final tzx cG;
    final tzx cH;
    final tzx cI;
    final tzx cJ;
    final tzx cK;
    final tzx cL;
    final tzx cM;
    final tzx cN;
    final tzx cO;
    final tzx cP;
    final tzx cQ;
    public final tzx cR;
    final tzx cS;
    final tzx cT;
    final tzx cU;
    final tzx cV;
    final tzx cW;
    final tzx cX;
    final tzx cY;
    final tzx cZ;
    final tzx ca;
    final tzx cb;
    final tzx cc;
    final tzx cd;
    final tzx ce;
    final tzx cf;
    final tzx cg;
    final tzx ch;
    final tzx ci;
    final tzx cj;
    final tzx ck;
    final tzx cl;
    final tzx cm;
    final tzx cn;
    final tzx co;
    final tzx cp;
    final tzx cq;
    final tzx cr;
    final tzx cs;
    final tzx ct;
    final tzx cu;
    final tzx cv;
    final tzx cw;
    final tzx cx;
    final tzx cy;
    final tzx cz;
    tzx d;
    tzx dA;
    tzx dB;
    tzx dC;
    tzx dD;
    tzx dE;
    tzx dF;
    tzx dG;
    tzx dH;
    tzx dI;
    tzx dJ;
    tzx dK;
    tzx dL;
    tzx dM;
    tzx dN;
    tzx dO;
    tzx dP;
    tzx dQ;
    tzx dR;
    tzx dS;
    tzx dT;
    tzx dU;
    tzx dV;
    tzx dW;
    tzx dX;
    tzx dY;
    tzx dZ;
    final tzx da;
    final tzx db;
    final tzx dc;
    final tzx dd;
    final tzx de;
    final tzx df;
    final tzx dg;
    final tzx dh;
    final tzx di;
    final tzx dj;
    final tzx dk;
    final tzx dl;
    final tzx dm;
    final tzx dn;

    /* renamed from: do, reason: not valid java name */
    final tzx f0do;
    final tzx dp;
    final tzx dq;
    tzx dr;
    tzx ds;
    tzx dt;
    tzx du;
    tzx dv;
    tzx dw;
    tzx dx;
    tzx dy;
    tzx dz;
    tzx e;
    tzx ea;
    tzx eb;
    tzx ec;
    tzx ed;
    tzx ee;
    tzx ef;
    tzx eg;
    tzx eh;
    tzx ei;
    tzx ej;
    tzx ek;
    tzx el;
    tzx em;
    tzx en;
    final tzx eo;
    final tzx ep;
    final tzx eq;
    final tzx er;
    final tzx es;
    final tzx et;
    public final iso eu;
    public final gox ev;
    final uh ew;
    tzx f;
    tzx g;
    tzx h;
    tzx i;
    tzx j;
    tzx k;
    tzx l;
    tzx m;
    tzx n;
    tzx o;
    tzx p;
    tzx q;
    tzx r;
    tzx s;
    tzx t;
    tzx u;
    tzx v;
    tzx w;
    tzx x;
    tzx y;
    tzx z;

    public izc(izm izmVar, gox goxVar, iso isoVar, ocq ocqVar) {
        this.a = izmVar;
        this.ev = goxVar;
        this.eu = isoVar;
        g(goxVar, isoVar);
        h(goxVar, isoVar, ocqVar);
        tzx tzxVarC = tzs.c(new ism(this.Z, izmVar.o, 11, null));
        this.aa = tzxVarC;
        tzx tzxVarC2 = tzs.c(new fds(this.t, izmVar.it, izmVar.is, 10, (byte[]) null));
        this.ab = tzxVarC2;
        tzx tzxVarC3 = tzs.c(nqn.a);
        this.ac = tzxVarC3;
        tzx tzxVarC4 = tzs.c(new fdh(this.v, izmVar.iA, izmVar.ug, izmVar.iz, izmVar.z, 2, (char[]) null));
        this.ad = tzxVarC4;
        tzx tzxVarC5 = tzs.c(new mvx(this.h, 8));
        this.ae = tzxVarC5;
        tzx tzxVarC6 = tzs.c(new mvx(this.p, 3));
        this.af = tzxVarC6;
        tzx tzxVar = this.i;
        kug kugVar = new kug(tzxVarC6, tzxVar, izmVar.d);
        this.ag = kugVar;
        tzx tzxVarC7 = tzs.c(new fjb(this.t, izmVar.mU, izmVar.qD, tzxVarC3, izmVar.ui, izmVar.is, izmVar.ro, tzxVarC4, izmVar.uj, tzxVarC5, (tzx) kugVar, tzxVarC6, tzxVar, izmVar.ul, izmVar.ug, izmVar.um, 1, (byte[]) null));
        this.ah = tzxVarC7;
        tzx tzxVarC8 = tzs.c(fhh.a);
        this.ai = tzxVarC8;
        ffw ffwVar = new ffw(tzxVarC7, tzxVarC8, izmVar.is);
        this.aj = ffwVar;
        tzx tzxVarC9 = tzs.c(new fds(izmVar.j, izmVar.ak, this.v, 19));
        this.ak = tzxVarC9;
        tzx tzxVarC10 = tzs.c(new fpg(tzxVarC9, 19));
        this.al = tzxVarC10;
        tzx tzxVarC11 = tzs.c(new jyc(this.v, izmVar.gF, izmVar.go, izmVar.W, 6, (char[]) null));
        this.am = tzxVarC11;
        tzx tzxVarC12 = tzs.c(new ihg(izmVar.jB, izmVar.uo, izmVar.jD, 6, (float[]) null));
        this.an = tzxVarC12;
        jmt jmtVar = new jmt(izmVar.z, izmVar.am, this.R, izmVar.uc, izmVar.lE, izmVar.im, this.T, izmVar.ud, this.G, this.X, izmVar.jZ, tzxVarC, izmVar.o, tzxVarC2, ffwVar, tzxVarC10, tzxVarC11, izmVar.lc, izmVar.jB, izmVar.iw, tzxVarC12, 2, (char[]) null);
        this.ao = jmtVar;
        tzx tzxVarC13 = tzs.c(jmtVar);
        this.ap = tzxVarC13;
        ims imsVar = new ims(isoVar, 0);
        this.aq = imsVar;
        tzx tzxVarC14 = tzs.c(new jke(this.h, this.v, this.X, izmVar.o, izmVar.eZ, this.o, izmVar.mU, tzxVarC11, izmVar.go, (tzx) imsVar, 8, (char[][]) null));
        this.ar = tzxVarC14;
        jcx jcxVar = new jcx(tzxVarC11, izmVar.up, izmVar.k, tzxVarC14, izmVar.jJ);
        this.as = jcxVar;
        tzt tztVar = tzz.a;
        List listAU = rnt.aU(1);
        List listAU2 = rnt.aU(5);
        rnt.aP(izmVar.uq, listAU2);
        rnt.aP(izmVar.us, listAU2);
        rnt.aP(izmVar.uw, listAU2);
        rnt.aP(izmVar.uy, listAU2);
        rnt.aQ(izmVar.uC, listAU);
        rnt.aP(tzz.a, listAU2);
        tzz tzzVar = new tzz(listAU, listAU2);
        this.at = tzzVar;
        this.au = new mvi(20);
        tzx tzxVarC15 = tzs.c(new fbn(tzxVarC9, izmVar.am, 19, null));
        this.av = tzxVarC15;
        tzx tzxVarC16 = tzs.c(new fbn(izmVar.tZ, tzxVarC15, 18, null));
        this.aw = tzxVarC16;
        imv imvVar = new imv(isoVar, 1);
        this.ax = imvVar;
        kty ktyVar = new kty(this.h, izmVar.nb, this.S, izmVar.fY, this.v, tzxVarC16, izmVar.k, imvVar);
        this.ay = ktyVar;
        tzx tzxVarC17 = tzs.c(new klq(this.l, izmVar.z, (tzx) ktyVar, 15, (char[]) null));
        this.az = tzxVarC17;
        tzx tzxVarC18 = tzs.c(new ism(izmVar.nE, izmVar.j, 8, null));
        this.aA = tzxVarC18;
        uh uhVar = new uh(izmVar.uD, izmVar.oD, izmVar.uE, izmVar.k, tzxVarC17, izmVar.uF, tzxVarC18, izmVar.qL, this.G, (byte[]) null);
        this.ew = uhVar;
        tzt tztVarB = tzu.b(new ocq(uhVar));
        this.aB = tztVarB;
        noz nozVar = new noz(tztVarB);
        this.aC = nozVar;
        fkh fkhVar = new fkh(tzzVar, nozVar, izmVar.o, 4);
        this.aD = fkhVar;
        tzx tzxVarC19 = tzs.c(new ihg(tzxVarC13, (tzx) jcxVar, (tzx) fkhVar, 10, (char[]) null));
        this.aE = tzxVarC19;
        tzx tzxVarC20 = tzs.c(new nmn(this.g, 1));
        this.aF = tzxVarC20;
        tzx tzxVarC21 = tzs.c(new jqc(tzxVarC11, izmVar.eY, izmVar.im, izmVar.kc, izmVar.eZ, izmVar.uG, this.v, izmVar.o, this.o, tzxVarC14, imsVar, tzxVarC20, 8, (char[][]) null));
        this.aG = tzxVarC21;
        tzx tzxVar2 = this.S;
        tzx tzxVar3 = izmVar.o;
        tzx tzxVar4 = izmVar.kA;
        nfr nfrVar = new nfr(tzxVar2, tzxVar3, tzxVar4);
        this.aH = nfrVar;
        nfy nfyVar = new nfy(tzxVar2, tzxVar3, izmVar.go, tzxVar4);
        this.aI = nfyVar;
        tzx tzxVarC22 = tzs.c(new mqg(tzxVar3, nfrVar, nfyVar, 6));
        this.aJ = tzxVarC22;
        tzx tzxVar5 = izmVar.im;
        jtf jtfVar = new jtf(tzxVar5, tzxVarC21, tzxVarC22, izmVar.jJ, izmVar.k);
        this.aK = jtfVar;
        jtk jtkVar = new jtk(jtfVar, izmVar.fY);
        this.aL = jtkVar;
        tzx tzxVarC23 = tzs.c(new ipw(tzxVar5, this.e, izmVar.in, this.X, izmVar.o, 14, (char[][][]) null));
        this.aM = tzxVarC23;
        tzx tzxVarC24 = tzs.c(new mvx(izmVar.k, 10));
        this.aN = tzxVarC24;
        tzx tzxVarC25 = tzs.c(new iup((tzx) jtkVar, tzxVarC23, tzxVarC24, izmVar.o, izmVar.z, this.v, 16, (int[][][]) null));
        this.aO = tzxVarC25;
        tzx tzxVarC26 = tzs.c(new ism(tzxVarC19, tzxVarC25, 14));
        this.aP = tzxVarC26;
        tzx tzxVarC27 = tzs.c(new ihg(tzxVarC13, (tzx) jcxVar, (tzx) fkhVar, 11, (char[]) null));
        this.aQ = tzxVarC27;
        ism ismVar = new ism(tzxVarC27, tzxVarC25, 13);
        this.aR = ismVar;
        tzx tzxVarC28 = tzs.c(new ipw(this.f, tzxVarC26, (tzx) ismVar, izmVar.uH, izmVar.k, 4, (int[]) null));
        this.aS = tzxVarC28;
        jaf jafVar = new jaf(izmVar.lt, 1, (byte[]) null);
        this.aT = jafVar;
        tzx tzxVar6 = this.v;
        hgv hgvVar = new hgv(tzxVarC20, tzxVar6, izmVar.ln, (tzx) jafVar, 14, (byte[]) null);
        this.aU = hgvVar;
        koi koiVar = new koi(tzxVarC20, izmVar.iC, izmVar.iD, tzxVar6, izmVar.W, 17, (boolean[][][]) null);
        this.aV = koiVar;
        tzx tzxVarC29 = tzs.c(krk.a);
        this.aW = tzxVarC29;
        tzx tzxVar7 = izmVar.oL;
        tzx tzxVar8 = izmVar.iz;
        tzx tzxVar9 = izmVar.iA;
        tzx tzxVar10 = izmVar.lc;
        tzx tzxVar11 = izmVar.jB;
        tzx tzxVar12 = this.v;
        fgm fgmVar = new fgm(tzxVarC20, tzxVar7, tzxVarC5, tzxVar8, tzxVar9, tzxVar10, tzxVar11, tzxVarC29, tzxVar12, 1, (byte[]) null);
        this.aX = fgmVar;
        jql jqlVar = new jql(izmVar.qO, tzxVarC20, tzxVar12, 12, (boolean[]) null);
        this.aY = jqlVar;
        fdh fdhVar = new fdh(this.g, tzxVar12, izmVar.jv, izmVar.ju, izmVar.z, 9, (short[][]) null);
        this.aZ = fdhVar;
        ixz ixzVar = new ixz(goxVar);
        this.ba = ixzVar;
        tzx tzxVarC30 = tzs.c(new mcr(this.G, 2));
        this.bb = tzxVarC30;
        lug lugVar = new lug(izmVar.h, izmVar.eZ, izmVar.uI);
        this.bc = lugVar;
        tzx tzxVarC31 = tzs.c(new gsq(izmVar.o, this.G, izmVar.B, 10, (char[][]) null));
        this.bd = tzxVarC31;
        tzx tzxVarC32 = tzs.c(new irz(izmVar.d, (tzx) ixzVar, izmVar.O, this.G, izmVar.ub, tzxVarC30, izmVar.w, izmVar.k, this.g, izmVar.qL, tzxVarC17, (tzx) lugVar, izmVar.uJ, tzxVarC18, izmVar.uL, tzxVarC31, izmVar.o, 1, (byte[]) null));
        this.be = tzxVarC32;
        tzx tzxVar13 = izmVar.z;
        fds fdsVar = new fds(tzxVar13, this.l, tzxVarC32, 2, (char[]) null);
        this.bf = fdsVar;
        tzx tzxVar14 = izmVar.k;
        fbn fbnVar = new fbn(fdsVar, tzxVar14, 3, null);
        this.bg = fbnVar;
        lko lkoVar = new lko(izmVar.uO, izmVar.uQ, izmVar.uS, izmVar.uU, tzxVar14, tzxVar13, this.w, izmVar.eZ, 4, (int[]) null);
        this.bh = lkoVar;
        tzx tzxVarC33 = tzs.c(lkoVar);
        this.bi = tzxVarC33;
        tzx tzxVarC34 = tzs.c(new lva(tzxVarC33, izmVar.k, 11, null));
        this.bj = tzxVarC34;
        tzx tzxVar15 = this.f;
        tzx tzxVar16 = izmVar.k;
        fds fdsVar2 = new fds(tzxVarC34, tzxVar15, tzxVar16, 0);
        this.bk = fdsVar2;
        hgv hgvVar2 = new hgv(this.g, izmVar.nu, izmVar.nv, izmVar.nw, 2, (char[]) null);
        this.bl = hgvVar2;
        gve gveVar = new gve(hgvVar2, tzxVar16, 13, null);
        this.bm = gveVar;
        ims imsVar2 = new ims(this.X, 1);
        this.bn = imsVar2;
        ipw ipwVar = new ipw(izmVar.jJ, tzxVarC20, imsVar2, izmVar.oK, this.j, 5, (boolean[]) null);
        this.bo = ipwVar;
        tzx tzxVar17 = izmVar.se;
        tzx tzxVar18 = izmVar.sg;
        tzx tzxVar19 = this.w;
        tzx tzxVar20 = this.v;
        tzx tzxVar21 = izmVar.o;
        ixk ixkVar = new ixk(tzxVarC20, imsVar2, tzxVar17, tzxVar18, tzxVar19, tzxVar20, tzxVar21, izmVar.z, 19, (byte[]) null, (byte[]) null);
        this.bp = ixkVar;
        lkf lkfVar = new lkf(izmVar.iv, izmVar.it, izmVar.uX, izmVar.uZ, izmVar.qa, tzxVar21);
        this.bq = lkfVar;
        kuu kuuVar = new kuu(izmVar.sh, izmVar.uV, tzxVar20, lkfVar, 20, null, null);
        this.br = kuuVar;
        ksl kslVar = new ksl(imsVar2, izmVar.qU, izmVar.qV, izmVar.mF, izmVar.mq, tzxVar20, 11, (boolean[][]) null);
        this.bs = kslVar;
        tzx tzxVarC35 = tzs.c(new kuv(this.t, this.C, izmVar.fY, 18));
        this.bt = tzxVarC35;
        tzx tzxVarC36 = tzs.c(new lqf(izmVar.z, this.h, this.l, tzxVarC35, izmVar.k, 0));
        this.bu = tzxVarC36;
        lva lvaVar = new lva(tzxVarC20, izmVar.kx, 6, null);
        this.bv = lvaVar;
        List listAU3 = rnt.aU(14);
        List listAU4 = rnt.aU(0);
        rnt.aQ(hgvVar, listAU3);
        rnt.aQ(koiVar, listAU3);
        rnt.aQ(fgmVar, listAU3);
        rnt.aQ(jqlVar, listAU3);
        rnt.aQ(fdhVar, listAU3);
        rnt.aQ(fbnVar, listAU3);
        rnt.aQ(fdsVar2, listAU3);
        rnt.aQ(gveVar, listAU3);
        rnt.aQ(ipwVar, listAU3);
        rnt.aQ(ixkVar, listAU3);
        rnt.aQ(kuuVar, listAU3);
        rnt.aQ(kslVar, listAU3);
        rnt.aQ(tzxVarC36, listAU3);
        rnt.aQ(lvaVar, listAU3);
        tzz tzzVar2 = new tzz(listAU3, listAU4);
        this.bw = tzzVar2;
        ovk ovkVar = new ovk(izmVar.z);
        this.bx = ovkVar;
        ixx ixxVar = new ixx(goxVar);
        this.by = ixxVar;
        tzx tzxVarC37 = tzs.c(new gla(ixxVar, 12));
        this.bz = tzxVarC37;
        tzx tzxVarC38 = tzs.c(new gla(ixxVar, 11));
        this.bA = tzxVarC38;
        tzx tzxVarC39 = tzs.c(new ggs(tzxVarC37, tzxVarC38, 14));
        this.bB = tzxVarC39;
        List listAU5 = rnt.aU(0);
        List listAU6 = rnt.aU(1);
        rnt.aP(tzxVarC39, listAU6);
        tzz tzzVar3 = new tzz(listAU5, listAU6);
        this.bC = tzzVar3;
        tzx tzxVarC40 = tzs.c(new fdl(tzzVar3, 0));
        this.bD = tzxVarC40;
        this.bE = tzs.c(new kei(this.z, this.B, this.H, this.N, this.O, this.Q, tzxVarC28, tzzVar2, izmVar.tZ, tzxVarC15, izmVar.fY, ovkVar, izmVar.k, tzxVarC40, 1, null));
        this.bF = tzs.c(jul.a);
        mxx mxxVar = new mxx(this.c);
        this.bG = mxxVar;
        this.bH = tzs.c(new mvx(this.s, 7));
        lvr lvrVar = new lvr(izmVar.rd, izmVar.eZ);
        this.bI = lvrVar;
        tzx tzxVarC41 = tzs.c(new fyr(this.l, this.t, lvrVar, izmVar.vn, izmVar.vo, izmVar.vp, izmVar.vq, izmVar.vr, izmVar.vs, izmVar.o, izmVar.O, izmVar.z, izmVar.w, 6, (float[]) null));
        this.bJ = tzxVarC41;
        this.bK = tzs.c(new mvx(this.p, 4));
        this.bL = new hoa(isoVar, 2);
        imq imqVar = new imq(isoVar);
        this.bM = imqVar;
        tzx tzxVarC42 = tzs.c(new iup(this.J, this.t, this.h, tzxVarC41, this.K, izmVar.eZ, 3, (short[]) null));
        this.bN = tzxVarC42;
        tzx tzxVar22 = this.t;
        this.bO = new mgg(tzxVar22, izmVar.eZ, tzxVarC42, this.v);
        this.bP = new ivy(tzxVar22, 6);
        tzx tzxVarC43 = tzs.c(new mnj(izmVar.z, this.h, this.l, izmVar.O, izmVar.o, this.o, 0));
        this.bQ = tzxVarC43;
        tzx tzxVarC44 = tzs.c(new lqf(this.t, izmVar.o, tzxVarC43, izmVar.b, this.g, 17, (boolean[][][]) null));
        this.bR = tzxVarC44;
        this.bS = tzs.c(new mei(tzxVarC44, izmVar.o, 8, null));
        this.bT = tzs.c(mil.a);
        this.bU = tzs.c(mim.a);
        this.bV = tzs.c(lux.a);
        this.bW = tzs.c(new mvx(this.r, 6));
        tzx tzxVarC45 = tzs.c(new fsa(18));
        this.bX = tzxVarC45;
        this.bY = tzs.c(new fus(this.v, izmVar.rK, izmVar.z, 2));
        this.bZ = tzs.c(new ftf(izmVar.O, tzxVarC45, 12));
        imo imoVar = new imo(isoVar);
        this.ca = imoVar;
        this.cb = tzs.c(mnz.a);
        mcr mcrVar = new mcr(this.t, 7);
        this.cc = mcrVar;
        this.cd = tzs.c(mcrVar);
        mgd mgdVar = new mgd(izmVar.lF, izmVar.uG, izmVar.vY, izmVar.vW, izmVar.eZ);
        this.ce = mgdVar;
        tzx tzxVarC46 = tzs.c(new mgk(this.t, this.g, tzxVarC42, mgdVar, izmVar.O, izmVar.z, this.l, izmVar.o, 0));
        this.cf = tzxVarC46;
        tzx tzxVarC47 = tzs.c(new fpg(tzxVarC15, 18));
        this.cg = tzxVarC47;
        this.ch = tzs.c(nqb.a);
        this.ci = tzs.c(npz.a);
        this.cj = new fdl(ffwVar, 4);
        tzx tzxVarC48 = tzs.c(lxf.a);
        this.ck = tzxVarC48;
        this.cl = new lva(tzxVarC48, izmVar.gp, 9);
        tzx tzxVarB = uaa.b(new lsk(izmVar.h, 5));
        this.cm = tzxVarB;
        tzx tzxVarC49 = tzs.c(new mul(tzxVarC43, tzxVarB, izmVar.o, izmVar.va, izmVar.eZ, 3, (short[]) null));
        this.cn = tzxVarC49;
        this.co = tzs.c(new mrj((Object) izmVar.o, izmVar.eZ, 4));
        tzx tzxVarC50 = tzs.c(gtz.a);
        this.cp = tzxVarC50;
        tzx tzxVarC51 = tzs.c(new ggs(izmVar.rp, izmVar.o, 20, null));
        this.cq = tzxVarC51;
        tzx tzxVarC52 = tzs.c(new fgc(izmVar.og, tzxVarC51, tzxVarC17, this.g, izmVar.tY, izmVar.O, izmVar.lc, 13, (byte[][][]) null));
        this.cr = tzxVarC52;
        tzx tzxVarC53 = tzs.c(new gla(izmVar.o, 14));
        this.cs = tzxVarC53;
        tzx tzxVarC54 = tzs.c(new gqd(izmVar.tB, tzxVarC53, tzxVarC17, this.g, izmVar.tY, izmVar.O, 4, (int[]) null));
        this.ct = tzxVarC54;
        this.cu = tzs.c(new fgv(izmVar.tB, tzxVarC50, tzxVarC17, this.g, izmVar.tY, izmVar.o, tzxVarC52, izmVar.rp, tzxVarC54, izmVar.O, 7, (byte[][]) null));
        mvx mvxVar = new mvx(izmVar.kb, 9);
        this.cv = mvxVar;
        tzx tzxVarC55 = tzs.c(mvxVar);
        this.cw = tzxVarC55;
        tzx tzxVar23 = izmVar.z;
        ncb ncbVar = new ncb(tzxVar23, imoVar, tzxVarC41, tzxVarC55, izmVar.j, izmVar.aa, this.e, izmVar.hl);
        this.cx = ncbVar;
        this.cy = tzs.c(new ish((tzx) ncbVar, tzxVar23, this.v, this.l, 10, (int[][]) null));
        this.cz = tzs.c(new mvx(this.p, 5));
        tzx tzxVarC56 = tzs.c(new fpg(izmVar.d, 5));
        this.cA = tzxVarC56;
        tzx tzxVarC57 = tzs.c(fpz.a);
        this.cB = tzxVarC57;
        this.cC = tzs.c(new fgm(tzxVarC56, izmVar.jZ, izmVar.go, izmVar.qe, izmVar.ub, izmVar.wD, izmVar.wE, tzxVarC57, this.v, 4, (int[]) null));
        tzx tzxVarC58 = tzs.c(muf.a);
        this.cD = tzxVarC58;
        tzx tzxVarC59 = tzs.c(new mcr(izmVar.o, 17));
        this.cE = tzxVarC59;
        tzx tzxVarC60 = tzs.c(new mrj((Object) izmVar.o, tzxVarC59, 3));
        this.cF = tzxVarC60;
        tzx tzxVarC61 = tzs.c(new ksm(this.h, izmVar.o, izmVar.z, tzxVarC58, mxxVar, tzxVarC60, izmVar.tW, 19, (byte[]) null, (byte[]) null));
        this.cG = tzxVarC61;
        this.cH = tzs.c(new mnj(this.h, tzxVarC61, izmVar.eZ, izmVar.o, (tzx) mxxVar, izmVar.tW, 4, (int[]) null));
        this.cI = new imt(isoVar, 0);
        this.cJ = new nns(this.h);
        this.cK = tzs.c(new iqn(imqVar, izmVar.z, 1));
        this.cL = new ixy(goxVar);
        this.cM = tzs.c(new lib(izmVar.o, 15));
        this.cN = tzs.c(new mqg(izmVar.z, izmVar.o, this.t, 3, (short[]) null));
        jhp jhpVar = new jhp(this.t);
        this.cO = jhpVar;
        this.cP = tzs.c(new ism(jhpVar, izmVar.oL, 19, null));
        this.cQ = tzs.c(new mnj(izmVar.o, tzxVarC20, izmVar.jJ, izmVar.mx, izmVar.rY, izmVar.oL, 2, (char[]) null));
        this.cR = tzs.c(gni.a);
        tzx tzxVarC62 = tzs.c(jtb.a);
        this.cS = tzxVarC62;
        this.cT = tzs.c(new khd(izmVar.rd, tzxVarC62, izmVar.tY, izmVar.jv, tzxVarB, 1, null));
        this.cU = tzs.c(new jjg(tzxVarC17, tzxVarC5, 18, null));
        this.cV = tzs.c(new fpg(tzxVarC9, 17));
        this.cW = tzs.c(new ksl(this.t, tzxVarC11, izmVar.im, izmVar.vY, izmVar.o, izmVar.ju, 14, (char[][][]) null));
        this.cX = tzs.c(new mvx(this.p, 2));
        tzx tzxVarC63 = tzs.c(new ihg(izmVar.oV, this.g, izmVar.o, 19, (short[][]) null));
        this.cY = tzxVarC63;
        jaf jafVar2 = new jaf(tzxVarC63, 1, (byte[]) null);
        this.cZ = jafVar2;
        this.da = new gad(jafVar2, izmVar.gp, 11);
        tzx tzxVarC64 = tzs.c(new gsq(izmVar.rp, izmVar.O, izmVar.o, 5, (boolean[]) null));
        this.db = tzxVarC64;
        this.dc = tzs.c(new fgl(tzxVarC64, this.t, tzxVarC42, izmVar.og, izmVar.O, izmVar.tY, tzxVarB, izmVar.o, 7, (byte[][]) null));
        this.dd = tzs.c(new mrj((Object) izmVar.d, izmVar.gz, 8));
        this.de = tzs.c(new mcr(this.n, 20));
        this.df = tzs.c(new fpg(tzxVarC9, 16));
        jaf jafVar3 = new jaf(tzxVarC49, 1, (byte[]) null);
        this.dg = jafVar3;
        this.dh = tzs.c(new mrj((Object) jafVar3, izmVar.o, 5));
        tzx tzxVar24 = jaj.a;
        this.di = tzxVar24;
        tzx tzxVarC65 = tzs.c(new nke(izmVar.o, this.t, 8));
        this.dj = tzxVarC65;
        this.dk = new lzr(tzxVar24, tzxVarC65, 10);
        this.dl = tzs.c(new fds(this.P, izmVar.z, izmVar.o, 20, (float[]) null));
        gpp gppVar = new gpp(izmVar.d);
        this.dm = gppVar;
        this.dn = tzs.c(new fus(izmVar.o, (tzx) gppVar, this.t, 20, (byte[]) null));
        tzx tzxVarC66 = tzs.c(new ggs(this.t, izmVar.z, 17, null));
        this.f0do = tzxVarC66;
        this.dp = tzs.c(new ggs(this.t, tzxVarC66, 12, null));
        this.dq = tzs.c(gpx.a);
        e();
        f();
        tzx tzxVar25 = izmVar.o;
        tzx tzxVar26 = izmVar.eZ;
        tzx tzxVar27 = this.dM;
        this.eo = new ihg(tzxVar25, tzxVar26, tzxVar27, 8, (char[]) null);
        this.ep = new jql(izmVar.qH, this.g, this.v, 11, (boolean[]) null);
        this.eq = new lwa(izmVar.oH, tzxVar27, izmVar.oO, 6, (float[]) null);
        this.er = new mei(tzxVar27, tzxVarC46, 6, null);
        this.es = tzs.c(new fbw(izmVar.d, tzxVar25, this.l, tzxVarC47, tzxVarC16, izmVar.k, 9, (short[][]) null));
        this.et = tzs.c(new ivy(izmVar.hs, 3));
    }

    private final void e() {
        tzx tzxVar = this.t;
        izm izmVar = this.a;
        tzx tzxVar2 = this.f0do;
        tzx tzxVarC = tzs.c(new feq(tzxVar, tzxVar2, izmVar.o, this.bz, 19, (byte[]) null, (byte[]) null));
        this.dr = tzxVarC;
        this.ds = tzs.c(new fdh(this.t, this.dp, this.dq, tzxVarC, izmVar.o, 17, (boolean[][][]) null));
        this.dt = new gql(izmVar.j);
        tzx tzxVarC2 = tzs.c(new ggs(izmVar.k, izmVar.hw, 13, null));
        this.du = tzxVarC2;
        this.dv = tzs.c(new fdh(this.ds, this.dt, tzxVarC2, izmVar.d, izmVar.k, 19, (byte[]) null, (byte[]) null));
        this.dw = tzs.c(grn.a);
        this.dx = tzs.c(gpy.a);
        tzx tzxVarC3 = tzs.c(new gqd(this.dn, this.dv, izmVar.k, this.az, this.dw, this.dx, 0));
        this.dy = tzxVarC3;
        this.dz = tzs.c(new gla(tzxVarC3, 10));
        lyv lyvVar = new lyv(izmVar.ng);
        this.dA = lyvVar;
        this.dB = tzs.c(new feq(lyvVar, izmVar.hw, this.af, izmVar.o, 20, (char[]) null, (byte[]) null));
        this.dC = tzs.c(new gla(izmVar.O, 8));
        this.dD = tzs.c(gqn.a);
        this.dE = tzs.c(new gpw(5));
        this.dF = tzs.c(new ggs(izmVar.z, this.dE, 15));
        this.dG = tzs.c(new ggs(izmVar.j, izmVar.o, 16));
        tzx tzxVarC4 = tzs.c(new fdh(izmVar.qp, izmVar.wr, izmVar.hw, this.dF, this.dG, 18, (float[][][]) null));
        this.dH = tzxVarC4;
        this.dI = new gpz(this.dD, tzxVarC4, this.dG, izmVar.o, this.v);
        this.dJ = tzs.c(new fdh(this.bN, izmVar.z, tzxVar2, this.t, this.bA, 15, (short[][][]) null));
        this.dK = tzs.c(new gla(izmVar.hw, 13));
        this.dL = tzs.c(new gsp(this.dz, this.du, this.dB, izmVar.o, this.G, this.dC, this.dI, this.dJ, this.dK, this.t, this.dx, 0));
        this.dM = tzs.c(new lvb(this.ck, 12));
        tzx tzxVarC5 = tzs.c(gte.a);
        this.dN = tzxVarC5;
        this.dO = tzs.c(new ggs(tzxVarC5, this.dK, 19));
        this.dP = tzs.c(new fbn(izmVar.W, this.av, 17, null));
    }

    private final void f() {
        izm izmVar = this.a;
        this.dQ = tzs.c(new gsq(izmVar.j, this.dP, this.dK, 0));
        tzx tzxVarC = tzs.c(new ggs(this.dK, izmVar.yA, 18, null));
        this.dR = tzxVarC;
        gqd gqdVar = new gqd(this.dz, this.dI, this.dO, this.dQ, tzxVarC, this.dB, 2, (char[]) null);
        this.dS = gqdVar;
        tzx tzxVarC2 = tzs.c(gqdVar);
        this.dT = tzxVarC2;
        this.dU = new gtc(this.dK, tzxVarC2);
        this.dV = new fdh(this.dL, this.dM, izmVar.z, this.dn, this.dU, 20, (char[]) null, (byte[]) null);
        this.dW = new kuu(this.v, this.h, izmVar.xc, izmVar.o, 18, (float[]) null);
        this.dX = new nlf(this.az);
        this.dY = tzs.c(new fbn(izmVar.iA, this.dX, 13, null));
        this.dZ = new mmm(izmVar.va);
        this.ea = tzs.c(lxr.a);
        this.eb = tzs.c(new ksl(izmVar.z, izmVar.O, this.dZ, izmVar.qD, izmVar.wo, this.ea, 16, (int[][][]) null));
        this.ec = new lxh(this.aW, this.cD, this.S, this.t, 0);
        tzx tzxVarC3 = tzs.c(new knp(izmVar.ng, this.eb, this.cg, izmVar.pD, izmVar.qH, izmVar.ls, this.g, this.ec, izmVar.k, 9, (short[][]) null));
        this.ed = tzxVarC3;
        this.ee = new lxg(tzxVarC3, izmVar.z, this.l);
        this.ef = new fbn(this.bj, this.f, 2, null);
        tzx tzxVar = izmVar.rd;
        tzx tzxVar2 = this.cS;
        tzx tzxVar3 = this.cm;
        this.eg = tzs.c(new koi(tzxVar, tzxVar2, tzxVar3, izmVar.it, izmVar.tY, 18, (float[][][]) null));
        this.eh = new kuu(izmVar.o, izmVar.eZ, this.dM, this.eg, 16, (int[][][]) null);
        this.ei = tzs.c(new lva(izmVar.z, this.G, 13, null));
        tzx tzxVar4 = this.v;
        this.ej = new feq(tzxVar4, izmVar.rQ, this.X, izmVar.xr, 0);
        tzx tzxVar5 = this.dM;
        tzx tzxVar6 = this.cT;
        tzx tzxVar7 = izmVar.eZ;
        tzx tzxVar8 = izmVar.o;
        this.ek = new ipw(tzxVar5, tzxVar6, tzxVar7, tzxVar8, izmVar.ju, 20, (char[]) null, (byte[]) null);
        this.el = new fgc(tzxVar8, tzxVar7, tzxVar5, this.cr, this.ct, this.dc, this.cu, 12, (float[][]) null);
        this.em = new hcm(izmVar.hp, izmVar.hw, izmVar.yF, this.dN, tzxVar4, 1, (byte[]) null);
        this.en = tzs.c(new iup(tzxVar8, izmVar.kV, this.g, tzxVar4, this.w, izmVar.z, 0));
        tzs.c(new ixk(izmVar.rd, tzxVar2, this.en, izmVar.it, izmVar.tY, this.v, izmVar.k, tzxVar3, 1, (byte[]) null));
    }

    private final void g(gox goxVar, iso isoVar) {
        this.c = tzs.c(mxw.a);
        this.d = tzs.c(mxy.a);
        imr imrVar = new imr(isoVar);
        this.e = imrVar;
        izm izmVar = this.a;
        nkv nkvVar = new nkv(imrVar, izmVar.o);
        this.f = nkvVar;
        this.g = tzs.c(new mvx(nkvVar, 20));
        this.h = new imn(isoVar);
        this.i = tzs.c(mxv.a);
        this.j = new ixu(goxVar);
        tzx tzxVar = this.h;
        tzx tzxVar2 = this.i;
        tzx tzxVar3 = izmVar.z;
        this.k = new mgs(tzxVar, tzxVar2, tzxVar3, this.j);
        iyb iybVar = new iyb(goxVar);
        this.l = iybVar;
        this.m = tzs.c(new lwa(this.k, tzxVar3, (tzx) iybVar, 14, (char[]) null));
        tzx tzxVarC = tzs.c(new mul(this.h, this.l, izmVar.z, izmVar.O, izmVar.nb, 0));
        this.n = tzxVarC;
        this.o = tzs.c(new mcr(tzxVarC, 19));
        this.p = tzs.c(myb.a);
        this.q = tzs.c(myc.a);
        this.r = tzs.c(mxz.a);
        this.s = tzs.c(mya.a);
        imm immVar = new imm(isoVar, 0);
        this.t = immVar;
        this.u = tzs.c(new nke(immVar, izmVar.o, 6, null));
        this.v = new ixw(goxVar);
        this.w = new ixv(goxVar);
        imu imuVar = new imu(isoVar);
        this.x = imuVar;
        this.y = new hgr(imuVar, izmVar.O, izmVar.aa, this.g, izmVar.gJ);
        this.z = tzs.c(new hcm(izmVar.tU, this.v, this.w, this.y, izmVar.z, 2, (char[]) null));
        this.A = tzs.c(new lwa(this.h, izmVar.z, this.w, 2, (char[]) null));
    }

    private final void h(gox goxVar, iso isoVar, ocq ocqVar) {
        izm izmVar = this.a;
        this.B = tzs.c(new lqf(izmVar.gA, this.A, izmVar.gS, izmVar.gO, izmVar.z, 6, (float[]) null));
        tzx tzxVarC = tzs.c(new fbn(this.x, izmVar.z, 5, null));
        this.C = tzxVarC;
        tzx tzxVar = this.t;
        tzx tzxVar2 = this.h;
        tzx tzxVar3 = izmVar.O;
        tzx tzxVar4 = izmVar.cT;
        this.D = tzs.c(new fbw(tzxVar, tzxVarC, tzxVar2, tzxVar3, tzxVar4, izmVar.gJ, 19, null, null));
        this.E = tzs.c(new fus(izmVar.z, this.w, this.h, 19, (byte[]) null));
        this.F = tzs.c(new fgc(this.D, izmVar.z, izmVar.tX, izmVar.gJ, izmVar.O, tzxVar4, this.E, 10, (int[][]) null));
        this.G = tzs.c(new mcr(ocqVar, 3));
        this.H = tzs.c(new fbw(izmVar.ii, this.F, this.G, izmVar.gJ, izmVar.tU, izmVar.W, 3, (short[]) null));
        this.I = tzs.c(new fds(this.h, izmVar.eZ, izmVar.z, 3, (byte[]) null));
        this.J = new iya(goxVar);
        this.K = tzs.c(new ljh(this.h, izmVar.ua, 8, null));
        fgv fgvVar = new fgv(this.h, this.C, this.l, this.I, this.J, izmVar.z, izmVar.tZ, this.K, izmVar.ik, this.G, 1, (byte[]) null);
        this.L = fgvVar;
        tzx tzxVarC2 = tzs.c(fgvVar);
        this.M = tzxVarC2;
        this.N = tzs.c(new fbn(tzxVarC2, this.G, 4));
        this.O = tzs.c(new fdh(izmVar.ub, izmVar.o, this.t, this.C, izmVar.z, 0));
        tzx tzxVarC3 = tzs.c(new fpg(izmVar.k, 20));
        this.P = tzxVarC3;
        this.Q = tzs.c(new ftp(tzxVarC3, 1));
        this.R = tzs.c(new ksl(izmVar.z, izmVar.o, this.g, izmVar.lc, izmVar.ld, izmVar.sx, 13, (byte[][][]) null));
        imp impVar = new imp(isoVar);
        this.S = impVar;
        this.T = tzs.c(new ihi(impVar, 9));
        this.U = tzs.c(new fbw(this.t, this.C, this.h, izmVar.O, tzxVar4, izmVar.gJ, 20, null, null));
        this.V = tzs.c(new gqd(izmVar.z, izmVar.tX, this.U, izmVar.gJ, tzxVar4, this.E, 1, (byte[]) null));
        this.W = tzs.c(new gla(this.e, 5));
        this.X = tzs.c(new fgm(izmVar.im, izmVar.z, this.V, this.F, izmVar.tX, izmVar.gJ, izmVar.tU, this.e, this.W, 12, (float[][]) null));
        tzx tzxVarC4 = tzs.c(new ivy(this.t, 1));
        this.Y = tzxVarC4;
        this.Z = new jaf(tzxVarC4, 1, (byte[]) null);
    }

    final rww a() {
        return new fvq((AtomicReference) this.c.a(), 9);
    }

    @Override // defpackage.mxe
    public final void b(GcaLayout gcaLayout) {
        gcaLayout.i = a();
        gcaLayout.j = (AtomicReference) this.c.a();
        izm izmVar = this.a;
        gcaLayout.n = (hbj) izmVar.o.a();
        gcaLayout.k = (pnq) izmVar.b.a();
        gcaLayout.l = (owq) this.d.a();
        gcaLayout.m = (owf) izmVar.tW.a();
    }

    /* JADX WARN: Type inference failed for: r0v24, types: [java.lang.Object, owq] */
    @Override // defpackage.mxh
    public final void c(MainActivityLayout mainActivityLayout) {
        ((GcaLayout) mainActivityLayout).i = a();
        ((GcaLayout) mainActivityLayout).j = (AtomicReference) this.c.a();
        izm izmVar = this.a;
        ((GcaLayout) mainActivityLayout).n = (hbj) izmVar.o.a();
        ((GcaLayout) mainActivityLayout).k = (pnq) izmVar.b.a();
        ((GcaLayout) mainActivityLayout).l = (owq) this.d.a();
        ((GcaLayout) mainActivityLayout).m = (owf) izmVar.tW.a();
        mainActivityLayout.r = (AtomicReference) this.c.a();
        mainActivityLayout.s = (owq) this.g.a();
        mainActivityLayout.A = (mgr) this.m.a();
        mainActivityLayout.B = (jgt) this.ev.a;
        mainActivityLayout.t = (owf) this.o.a();
        mainActivityLayout.u = this.eu.a;
        mainActivityLayout.v = (sbv) this.p.a();
        mainActivityLayout.w = (owq) this.i.a();
        mainActivityLayout.x = (owq) this.q.a();
        mainActivityLayout.y = (owq) this.r.a();
        mainActivityLayout.z = (owq) this.s.a();
    }

    @Override // defpackage.nck
    public final void d(ShutterButton shutterButton) {
        izm izmVar = this.a;
        shutterButton.z = (hbj) izmVar.o.a();
        shutterButton.e = (pbn) izmVar.k.a();
        shutterButton.A = (syj) this.u.a();
        shutterButton.f = (pnq) izmVar.b.a();
    }
}
