package defpackage;

import android.view.accessibility.AccessibilityManager;
import com.google.android.apps.camera.ui.hotshot.HotshotController;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class jbn {
    private final uem A;
    private final uem B;
    private final uem C;
    private final uem D;
    private final uem E;
    private final uem F;
    private final uem G;
    private final uem H;
    private final uem I;
    private final uem J;
    private final uem K;
    private final uem L;
    private final uem M;
    private final uem a;
    private final uem b;
    private final uem c;
    private final uem d;
    private final uem e;
    private final uem f;
    private final uem g;
    private final uem h;
    private final uem i;
    private final uem j;
    private final uem k;
    private final uem l;
    private final uem m;
    private final uem n;
    private final uem o;
    private final uem p;
    private final uem q;
    private final uem r;
    private final uem s;
    private final uem t;
    private final uem u;
    private final uem v;
    private final uem w;
    private final uem x;
    private final uem y;
    private final uem z;

    public jbn(uem uemVar, uem uemVar2, uem uemVar3, uem uemVar4, uem uemVar5, uem uemVar6, uem uemVar7, uem uemVar8, uem uemVar9, uem uemVar10, uem uemVar11, uem uemVar12, uem uemVar13, uem uemVar14, uem uemVar15, uem uemVar16, uem uemVar17, uem uemVar18, uem uemVar19, uem uemVar20, uem uemVar21, uem uemVar22, uem uemVar23, uem uemVar24, uem uemVar25, uem uemVar26, uem uemVar27, uem uemVar28, uem uemVar29, uem uemVar30, uem uemVar31, uem uemVar32, uem uemVar33, uem uemVar34, uem uemVar35, uem uemVar36, uem uemVar37, uem uemVar38, uem uemVar39) {
        uemVar.getClass();
        this.a = uemVar;
        uemVar2.getClass();
        this.b = uemVar2;
        uemVar3.getClass();
        this.c = uemVar3;
        uemVar4.getClass();
        this.d = uemVar4;
        uemVar5.getClass();
        this.e = uemVar5;
        this.f = uemVar6;
        this.g = uemVar7;
        this.h = uemVar8;
        uemVar9.getClass();
        this.i = uemVar9;
        this.j = uemVar10;
        uemVar11.getClass();
        this.k = uemVar11;
        uemVar12.getClass();
        this.l = uemVar12;
        uemVar13.getClass();
        this.m = uemVar13;
        uemVar14.getClass();
        this.n = uemVar14;
        this.o = uemVar15;
        uemVar16.getClass();
        this.p = uemVar16;
        uemVar17.getClass();
        this.q = uemVar17;
        uemVar18.getClass();
        this.r = uemVar18;
        this.s = uemVar19;
        uemVar20.getClass();
        this.t = uemVar20;
        uemVar21.getClass();
        this.u = uemVar21;
        uemVar22.getClass();
        this.v = uemVar22;
        uemVar23.getClass();
        this.w = uemVar23;
        uemVar24.getClass();
        this.x = uemVar24;
        uemVar25.getClass();
        this.y = uemVar25;
        uemVar26.getClass();
        this.z = uemVar26;
        uemVar27.getClass();
        this.A = uemVar27;
        this.B = uemVar28;
        uemVar29.getClass();
        this.C = uemVar29;
        uemVar30.getClass();
        this.D = uemVar30;
        this.E = uemVar31;
        this.F = uemVar32;
        uemVar33.getClass();
        this.G = uemVar33;
        uemVar34.getClass();
        this.H = uemVar34;
        uemVar35.getClass();
        this.I = uemVar35;
        uemVar36.getClass();
        this.J = uemVar36;
        this.K = uemVar37;
        uemVar38.getClass();
        this.L = uemVar38;
        uemVar39.getClass();
        this.M = uemVar39;
    }

    public final jbm a(nkw nkwVar, rwc rwcVar, kgt kgtVar, jub jubVar) {
        pbn pbnVar = (pbn) this.a.a();
        pbnVar.getClass();
        gnt gntVar = (gnt) this.b.a();
        gntVar.getClass();
        kgp kgpVar = (kgp) this.c.a();
        kgpVar.getClass();
        iyu iyuVar = (iyu) this.d.a();
        iyuVar.getClass();
        out outVar = (out) this.e.a();
        outVar.getClass();
        moy moyVar = (moy) this.f.a();
        moyVar.getClass();
        mbj mbjVar = (mbj) this.g.a();
        mbjVar.getClass();
        uh uhVarA = ((jua) this.h).a();
        mes mesVar = (mes) this.i.a();
        mesVar.getClass();
        jtl jtlVar = (jtl) this.j.a();
        jtlVar.getClass();
        ndj ndjVar = (ndj) this.k.a();
        ndjVar.getClass();
        rwc rwcVarB = ((gad) this.l).b();
        uem uemVar = this.n;
        Object objA = this.m.a();
        fvu fvuVar = (fvu) uemVar.a();
        fvuVar.getClass();
        itl itlVar = (itl) this.o.a();
        itlVar.getClass();
        fbq fbqVarA = ((fbr) this.p).a();
        msi msiVarA = ((msj) this.q).a();
        juh juhVar = (juh) this.r.a();
        juhVar.getClass();
        gtx gtxVar = (gtx) this.s.a();
        gtxVar.getClass();
        nak nakVarA = ((nal) this.t).a();
        ixf ixfVar = (ixf) this.u.a();
        ixfVar.getClass();
        ocq ocqVar = (ocq) this.v.a();
        ocqVar.getClass();
        owq owqVar = (owq) this.w.a();
        owqVar.getClass();
        hbj hbjVar = (hbj) this.x.a();
        hbjVar.getClass();
        kdh kdhVar = (kdh) this.y.a();
        kdhVar.getClass();
        lpd lpdVar = (lpd) this.z.a();
        lpdVar.getClass();
        imi imiVar = (imi) this.A.a();
        imiVar.getClass();
        rwc rwcVar2 = (rwc) this.B.a();
        rwcVar2.getClass();
        rwc rwcVar3 = (rwc) this.C.a();
        rwcVar3.getClass();
        uem uemVar2 = this.D;
        uem uemVar3 = this.E;
        AccessibilityManager accessibilityManagerA = ((imz) uemVar2).a();
        hjb hjbVar = (hjb) uemVar3.a();
        hjbVar.getClass();
        ktx ktxVar = (ktx) this.F.a();
        ktxVar.getClass();
        HotshotController hotshotController = (HotshotController) this.G.a();
        hotshotController.getClass();
        ipq ipqVar = (ipq) this.H.a();
        ipqVar.getClass();
        uem uemVar4 = this.I;
        uem uemVar5 = this.J;
        rwc rwcVarB2 = ((gad) uemVar4).b();
        muu muuVar = (muu) uemVar5.a();
        muuVar.getClass();
        owq owqVar2 = (owq) this.K.a();
        owqVar2.getClass();
        rwc rwcVar4 = (rwc) this.L.a();
        rwcVar4.getClass();
        qwz qwzVar = (qwz) this.M.a();
        qwzVar.getClass();
        nkwVar.getClass();
        return new jbm(pbnVar, gntVar, kgpVar, iyuVar, outVar, moyVar, mbjVar, uhVarA, mesVar, jtlVar, ndjVar, rwcVarB, (rwc) objA, fvuVar, itlVar, fbqVarA, msiVarA, juhVar, gtxVar, nakVarA, ixfVar, ocqVar, owqVar, hbjVar, kdhVar, lpdVar, imiVar, rwcVar2, rwcVar3, accessibilityManagerA, hjbVar, ktxVar, hotshotController, ipqVar, rwcVarB2, muuVar, owqVar2, rwcVar4, qwzVar, nkwVar, rwcVar, kgtVar, jubVar);
    }
}
