package defpackage;

import java.util.HashMap;
import java.util.Map;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class mdt {
    public static final mdt a = new mdt();
    public final Map b;

    public mdt() {
        HashMap map = new HashMap();
        this.b = map;
        map.put(ksa.UNKNOWN, ssi.UNKNOWN);
        map.put(ksa.TIMER_ZERO_SECONDS, ssi.TIMER_ZERO_SECONDS);
        map.put(ksa.TIMER_THREE_SECONDS, ssi.TIMER_THREE_SECONDS);
        map.put(ksa.TIMER_FIVE_SECONDS, ssi.TIMER_FIVE_SECONDS);
        map.put(ksa.TIMER_TEN_SECONDS, ssi.TIMER_TEN_SECONDS);
        map.put(ksa.TIMER_AUTO, ssi.TIMER_AUTO);
        map.put(ksa.PHOTO_FLASH_ON, ssi.PHOTO_FLASH_ON);
        map.put(ksa.PHOTO_FLASH_OFF, ssi.PHOTO_FLASH_OFF);
        map.put(ksa.PHOTO_FLASH_AUTO, ssi.PHOTO_FLASH_AUTO);
        map.put(ksa.PHOTO_FLASH_NS, ssi.PHOTO_FLASH_NS);
        map.put(ksa.PHOTO_FLASH_GRAYED, ssi.PHOTO_FLASH_GRAYED);
        map.put(ksa.PHOTO_FLASH_UNGRAYED, ssi.PHOTO_FLASH_UNGRAYED);
        map.put(ksa.VIDEO_FLASH_ON, ssi.VIDEO_FLASH_ON);
        map.put(ksa.VIDEO_FLASH_NS, ssi.VIDEO_FLASH_NS);
        map.put(ksa.VIDEO_FLASH_OFF, ssi.VIDEO_FLASH_OFF);
        ksa ksaVar = ksa.MICROVIDEO_ON;
        ssi ssiVar = ssi.MICROVIDEO_ON;
        map.put(ksaVar, ssiVar);
        ksa ksaVar2 = ksa.MICROVIDEO_AUTO;
        ssi ssiVar2 = ssi.MICROVIDEO_AUTO;
        map.put(ksaVar2, ssiVar2);
        ksa ksaVar3 = ksa.MICROVIDEO_OFF;
        ssi ssiVar3 = ssi.MICROVIDEO_OFF;
        map.put(ksaVar3, ssiVar3);
        map.put(ksa.MIC_INPUT_EXT_BLUETOOTH, ssi.MIC_INPUT_EXT_BLUETOOTH);
        map.put(ksa.MIC_INPUT_EXT_WIRED, ssi.MIC_INPUT_EXT_WIRED);
        map.put(ksa.MIC_INPUT_PHONE, ssi.MIC_INPUT_PHONE);
        map.put(ksa.FPS_AUTO, ssi.FPS_AUTO);
        map.put(ksa.C, ssi.FPS_24);
        map.put(ksa.FPS_30, ssi.FPS_30);
        map.put(ksa.FPS_60, ssi.FPS_60);
        map.put(ksa.BEAUTIFICATION_ON_LIGHT, ssi.BEAUTIFICATION_ON_LIGHT);
        map.put(ksa.BEAUTIFICATION_ON_STRONG, ssi.BEAUTIFICATION_ON_STRONG);
        map.put(ksa.BEAUTIFICATION_OFF, ssi.BEAUTIFICATION_OFF);
        map.put(ksa.AF_ON, ssi.AF_ON);
        map.put(ksa.AF_ON_LOCKED, ssi.AF_ON_LOCKED);
        map.put(ksa.AF_OFF_NEAR, ssi.AF_OFF_NEAR);
        map.put(ksa.AF_OFF_FAR, ssi.AF_OFF_FAR);
        map.put(ksa.AF_OFF_INFINITY, ssi.AF_OFF_INFINITY);
        map.put(ksa.IMAX_AUDIO_ON, ssi.P);
        map.put(ksa.IMAX_AUDIO_OFF, ssi.IMAX_AUDIO_OFF);
        map.put(ksa.aq, ssi.SELECTED);
        map.put(ksa.UNSELECTED, ssi.UNSELECTED);
        map.put(ksa.HORIZONTAL_PHOTO_SPHERE, ssi.HORIZONTAL_PHOTO_SPHERE);
        map.put(ksa.VERTICAL_PHOTO_SPHERE, ssi.VERTICAL_PHOTO_SPHERE);
        map.put(ksa.WIDE_ANGLE_PHOTO_SPHERE, ssi.WIDE_ANGLE_PHOTO_SPHERE);
        map.put(ksa.FISH_EYE_PHOTO_SPHERE, ssi.W);
        map.put(ksa.PHOTO_SPHERE, ssi.PHOTO_SPHERE);
        map.put(ksa.ASPECT_RATIO_SIXTEEN_BY_NINE, ssi.ASPECT_RATIO_SIXTEEN_BY_NINE);
        map.put(ksa.ASPECT_RATIO_FOUR_BY_THREE, ssi.ASPECT_RATIO_FOUR_BY_THREE);
        map.put(ksa.ASPECT_RATIO_THREE_BY_FOUR, ssi.ASPECT_RATIO_THREE_BY_FOUR);
        map.put(ksa.RES_1080P, ssi.RES_1080P);
        map.put(ksa.RES_2160P, ssi.RES_2160P);
        map.put(ksa.RES_4320P, ssi.RES_4320P);
        map.put(ksa.VIDEO_ASPECT_RATIO_SIXTEEN_BY_NINE, ssi.VIDEO_ASPECT_RATIO_SIXTEEN_BY_NINE);
        map.put(ksa.VIDEO_ASPECT_RATIO_THREE_BY_FOUR, ssi.VIDEO_ASPECT_RATIO_THREE_BY_FOUR);
        map.put(ksa.ASTRO_OFF, ssi.ASTRO_OFF);
        map.put(ksa.P, ssi.ASTRO_AUTO);
        map.put(ksa.SWISS_OFF, ssi.SWISS_OFF);
        map.put(ksa.SWISS_ON, ssi.SWISS_ON);
        map.put(ksa.LASAGNA_TR_SMALL, ssi.LASAGNA_TR_SMALL);
        map.put(ksa.LASAGNA_TR_MEDIUM, ssi.LASAGNA_TR_MEDIUM);
        map.put(ksa.LASAGNA_TR_LARGE, ssi.ao);
        map.put(ksa.COCKTAIL_PARTY_OFF, ssi.COCKTAIL_PARTY_OFF);
        map.put(ksa.COCKTAIL_PARTY_ON, ssi.COCKTAIL_PARTY_ON);
        map.put(ksa.AMETHYST_OFF, ssi.AMETHYST_OFF);
        map.put(ksa.AMETHYST_ON, ssi.AMETHYST_ON);
        map.put(ksa.TAXI_OFF, ssi.TAXI_OFF);
        map.put(ksa.TAXI_AUTO, ssi.TAXI_AUTO);
        map.put(ksa.TAXI_ON, ssi.TAXI_ON);
        map.put(ksa.CAPTURE_RESOLUTION_DEFAULT, ssi.CAPTURE_RESOLUTION_DEFAULT);
        map.put(ksa.CAPTURE_RESOLUTION_HI_RES, ssi.CAPTURE_RESOLUTION_HI_RES);
        map.put(ksa.VIDEO_STABILIZATION_STANDARD, ssi.VIDEO_STABILIZATION_STANDARD);
        map.put(ksa.VIDEO_STABILIZATION_LOCKED, ssi.VIDEO_STABILIZATION_LOCKED);
        map.put(ksa.VIDEO_STABILIZATION_ACTIVE, ssi.VIDEO_STABILIZATION_ACTIVE);
        map.put(ksa.SAPPHIRE_OFF, ssi.SAPPHIRE_OFF);
        map.put(ksa.SAPPHIRE_ON, ssi.SAPPHIRE_ON);
        map.put(ksa.ARK_SH_LESS, ssi.ARK_SH_LESS);
        map.put(ksa.ARK_SH_NORMAL, ssi.ARK_SH_NORMAL);
        map.put(ksa.ARK_SH_MORE, ssi.ARK_SH_MORE);
        map.put(ksa.ARK_LA, ssi.ARK_LA);
        map.put(ksa.ARK_LM, ssi.ARK_LM);
        map.put(ksa.SERENGETI_NS_OFF, ssi.SERENGETI_NS_OFF);
        map.put(ksa.SERENGETI_NS_AUTO, ssi.SERENGETI_NS_AUTO);
        map.put(ksa.SERENGETI_NS_ON, ssi.SERENGETI_NS_ON);
        map.put(ksa.SERENGETI_MODE_ALTERNATE, ssi.SERENGETI_MODE_ALTERNATE);
        map.put(ksa.SERENGETI_MODE_DEFAULT, ssi.SERENGETI_MODE_DEFAULT);
        map.put(ksa.FEATURE_SOUND_EFFECTS_OFF, ssi.FEATURE_SOUND_EFFECTS_OFF);
        map.put(ksa.FEATURE_SOUND_EFFECTS_ON, ssi.FEATURE_SOUND_EFFECTS_ON);
        map.put(ksaVar3, ssiVar3);
        map.put(ksaVar2, ssiVar2);
        map.put(ksaVar, ssiVar);
        map.put(ksa.MOTION_PHOTO_OFF, ssi.MOTION_PHOTO_OFF);
        map.put(ksa.MOTION_PHOTO_AUTO, ssi.MOTION_PHOTO_AUTO);
        map.put(ksa.MOTION_PHOTO_ON, ssi.MOTION_PHOTO_ON);
    }
}
