package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class mo {
    public static final int[] a = {R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.gravity, R.attr.text, R.attr.maxLines, R.attr.lineSpacingExtra, R.attr.lineSpacingMultiplier, R.attr.fontFamily, com.google.ar.core.R.attr.maxTextSize, com.google.ar.core.R.attr.minTextSize};
    public static final int[] b = {R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.gravity, R.attr.src, R.attr.text, R.attr.maxLines, R.attr.color, R.attr.lineSpacingExtra, R.attr.lineSpacingMultiplier, R.attr.fontFamily, R.attr.elevation, R.attr.stateListAnimator, com.google.ar.core.R.attr.buttonRippleColor, com.google.ar.core.R.attr.imageScaleMode, com.google.ar.core.R.attr.maxTextSize, com.google.ar.core.R.attr.minTextSize, com.google.ar.core.R.attr.pressedButtonTranslationZ};
    public static final int[] c = {R.attr.src, com.google.ar.core.R.attr.background_border_cap, com.google.ar.core.R.attr.background_border_color, com.google.ar.core.R.attr.background_border_width, com.google.ar.core.R.attr.background_color, com.google.ar.core.R.attr.background_radius, com.google.ar.core.R.attr.background_radius_percent, com.google.ar.core.R.attr.background_radius_pressed, com.google.ar.core.R.attr.background_radius_pressed_percent, com.google.ar.core.R.attr.background_shadow_width, com.google.ar.core.R.attr.circle_border_cap, com.google.ar.core.R.attr.circle_border_color, com.google.ar.core.R.attr.circle_border_width, com.google.ar.core.R.attr.circle_color, com.google.ar.core.R.attr.circle_padding, com.google.ar.core.R.attr.circle_radius, com.google.ar.core.R.attr.circle_radius_percent, com.google.ar.core.R.attr.circle_radius_pressed, com.google.ar.core.R.attr.circle_radius_pressed_percent, com.google.ar.core.R.attr.clip_dimen, com.google.ar.core.R.attr.image_circle_percentage, com.google.ar.core.R.attr.image_horizontal_offcenter_percentage, com.google.ar.core.R.attr.image_tint, com.google.ar.core.R.attr.img_circle_percentage, com.google.ar.core.R.attr.img_horizontal_offset_percentage, com.google.ar.core.R.attr.img_padding, com.google.ar.core.R.attr.img_tint, com.google.ar.core.R.attr.shadow_width, com.google.ar.core.R.attr.square_dimen};
    public static final int[] d = {R.attr.clickable, R.attr.src, R.attr.color, R.attr.elevation, R.attr.stateListAnimator, com.google.ar.core.R.attr.buttonRippleColor, com.google.ar.core.R.attr.imageScaleMode, com.google.ar.core.R.attr.pressedButtonTranslationZ};
    public static final int[] e = {com.google.ar.core.R.attr.pageIndicatorDotColor, com.google.ar.core.R.attr.pageIndicatorDotColorSelected, com.google.ar.core.R.attr.pageIndicatorDotFadeInDuration, com.google.ar.core.R.attr.pageIndicatorDotFadeOutDelay, com.google.ar.core.R.attr.pageIndicatorDotFadeOutDuration, com.google.ar.core.R.attr.pageIndicatorDotFadeWhenIdle, com.google.ar.core.R.attr.pageIndicatorDotRadius, com.google.ar.core.R.attr.pageIndicatorDotRadiusSelected, com.google.ar.core.R.attr.pageIndicatorDotShadowColor, com.google.ar.core.R.attr.pageIndicatorDotShadowDx, com.google.ar.core.R.attr.pageIndicatorDotShadowDy, com.google.ar.core.R.attr.pageIndicatorDotShadowRadius, com.google.ar.core.R.attr.pageIndicatorDotSpacing, com.google.ar.core.R.attr.wsPageIndicatorDotColor, com.google.ar.core.R.attr.wsPageIndicatorDotColorSelected, com.google.ar.core.R.attr.wsPageIndicatorDotFadeInDuration, com.google.ar.core.R.attr.wsPageIndicatorDotFadeOutDelay, com.google.ar.core.R.attr.wsPageIndicatorDotFadeOutDuration, com.google.ar.core.R.attr.wsPageIndicatorDotFadeWhenIdle, com.google.ar.core.R.attr.wsPageIndicatorDotRadius, com.google.ar.core.R.attr.wsPageIndicatorDotRadiusSelected, com.google.ar.core.R.attr.wsPageIndicatorDotShadowColor, com.google.ar.core.R.attr.wsPageIndicatorDotShadowDx, com.google.ar.core.R.attr.wsPageIndicatorDotShadowDy, com.google.ar.core.R.attr.wsPageIndicatorDotShadowRadius, com.google.ar.core.R.attr.wsPageIndicatorDotSpacing};
}
