package defpackage;

import android.content.Context;
import android.view.accessibility.AccessibilityManager;
import com.google.android.apps.camera.ui.hotshot.HotshotController;
import java.util.concurrent.ScheduledExecutorService;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class mvw implements tzt {
    private final tzx A;
    private final tzx B;
    private final tzx C;
    private final tzx D;
    private final tzx E;
    private final tzx F;
    private final tzx G;
    private final tzx H;
    private final tzx I;
    private final tzx J;
    private final tzx K;
    private final tzx L;
    private final tzx M;
    private final tzx N;
    private final tzx O;
    private final tzx P;
    private final tzx a;
    private final tzx b;
    private final tzx c;
    private final tzx d;
    private final tzx e;
    private final tzx f;
    private final tzx g;
    private final tzx h;
    private final tzx i;
    private final tzx j;
    private final tzx k;
    private final tzx l;
    private final tzx m;
    private final tzx n;
    private final tzx o;
    private final tzx p;
    private final tzx q;
    private final tzx r;
    private final tzx s;
    private final tzx t;
    private final tzx u;
    private final tzx v;
    private final tzx w;
    private final tzx x;
    private final tzx y;
    private final tzx z;

    public mvw(tzx tzxVar, tzx tzxVar2, tzx tzxVar3, tzx tzxVar4, tzx tzxVar5, tzx tzxVar6, tzx tzxVar7, tzx tzxVar8, tzx tzxVar9, tzx tzxVar10, tzx tzxVar11, tzx tzxVar12, tzx tzxVar13, tzx tzxVar14, tzx tzxVar15, tzx tzxVar16, tzx tzxVar17, tzx tzxVar18, tzx tzxVar19, tzx tzxVar20, tzx tzxVar21, tzx tzxVar22, tzx tzxVar23, tzx tzxVar24, tzx tzxVar25, tzx tzxVar26, tzx tzxVar27, tzx tzxVar28, tzx tzxVar29, tzx tzxVar30, tzx tzxVar31, tzx tzxVar32, tzx tzxVar33, tzx tzxVar34, tzx tzxVar35, tzx tzxVar36, tzx tzxVar37, tzx tzxVar38, tzx tzxVar39, tzx tzxVar40, tzx tzxVar41, tzx tzxVar42) {
        this.a = tzxVar;
        this.b = tzxVar2;
        this.c = tzxVar3;
        this.d = tzxVar4;
        this.e = tzxVar5;
        this.f = tzxVar6;
        this.g = tzxVar7;
        this.h = tzxVar8;
        this.i = tzxVar9;
        this.j = tzxVar10;
        this.k = tzxVar11;
        this.l = tzxVar12;
        this.m = tzxVar13;
        this.n = tzxVar14;
        this.o = tzxVar15;
        this.p = tzxVar16;
        this.q = tzxVar17;
        this.r = tzxVar18;
        this.s = tzxVar19;
        this.t = tzxVar20;
        this.u = tzxVar21;
        this.v = tzxVar22;
        this.w = tzxVar23;
        this.x = tzxVar24;
        this.y = tzxVar25;
        this.z = tzxVar26;
        this.A = tzxVar27;
        this.B = tzxVar28;
        this.C = tzxVar29;
        this.D = tzxVar30;
        this.E = tzxVar31;
        this.F = tzxVar32;
        this.G = tzxVar33;
        this.H = tzxVar34;
        this.I = tzxVar35;
        this.J = tzxVar36;
        this.K = tzxVar37;
        this.L = tzxVar38;
        this.M = tzxVar39;
        this.N = tzxVar40;
        this.O = tzxVar41;
        this.P = tzxVar42;
    }

    @Override // defpackage.uem, defpackage.uel
    public final /* synthetic */ Object a() {
        Context contextB = ((imm) this.a).b();
        owf owfVar = (owf) this.b.a();
        iyu iyuVar = (iyu) this.c.a();
        mbj mbjVar = (mbj) this.e.a();
        AccessibilityManager accessibilityManagerA = ((imz) this.f).a();
        hbj hbjVar = (hbj) this.g.a();
        luj lujVar = (luj) this.h.a();
        hjb hjbVar = (hjb) this.i.a();
        owq owqVar = (owq) this.j.a();
        gnt gntVar = (gnt) this.k.a();
        mvk mvkVar = (mvk) this.l.a();
        krj krjVar = (krj) this.n.a();
        ndj ndjVar = (ndj) this.o.a();
        ScheduledExecutorService scheduledExecutorService = (ScheduledExecutorService) this.p.a();
        owf owfVar2 = (owf) this.q.a();
        owf owfVar3 = (owf) this.r.a();
        fdq fdqVarA = ((ixw) this.s).a();
        owq owqVar2 = (owq) this.t.a();
        ktx ktxVar = (ktx) this.u.a();
        owq owqVar3 = (owq) this.v.a();
        myl mylVar = (myl) this.w.a();
        owq owqVar4 = (owq) this.x.a();
        cxb cxbVar = (cxb) this.y.a();
        owf owfVar4 = (owf) this.z.a();
        out outVar = (out) this.A.a();
        owq owqVar5 = (owq) this.B.a();
        pbn pbnVar = (pbn) this.C.a();
        mwb mwbVar = (mwb) this.D.a();
        mwc mwcVar = (mwc) this.E.a();
        owf owfVar5 = (owf) this.F.a();
        mva mvaVar = (mva) this.G.a();
        imi imiVar = (imi) this.H.a();
        itl itlVar = (itl) this.I.a();
        tzx tzxVar = this.J;
        tzx tzxVar2 = this.K;
        lvq lvqVarA = ((lvr) tzxVar).a();
        owf owfVar6 = (owf) tzxVar2.a();
        mwq mwqVar = (mwq) this.N.a();
        return new HotshotController(contextB, owfVar, iyuVar.K.j, mbjVar, accessibilityManagerA, hbjVar, lujVar, hjbVar, owqVar, gntVar, mvkVar, krjVar, ndjVar, scheduledExecutorService, owfVar2, owfVar3, fdqVarA, owqVar2, ktxVar, owqVar3, mylVar, owqVar4, cxbVar, owfVar4, outVar, owqVar5, pbnVar, mwbVar, mwcVar, owfVar5, mvaVar, imiVar, itlVar, lvqVarA, owfVar6, mwqVar, (owf) this.P.a());
    }
}
