package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class psu {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final cfp D;
    public static final cfd E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final cfp I;
    public static final cfd J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final cfp N;
    public static final cfd O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final cfp S;
    public static final cfd T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final cfp X;
    public static final cfd Y;
    public static final long Z;
    public static final cfd a;
    public static final long aa;
    public static final long ab;
    public static final cfp ac;
    public static final cfd ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final cfp ah;
    public static final cfd ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final cfp am;
    public static final cfd an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final cfp ar;
    public static final cfd as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final cfp aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final cfp e;
    public static final cfd f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final cfp j;
    public static final cfd k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final cfp o;
    public static final cfd p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final cfp t;
    public static final cfd u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final cfp y;
    public static final cfd z;

    static {
        cfd cfdVar = psw.a;
        a = psw.b;
        b = chp.A(24.0d);
        c = chp.C(16);
        d = chp.A(0.0d);
        e = psw.d;
        f = psw.b;
        g = chp.A(20.0d);
        h = chp.C(14);
        i = chp.A(0.0d);
        j = psw.d;
        k = psw.b;
        l = chp.A(16.0d);
        m = chp.C(12);
        n = chp.A(0.0d);
        o = psw.d;
        p = psw.a;
        q = chp.A(64.0d);
        r = chp.C(57);
        s = chp.A(0.0d);
        t = psw.d;
        u = psw.a;
        v = chp.A(52.0d);
        w = chp.C(45);
        x = chp.A(0.0d);
        y = psw.d;
        z = psw.a;
        A = chp.A(44.0d);
        B = chp.C(36);
        C = chp.A(0.0d);
        D = psw.d;
        E = psw.a;
        F = chp.A(40.0d);
        G = chp.C(32);
        H = chp.A(0.0d);
        I = psw.d;
        J = psw.a;
        K = chp.A(36.0d);
        L = chp.C(28);
        M = chp.A(0.0d);
        N = psw.d;
        O = psw.a;
        P = chp.A(32.0d);
        Q = chp.C(24);
        R = chp.A(0.0d);
        S = psw.d;
        T = psw.b;
        U = chp.A(20.0d);
        V = chp.C(14);
        W = chp.A(0.0d);
        X = psw.c;
        Y = psw.b;
        Z = chp.A(16.0d);
        aa = chp.C(12);
        ab = chp.A(0.1d);
        ac = psw.c;
        ad = psw.b;
        ae = chp.A(16.0d);
        af = chp.C(11);
        ag = chp.A(0.1d);
        ah = psw.c;
        ai = psw.a;
        aj = chp.A(28.0d);
        ak = chp.C(22);
        al = chp.A(0.0d);
        am = psw.d;
        an = psw.b;
        ao = chp.A(24.0d);
        ap = chp.C(16);
        aq = chp.A(0.0d);
        ar = psw.c;
        as = psw.b;
        at = chp.A(20.0d);
        au = chp.C(14);
        av = chp.A(0.0d);
        aw = psw.c;
    }
}
