package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class pte {
    public static final cfd T;
    public static final cfp U;
    public static final cfd V;
    public static final cfp W;
    public static final cfd X;
    public static final cfp Y;
    public static final cfd Z;
    public static final cfp aa;
    public static final cfd ab;
    public static final cfp ac;
    public static final cfd ad;
    public static final cfp ae;
    public static final cfd af;
    public static final cfp ag;
    public static final cfd ah;
    public static final cfp ai;
    public static final cfd aj;
    public static final cfp ak;
    public static final cfd al;
    public static final cfp am;
    public static final cfd an;
    public static final cfp ao;
    public static final cfd ap;
    public static final cfp aq;
    public static final cfd ar;
    public static final cfp as;
    public static final cfd at;
    public static final cfp au;
    public static final cfd av;
    public static final cfp aw;
    public static final long a = chp.A(24.0d);
    private static final float ax = 16.0f;
    public static final long b = chp.C(16);
    public static final long c = chp.A(0.0d);
    private static final float ay = 100.0f;
    private static final float az = 400.0f;
    public static final long d = chp.A(20.0d);
    private static final float aA = 14.0f;
    public static final long e = chp.C(14);
    public static final long f = chp.A(0.0d);
    private static final float aB = 100.0f;
    private static final float aC = 400.0f;
    public static final long g = chp.A(16.0d);
    private static final float aD = 12.0f;
    public static final long h = chp.C(12);
    public static final long i = chp.A(0.1d);
    private static final float aE = 100.0f;
    private static final float aF = 400.0f;
    public static final long j = chp.A(64.0d);
    private static final float aG = 57.0f;
    public static final long k = chp.C(57);
    public static final long l = chp.A(0.0d);
    private static final float aH = 100.0f;
    private static final float aI = 400.0f;
    public static final long m = chp.A(52.0d);
    private static final float aJ = 45.0f;
    public static final long n = chp.C(45);
    public static final long o = chp.A(0.0d);
    private static final float aK = 100.0f;
    private static final float aL = 400.0f;
    public static final long p = chp.A(44.0d);
    private static final float aM = 36.0f;
    public static final long q = chp.C(36);
    public static final long r = chp.A(0.0d);
    private static final float aN = 100.0f;
    private static final float aO = 400.0f;
    public static final long s = chp.A(40.0d);
    private static final float aP = 32.0f;
    public static final long t = chp.C(32);
    public static final long u = chp.A(0.0d);
    private static final float aQ = 100.0f;
    private static final float aR = 400.0f;
    public static final long v = chp.A(36.0d);
    private static final float aS = 28.0f;
    public static final long w = chp.C(28);
    public static final long x = chp.A(0.0d);
    private static final float aT = 100.0f;
    private static final float aU = 400.0f;
    public static final long y = chp.A(32.0d);
    private static final float aV = 24.0f;
    public static final long z = chp.C(24);
    public static final long A = chp.A(0.0d);
    private static final float aW = 100.0f;
    private static final float aX = 400.0f;
    public static final long B = chp.A(20.0d);
    private static final float aY = 14.0f;
    public static final long C = chp.C(14);
    public static final long D = chp.A(0.0d);
    private static final float aZ = 100.0f;
    private static final float ba = 500.0f;
    public static final long E = chp.A(16.0d);
    private static final float bb = 12.0f;
    public static final long F = chp.C(12);
    public static final long G = chp.A(0.0d);
    private static final float bc = 100.0f;
    private static final float bd = 500.0f;
    public static final long H = chp.A(16.0d);
    private static final float be = 11.0f;
    public static final long I = chp.C(11);
    public static final long J = chp.A(0.1d);
    private static final float bf = 100.0f;
    private static final float bg = 500.0f;
    public static final long K = chp.A(28.0d);
    private static final float bh = 22.0f;
    public static final long L = chp.C(22);
    public static final long M = chp.A(0.0d);
    private static final float bi = 100.0f;
    private static final float bj = 400.0f;
    public static final long N = chp.A(24.0d);
    private static final float bk = 16.0f;
    public static final long O = chp.C(16);
    public static final long P = chp.A(0.0d);
    private static final float bl = 100.0f;
    private static final float bm = 500.0f;
    public static final long Q = chp.A(20.0d);
    private static final float bn = 14.0f;
    public static final long R = chp.C(14);
    public static final long S = chp.A(0.0d);
    private static final float bo = 100.0f;
    private static final float bp = 500.0f;

    static {
        new cfo(bqs.m("wdth", 100.0f), bqs.m("wght", 400.0f), bqs.m("opsz", 16.0f), bqs.m("GRAD", 0.0f), bqs.m("slnt", 0.0f), bqs.m("ROND", 0.0f));
        cfd cfdVar = psw.a;
        T = psw.b;
        U = psw.e;
        new cfo(bqs.m("ROND", 0.0f), bqs.m("wght", 400.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 14.0f), bqs.m("slnt", 0.0f), bqs.m("wdth", 100.0f));
        V = psw.b;
        W = psw.e;
        new cfo(bqs.m("slnt", 0.0f), bqs.m("ROND", 0.0f), bqs.m("opsz", 12.0f), bqs.m("wght", 400.0f), bqs.m("wdth", 100.0f), bqs.m("GRAD", 0.0f));
        X = psw.b;
        Y = psw.e;
        new cfo(bqs.m("ROND", 0.0f), bqs.m("slnt", 0.0f), bqs.m("opsz", 57.0f), bqs.m("wdth", 100.0f), bqs.m("wght", 400.0f), bqs.m("GRAD", 0.0f));
        Z = psw.a;
        aa = psw.e;
        new cfo(bqs.m("wdth", 100.0f), bqs.m("ROND", 0.0f), bqs.m("wght", 400.0f), bqs.m("slnt", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 45.0f));
        ab = psw.a;
        ac = psw.e;
        new cfo(bqs.m("ROND", 0.0f), bqs.m("slnt", 0.0f), bqs.m("wght", 400.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 36.0f), bqs.m("wdth", 100.0f));
        ad = psw.a;
        ae = psw.e;
        new cfo(bqs.m("wdth", 100.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 32.0f), bqs.m("ROND", 0.0f), bqs.m("slnt", 0.0f), bqs.m("wght", 400.0f));
        af = psw.a;
        ag = psw.e;
        new cfo(bqs.m("slnt", 0.0f), bqs.m("wght", 400.0f), bqs.m("ROND", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 28.0f), bqs.m("wdth", 100.0f));
        ah = psw.a;
        ai = psw.e;
        new cfo(bqs.m("wdth", 100.0f), bqs.m("GRAD", 0.0f), bqs.m("wght", 400.0f), bqs.m("slnt", 0.0f), bqs.m("ROND", 0.0f), bqs.m("opsz", 24.0f));
        aj = psw.a;
        ak = psw.e;
        new cfo(bqs.m("wght", 500.0f), bqs.m("slnt", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 14.0f), bqs.m("wdth", 100.0f), bqs.m("ROND", 0.0f));
        al = psw.b;
        am = psw.d;
        new cfo(bqs.m("wdth", 100.0f), bqs.m("GRAD", 0.0f), bqs.m("ROND", 0.0f), bqs.m("opsz", 12.0f), bqs.m("slnt", 0.0f), bqs.m("wght", 500.0f));
        an = psw.b;
        ao = psw.d;
        new cfo(bqs.m("wdth", 100.0f), bqs.m("ROND", 0.0f), bqs.m("opsz", 11.0f), bqs.m("slnt", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("wght", 500.0f));
        ap = psw.b;
        aq = psw.d;
        new cfo(bqs.m("opsz", 22.0f), bqs.m("wght", 400.0f), bqs.m("slnt", 0.0f), bqs.m("wdth", 100.0f), bqs.m("ROND", 0.0f), bqs.m("GRAD", 0.0f));
        ar = psw.a;
        as = psw.e;
        new cfo(bqs.m("slnt", 0.0f), bqs.m("wdth", 100.0f), bqs.m("wght", 500.0f), bqs.m("ROND", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("opsz", 16.0f));
        at = psw.b;
        au = psw.d;
        new cfo(bqs.m("slnt", 0.0f), bqs.m("GRAD", 0.0f), bqs.m("wght", 500.0f), bqs.m("opsz", 14.0f), bqs.m("ROND", 0.0f), bqs.m("wdth", 100.0f));
        av = psw.b;
        aw = psw.d;
    }
}
