package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class rri {
    public static final float A;
    public static final long B;
    public static final float C;
    public static final long D;
    public static final long E;
    public static final float F;
    public static final float G;
    public static final long H;
    public static final float I;
    public static final long J;
    public static final long K;
    public static final float L;
    public static final float M;
    public static final long N;
    public static final float O;
    public static final long P;
    public static final long Q;
    public static final float R;
    public static final float S;
    public static final long T;
    public static final float U;
    public static final long V;
    public static final long W;
    public static final float X;
    public static final float Y;
    public static final long Z;
    public static final long a;
    public static final float aA;
    public static final float aB;
    public static final long aC;
    public static final float aD;
    public static final long aE;
    public static final long aF;
    public static final float aG;
    public static final float aH;
    public static final long aI;
    public static final float aJ;
    public static final long aK;
    public static final long aL;
    public static final float aM;
    public static final float aN;
    public static final long aO;
    public static final float aP;
    public static final long aQ;
    public static final long aR;
    public static final float aS;
    public static final float aT;
    public static final long aU;
    public static final float aV;
    public static final long aW;
    public static final long aX;
    public static final float aY;
    public static final float aZ;
    public static final float aa;
    public static final long ab;
    public static final float ac;
    public static final float ad;
    public static final long ae;
    public static final float af;
    public static final long ag;
    public static final long ah;
    public static final float ai;
    public static final float aj;
    public static final long ak;
    public static final float al;
    public static final long am;
    public static final long an;
    public static final float ao;
    public static final float ap;
    public static final long aq;
    public static final float ar;
    public static final long as;
    public static final long at;
    public static final float au;
    public static final float av;
    public static final long aw;
    public static final float ax;
    public static final long ay;
    public static final long az;
    public static final float b;
    public static final long ba;
    public static final float bb;
    public static final long bc;
    public static final long bd;
    public static final float be;
    public static final float bf;
    public static final long bg;
    public static final float bh;
    public static final long bi;
    public static final long bj;
    public static final float bk;
    public static final float bl;
    public static final long bm;
    public static final float bn;
    public static final long bo;
    public static final long bp;
    public static final float bq;
    public static final float br;
    public static final long bs;
    public static final float bt;
    public static final long bu;
    public static final long bv;
    public static final float bw;
    public static final float bx;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final float f;
    public static final float g;
    public static final long h;
    public static final float i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final float m;
    public static final float n;
    public static final long o;
    public static final float p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final float t;
    public static final float u;
    public static final long v;
    public static final float w;
    public static final long x;
    public static final long y;
    public static final float z;

    static {
        int i2 = rrj.a;
        a = chp.A(22.0d);
        b = 100.0f;
        c = chp.C(18);
        d = chp.A(1.6d);
        e = chp.A(0.4d);
        f = 599.0f;
        g = 100.0f;
        h = chp.A(18.0d);
        i = 100.0f;
        j = chp.C(15);
        k = chp.A(1.4d);
        l = chp.A(0.6d);
        m = 599.0f;
        n = 90.0f;
        o = chp.A(16.0d);
        p = 100.0f;
        q = chp.C(14);
        r = chp.A(1.4d);
        s = chp.A(0.6d);
        t = 550.0f;
        u = 90.0f;
        v = chp.A(12.0d);
        w = 100.0f;
        x = chp.C(10);
        y = chp.A(0.4d);
        z = 500.0f;
        A = 84.0f;
        B = chp.A(18.0d);
        C = 100.0f;
        D = chp.C(16);
        E = chp.A(0.4d);
        F = 450.0f;
        G = 90.0f;
        H = chp.A(16.0d);
        I = 100.0f;
        J = chp.C(14);
        K = chp.A(0.4d);
        L = 450.0f;
        M = 90.0f;
        N = chp.A(14.0d);
        O = 100.0f;
        P = chp.C(12);
        Q = chp.A(0.4d);
        R = 500.0f;
        S = 86.0f;
        T = chp.A(44.0d);
        U = 100.0f;
        V = chp.C(40);
        W = chp.A(0.0d);
        X = 450.0f;
        Y = 100.0f;
        Z = chp.A(34.0d);
        aa = 100.0f;
        ab = chp.C(30);
        chp.A(0.0d);
        ac = 500.0f;
        ad = 100.0f;
        ae = chp.A(26.0d);
        af = 100.0f;
        ag = chp.C(24);
        ah = chp.A(0.0d);
        ai = 500.0f;
        aj = 100.0f;
        ak = chp.A(22.0d);
        al = 100.0f;
        am = chp.C(20);
        an = chp.A(0.4d);
        ao = 500.0f;
        ap = 100.0f;
        aq = chp.A(18.0d);
        ar = 100.0f;
        as = chp.C(15);
        at = chp.A(0.4d);
        au = 500.0f;
        av = 90.0f;
        aw = chp.A(16.0d);
        ax = 100.0f;
        ay = chp.C(13);
        az = chp.A(0.4d);
        aA = 500.0f;
        aB = 84.0f;
        aC = chp.A(60.0d);
        aD = 100.0f;
        aE = chp.C(60);
        aF = chp.A(0.0d);
        aG = 550.0f;
        aH = 100.0f;
        aI = chp.A(24.0d);
        aJ = 100.0f;
        aK = chp.C(24);
        aL = chp.A(0.0d);
        aM = 550.0f;
        aN = 100.0f;
        aO = chp.A(50.0d);
        aP = 100.0f;
        aQ = chp.C(50);
        aR = chp.A(0.0d);
        aS = 599.0f;
        aT = 100.0f;
        aU = chp.A(40.0d);
        aV = 100.0f;
        aW = chp.C(40);
        aX = chp.A(0.0d);
        aY = 599.0f;
        aZ = 100.0f;
        ba = chp.A(30.0d);
        bb = 100.0f;
        bc = chp.C(30);
        bd = chp.A(0.0d);
        be = 599.0f;
        bf = 100.0f;
        bg = chp.A(20.0d);
        bh = 100.0f;
        bi = chp.C(18);
        bj = chp.A(0.0d);
        bk = 500.0f;
        bl = 100.0f;
        bm = chp.A(18.0d);
        bn = 100.0f;
        bo = chp.C(16);
        bp = chp.A(0.2d);
        bq = 550.0f;
        br = 100.0f;
        bs = chp.A(16.0d);
        bt = 100.0f;
        bu = chp.C(14);
        bv = chp.A(0.4d);
        bw = 550.0f;
        bx = 100.0f;
    }
}
