package defpackage;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class tma {
    public static final tiw A;
    public static final tiv B;
    public static final tiw C;
    public static final tiv D;
    public static final tiw E;
    public static final tiv F;
    public static final tiw G;
    public static final tiv H;
    public static final tiw I;
    public static final tiv J;
    public static final tiw K;
    public static final tiv L;
    public static final tiw M;
    public static final tiv N;
    public static final tiw O;
    public static final tiv P;
    public static final tiw Q;
    public static final tiv R;
    public static final tiw S;
    public static final tiv T;
    public static final tiw U;
    public static final tiw V;
    public static final tiv a;
    public static final tiw b;
    public static final tiv c;
    public static final tiw d;
    public static final tiv e;
    public static final tiv f;
    public static final tiw g;
    public static final tiv h;
    public static final tiw i;
    public static final tiv j;
    public static final tiw k;
    public static final tiv l;
    public static final tiw m;
    public static final tiv n;
    public static final tiw o;
    public static final tiv p;
    public static final tiw q;
    public static final tiv r;
    public static final tiw s;
    public static final tiv t;
    public static final tiv u;
    public static final tiw v;
    public static final tiv w;
    public static final tiv x;
    public static final tiv y;
    public static final tiv z;

    static {
        tiv tivVarB = new tlg().b();
        a = tivVarB;
        b = new tls(Class.class, tivVarB, 1);
        tiv tivVarB2 = new tlp().b();
        c = tivVarB2;
        d = new tls(BitSet.class, tivVarB2, 1);
        tlt tltVar = new tlt();
        e = tltVar;
        f = new tlu();
        g = new tlq(Boolean.TYPE, Boolean.class, tltVar, 1, null);
        tlv tlvVar = new tlv();
        h = tlvVar;
        i = new tlq(Byte.TYPE, Byte.class, tlvVar, 1, null);
        tlw tlwVar = new tlw();
        j = tlwVar;
        k = new tlq(Short.TYPE, Short.class, tlwVar, 1, null);
        tlx tlxVar = new tlx();
        l = tlxVar;
        m = new tlq(Integer.TYPE, Integer.class, tlxVar, 1, null);
        tiv tivVarB3 = new tly().b();
        n = tivVarB3;
        o = new tls(AtomicInteger.class, tivVarB3, 1);
        tiv tivVarB4 = new tlz().b();
        p = tivVarB4;
        q = new tls(AtomicBoolean.class, tivVarB4, 1);
        tiv tivVarB5 = new tky().b();
        r = tivVarB5;
        s = new tls(AtomicIntegerArray.class, tivVarB5, 1);
        t = new tkz();
        tla tlaVar = new tla();
        u = tlaVar;
        v = new tlq(Character.TYPE, Character.class, tlaVar, 1, null);
        tlb tlbVar = new tlb();
        w = tlbVar;
        x = new tlc();
        y = new tld();
        z = new tle();
        A = new tls(String.class, tlbVar, 1);
        tlf tlfVar = new tlf();
        B = tlfVar;
        C = new tls(StringBuilder.class, tlfVar, 1);
        tlh tlhVar = new tlh();
        D = tlhVar;
        E = new tls(StringBuffer.class, tlhVar, 1);
        tli tliVar = new tli();
        F = tliVar;
        G = new tls(URL.class, tliVar, 1);
        tlj tljVar = new tlj();
        H = tljVar;
        I = new tls(URI.class, tljVar, 1);
        tlk tlkVar = new tlk();
        J = tlkVar;
        K = new tls(InetAddress.class, tlkVar, 0);
        tll tllVar = new tll();
        L = tllVar;
        M = new tls(UUID.class, tllVar, 1);
        tiv tivVarB6 = new tlm().b();
        N = tivVarB6;
        O = new tls(Currency.class, tivVarB6, 1);
        tln tlnVar = new tln();
        P = tlnVar;
        Q = new tlq(Calendar.class, GregorianCalendar.class, tlnVar, 0);
        tlo tloVar = new tlo();
        R = tloVar;
        S = new tls(Locale.class, tloVar, 1);
        tkh tkhVar = tkh.a;
        T = tkhVar;
        U = new tls(til.class, tkhVar, 0);
        V = tkf.a;
    }
}
